
import re
CARDS_PATH = '/Users/radekmajewski/Downloads/valujack/public/cards.js'
descriptions = {
    328: ('Krka DD', 'Slovenian generic pharma. Dividend compounder.', 'European generic pharma.', "Krka is a Slovenian pharmaceutical company specialising in generic drugs, OTC products, and animal health across Central and Eastern Europe and beyond. The company has consistently high margins and returns on capital across its diversified generic drug portfolio.", 'Quality pharma. Underappreciated compounder.', 'Hidden European compounder.', "A high-quality Slovenian generic pharmaceutical company with a 19.4% ROIC and a 3.4% dividend yield. Krka operates in structurally growing generic drug markets across Europe and has compounded earnings steadily for over a decade.", ["Leading Slovenian generic pharmaceutical company with operations across 70+ countries.", "ROIC of 19.4% — exceptional for a generic pharma business reflecting strong operational efficiency.", "EPS grew 7.3% annualised with consistent margins across economic cycles.", "Dividend yield of 3.4% backed by strong free cash flow from a diversified drug portfolio."], 'KING'),
    358: ('Kunlun Energy Co Ltd', 'Chinese natural gas distributor. Steady yield.', 'China gas distribution.', "Kunlun Energy is a Hong Kong-listed natural gas distribution company operating pipelines and LNG receiving terminals across China. The company benefits from structural shift from coal to natural gas as the government pursues cleaner energy targets.", 'China gas transition. Steady income.', 'Energy transition compounder.', "A Chinese natural gas distributor with a 4.6% dividend yield and ROIC of 13.6%. Kunlun Energy operates in a structurally growing market as China accelerates its coal-to-gas transition with predictable regulated returns from pipeline assets.", ["Natural gas pipelines and LNG terminals across China — essential energy infrastructure.", "Structural tailwind from China coal-to-gas transition and clean energy policy targets.", "ROIC of 13.6% reflects steady regulated returns from long-life pipeline assets.", "Dividend yield of 4.6% backed by predictable cash flows from regulated distribution."], 'KING'),
    387: ('ACT Energy Technologies Ltd', 'Canadian oilfield tubular services. Recovery play.', 'Oilfield services recovery.', "ACT Energy Technologies provides tubular running services and equipment rental to the Canadian oil and gas industry. The company operates in the Western Canadian Sedimentary Basin and benefits from rising Canadian energy investment.", 'Canadian oilfield services. Recovery momentum.', 'Energy services recovery.', "A Canadian oilfield tubular services company recovering in the Western Canadian energy sector. ACT Energy benefits from rising Canadian energy investment and tight oil activity expansion with revenue growing consistently.", ["Tubular running services and equipment rental for Canadian oil and gas producers.", "Operations in the Western Canadian Sedimentary Basin — core Canadian energy geography.", "Revenue grew 9.8% annualised as Canadian energy investment activity expanded.", "Recovery play with improving margins as oilfield services pricing strengthens."], 'JACK'),
    599: ('5th Planet Games', 'Danish mobile gaming studio. Growth recovery.', 'Mobile gaming recovery.', "5th Planet Games is a Danish mobile game developer creating fantasy and adventure games for global audiences. The company is recovering from a difficult period and building a new game portfolio targeting the growing mobile gaming market.", 'Mobile gaming. Growth recovery play.', 'Gaming studio recovery.', "A Danish mobile game developer showing growth recovery momentum. 5th Planet Games is rebuilding its game portfolio for the mobile gaming market — a high-growth digital entertainment segment with global reach and low distribution costs.", ["Danish mobile game developer targeting global fantasy and adventure gaming audiences.", "Recovering game portfolio with new titles targeting the growing mobile gaming market.", "EPS growing as new game launches and player acquisition strategies improve.", "Mobile gaming benefits from global distribution with minimal physical infrastructure costs."], 'JOKER'),
    607: ('Array Digital Infrastructure Inc', 'US digital infrastructure. High revenue growth.', 'Digital infrastructure growth.', "Array Digital Infrastructure is a US company building data centres, fibre networks, and wireless tower assets supporting growing demand for digital connectivity and cloud computing. The company is in a high-growth investment phase.", 'Digital infrastructure. High revenue growth.', 'Digital infrastructure compounder.', "A US digital infrastructure company with revenue growth of 58.3% annualised building data centres and connectivity assets. Array Digital Infrastructure benefits from structural demand as cloud computing and connectivity investment accelerates.", ["Data centres, fibre networks and wireless towers for digital connectivity infrastructure.", "Revenue grew 58.3% annualised as digital infrastructure demand accelerated strongly.", "Structural tailwind from cloud computing and mobile data consumption growth.", "High capital investment phase building assets that generate long-term recurring revenue."], 'JOKER'),
    616: ('Concejo B', 'Swedish IT consulting. Growth recovery.', 'Swedish IT consulting recovery.', "Concejo is a Swedish IT consulting company providing technology consulting and digital services to enterprise clients. The company is recovering from restructuring with improving financial metrics through better project execution and client retention.", 'Swedish IT consulting. Growth recovery.', 'IT consulting recovery play.', "A Swedish IT consulting company with an 8.1% ROIC showing growth recovery. Concejo provides technology consulting to Swedish enterprise clients — improving financial trajectory as IT consulting demand and project execution metrics recover.", ["IT consulting and digital services for Swedish enterprise clients.", "ROIC of 8.1% with improving trajectory as IT consulting demand recovers.", "EPS grew 17.9% annualised from improved project execution and client retention.", "Recovery momentum as Swedish enterprise technology investment normalises."], 'JOKER'),
    618: ('Eco Animal Health Group PLC', 'UK veterinary pharmaceuticals. Recovery play.', 'Veterinary pharma recovery.', "Eco Animal Health is a UK veterinary pharmaceutical company producing antibiotics and health products for livestock globally. The company is recovering as antibiotic regulation and livestock farming investment normalise across its key markets.", 'Veterinary pharma. Recovery play.', 'Animal health recovery.', "A UK veterinary pharmaceutical company with a 3.8% ROIC recovering in the livestock health market. Eco Animal Health produces antibiotic and health products for global livestock farming — improving financial metrics as the veterinary pharma market recovers.", ["Veterinary antibiotics and health products for global livestock farming.", "ROIC of 3.8% with improving trajectory as livestock pharma market recovers.", "Revenue growing 1.4% annualised as veterinary antibiotic demand normalises.", "Recovery play in a structurally growing global animal health market."], 'JOKER'),
    648: ('Sphere Entertainment Co', 'US immersive entertainment venue. High revenue growth.', 'Immersive entertainment pioneer.', "Sphere Entertainment operates the Las Vegas Sphere — the world's largest and most technologically advanced entertainment venue. The iconic spherical building delivers immersive audio-visual experiences at unprecedented scale, hosting concerts, residencies, and branded experiences.", 'Las Vegas Sphere. Immersive entertainment.', 'Entertainment technology pioneer.', "The operator of the Las Vegas Sphere — the world's most advanced entertainment venue. Sphere Entertainment is pioneering immersive large-format entertainment with exceptional audio-visual technology that cannot be replicated at home or in traditional venues.", ["Las Vegas Sphere — world's largest and most technologically advanced entertainment venue.", "Immersive audio-visual experiences at unprecedented scale for concerts and events.", "Revenue grew 18.8% annualised as Sphere residencies and branded experiences expanded.", "Pioneer in immersive entertainment creating a new category of live experience."], 'JOKER'),
    687: ('Hilton Food Group PLC', 'UK food packing and processing. Contrarian recovery.', 'Food packing contrarian play.', "Hilton Food Group is a UK food packing and processing company serving major supermarkets across Europe and Australia. The company has been beaten down on margin compression — fundamentals are improving as input cost inflation normalises and contract pricing adjusts.", 'Food packing. Contrarian recovery.', 'Food processing recovery.', "A UK food packing and processing company in a contrarian recovery phase. Hilton Food Group packs meat, fish, and plant-based products for major European supermarkets — quality food infrastructure business trading below fair value as margins recover.", ["Food packing and processing for major supermarkets across Europe and Australia.", "Recovery play as input cost inflation normalises and contract pricing adjustments take effect.", "Revenue growing as food volumes and new protein category expansion continue.", "Contrarian entry as temporary margin compression creates discount to intrinsic value."], 'TWO'),
    689: ('Humble Group', 'Swedish health food company. Contrarian recovery.', 'Health food contrarian play.', "Humble Group is a Swedish health food company producing and distributing organic, natural, and functional food products across Scandinavia and Europe. The company has been beaten down — fundamentals are improving as the health food market recovers.", 'Swedish health food. Contrarian recovery.', 'Health food recovery.', "A Swedish health food company with a 0.2% ROIC in a contrarian recovery phase. Humble Group produces organic and natural food products for the growing Scandinavian health food market — trading below fair value as the business improves.", ["Organic, natural and functional food products across Scandinavia and Europe.", "Recovery play as health food demand and distribution normalise.", "EPS growing 15.9% annualised from a low base as health food margins recover.", "Contrarian entry as the market discounts temporary operational challenges."], 'TWO'),
    691: ('Kolibri Global Energy Inc', 'Canadian Permian Basin oil producer. Contrarian recovery.', 'Permian oil contrarian play.', "Kolibri Global Energy is a Canadian oil producer with assets in the STACK play of Oklahoma. The company has been beaten down on oil price concerns — quality oil assets trading below fair value with solid production metrics and improving financial health.", 'Oklahoma oil producer. Contrarian entry.', 'Oil producer contrarian play.', "A Canadian oil producer with a 5.8% ROIC in a contrarian recovery phase. Kolibri Global Energy operates Oklahoma STACK wells — quality oil production assets trading below fair value as the market discounts oil price uncertainty.", ["Oil production from the STACK play in Oklahoma with improving well economics.", "ROIC of 5.8% with improving trajectory as production and pricing recover.", "EPS grew 16.5% annualised as production volumes and well efficiency improved.", "Contrarian entry as oil price concerns create discount to intrinsic asset value."], 'TWO'),
    696: ('Orsted', 'Danish offshore wind giant. Contrarian recovery.', 'Offshore wind contrarian play.', "Orsted is a Danish company and the global leader in offshore wind energy development and operation. The company has been severely beaten down on project cost overruns and cancellations — but its long-term offshore wind franchise and pipeline remain intact.", 'Offshore wind leader. Contrarian recovery.', 'Offshore wind recovery play.', "The global offshore wind leader in a contrarian recovery phase after significant price dislocation. Orsted has the largest offshore wind development pipeline globally — trading at a deep discount to long-term intrinsic value as near-term project challenges overshadow structural franchise value.", ["Global leader in offshore wind development and operation across Europe and North America.", "Beaten down on project cost overruns creating contrarian entry below fair value.", "Long-term offshore wind pipeline intact despite near-term project cancellations.", "Structural energy transition tailwind supports multi-decade offshore wind growth."], 'TWO'),
    702: ('Surgical Science', 'Swedish surgical simulation technology. High ROIC.', 'Surgical training technology.', "Surgical Science is a Swedish company producing surgical simulators — high-fidelity virtual reality training systems for surgeons and medical students. The company products allow surgeons to practice complex procedures repeatedly before performing them on patients.", 'Surgical simulation. High ROIC growth.', 'Medical training compounder.', "A Swedish surgical simulation company with a 1.8% ROIC and EPS growth of 23.3% annualised. Surgical Science produces VR surgical training simulators — a growing market as hospitals invest in simulation-based training to improve surgical outcomes and reduce complications.", ["High-fidelity surgical simulators for surgeon training and medical education.", "EPS grew 23.3% annualised as hospital adoption of surgical simulation expanded.", "Revenue grew 12.2% annualised with consistent new simulator installations globally.", "Growing market as evidence-based surgical training drives simulation investment."], 'TWO'),
    703: ('Swedencare', 'Swedish pet health products. Contrarian recovery.', 'Pet health contrarian play.', "Swedencare is a Swedish pet health company producing supplements, dental care, and health products for dogs and cats. The company has been beaten down as post-pandemic pet product demand normalised — fundamentals improving as the business restructures.", 'Pet health products. Contrarian recovery.', 'Pet health recovery.', "A Swedish pet health company with a 0.6% ROIC in a contrarian recovery phase. Swedencare produces supplements and dental products for pets — recovering as post-pandemic demand normalisation completes and restructuring benefits flow through.", ["Pet supplements, dental care and health products for dogs and cats.", "Recovery play as post-pandemic pet product demand normalisation completes.", "EPS growing 15.9% annualised from a low base as restructuring benefits improve margins.", "Structural pet humanisation trend provides long-term demand for premium pet health."], 'TWO'),
    705: ('Tripadvisor Inc', 'US travel review platform. Contrarian recovery.', 'Travel platform contrarian play.', "Tripadvisor is the world's largest travel guidance platform with reviews, hotel bookings, and experience recommendations. The company has been beaten down as its transition from advertising to experiences revenue evolves — fundamentals improving as travel demand remains structurally strong.", 'Travel platform. Contrarian recovery.', 'Travel platform recovery.', "The world's largest travel review platform in a contrarian recovery phase. Tripadvisor massive review database and travel guidance platform serves hundreds of millions of global travellers — trading below fair value as business model transition creates near-term uncertainty.", ["World's largest travel review and guidance platform with hundreds of millions of users.", "Beaten down as advertising-to-experiences revenue transition creates near-term uncertainty.", "Structural travel demand recovery supports platform traffic and monetisation improvement.", "Contrarian entry as business model evolution discount overstates long-term franchise risk."], 'TWO'),
    706: ('Vimian Group', 'Swedish veterinary specialties. Contrarian recovery.', 'Veterinary specialties recovery.', "Vimian Group is a Swedish company developing and selling specialty veterinary pharmaceuticals and diagnostics. The company has been beaten down as post-acquisition integration and investment weighed on margins — fundamentals improving as the specialty vet portfolio matures.", 'Veterinary specialties. Contrarian recovery.', 'Vet pharma contrarian play.', "A Swedish veterinary specialties company with a 3.3% ROIC in a contrarian recovery phase. Vimian develops specialty veterinary pharmaceuticals and diagnostics — quality business trading below fair value as integration costs and investment weigh on near-term metrics.", ["Specialty veterinary pharmaceuticals and diagnostics for companion and production animals.", "Recovery play as post-acquisition integration and investment phase matures.", "Revenue growing 13.4% annualised as veterinary specialty portfolio expands.", "Contrarian entry as integration discount creates opportunity below intrinsic value."], 'TWO'),
    709: ('WM Technology Inc', 'US cannabis marketplace technology. Contrarian recovery.', 'Cannabis marketplace recovery.', "WM Technology operates Weedmaps — the largest online marketplace for cannabis dispensaries and consumers in the US. The company has been beaten down as cannabis market growth disappointed — but its dominant marketplace position remains intact as US cannabis legalisation expands.", 'Cannabis marketplace. Contrarian recovery.', 'Cannabis tech contrarian play.', "The operator of Weedmaps — the dominant US cannabis dispensary marketplace — in a contrarian recovery phase. WM Technology marketplace connects consumers with dispensaries across legal US states — trading below fair value as the cannabis market recovers from a growth slowdown.", ["Weedmaps — dominant online marketplace connecting cannabis consumers with dispensaries.", "Recovery play as US cannabis market growth and dispensary advertising spending normalises.", "EPS growing 13.3% annualised as marketplace monetisation and cost structure improve.", "Structural US cannabis legalisation expansion supports long-term marketplace growth."], 'TWO'),
}
with open(CARDS_PATH, "r", encoding="utf-8") as f:
    content = f.read()
updated = 0
for card_id, (company, tag, tagBold, tagFull, pick, pickBold, pickFull, bullets, card_type) in descriptions.items():
    pattern = re.compile(rf"(id: {card_id}, type: '{card_type}'.*?tag: ')[^']*('..*?tagBold: ')[^']*('..*?tagFull: \")[^\"]*(\",.*?pick: ')[^']*('..*?pickBold: ')[^']*('..*?pickFull: \")[^\"]*(\",)", re.DOTALL)
    replacement = rf"\g<1>{tag}\g<2>{tagBold}\g<3>{tagFull}\g<4>{pick}\g<5>{pickBold}\g<6>{pickFull}\g<7>"
    new_content = pattern.sub(replacement, content)
    if new_content != content:
        content = new_content
        updated += 1
        print(f"OK {card_id}: {company}")
    else:
        print(f"MISS {card_id}: {company}")
    bullets_str = ", ".join([f'"{b}"' for b in bullets])
    bp = re.compile(rf"(id: {card_id},.*?bullets: \[)[^\]]*\]", re.DOTALL)
    content = bp.sub(rf"\g<1>{bullets_str}]", content)
with open(CARDS_PATH, "w", encoding="utf-8") as f:
    f.write(content)
print(f"Updated: {updated}")
print(f"Remaining: {content.count('operates in')}")
