import re, shutil

src = '/Users/radekmajewski/Downloads/ValuJack/public/index.html'
shutil.copy(src, src + '.bak_before_new_cards')

new_cards = '''    {
        id: 1, type: 'JACK', isPro: false, fairValue: 150.98, yahooTicker: 'ESEA',
        stars: 5, sector: 'Industrials', sectorIcon: '🚢',
        irLink: 'https://www.euroseas.gr/investors/',
        company: 'Euroseas Ltd', ticker: 'ESEA',
        tag: 'Container shipping. Deep value.', tagBold: 'Trades at 44% of fair value.',
        tagFull: "Euroseas operates a fleet of container vessels serving inter-regional trade lanes. With a P/E below 4 and consistent cash generation, the market is pricing in a severe downturn that the order book does not support.",
        pick: 'Cheap containers. Strong cash.', pickBold: 'Compelling entry point.',
        pickFull: "A high-quality small-cap container shipper trading at a fraction of its intrinsic value — strong cash flow, low debt, and a healthy dividend. The fleet is modern and the earnings track record is consistent.",
        ind1l: 'FCF YIELD', ind1v: '28.1%', ind2l: 'P/E', ind2v: '3.4',
        metrics: [{ l: 'P/E', v: '3.4' }, { l: 'ROIC', v: '32.5%' }, { l: 'FCF Yield', v: '28.1%' }, { l: 'D/E', v: '0.5' }],
        scores: [{ l: 'Dividend', v: 4, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Moderate' }, { l: 'Momentum', v: 8, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '151%' }, { l: 'Profit', v: 7, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '32.5%' }, { l: 'Low Debt', v: 8, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Low' }, { l: 'Fair Price', v: 9, max: 10, color: '#D4884A', raw: 'JACK Signal', rawV: 'STRONGLY UNDERVALUED' }],
        bullets: ["Small fleet operator with modern, fuel-efficient container vessels.", "Trading at P/E 3.4 — one of the cheapest quality shippers in the market.", "Strong ROIC of 32.5% — capital returns far above cost of capital.", "Stock up 151% in the past year, yet still deeply below fair value."],
    },
    {
        id: 2, type: 'JACK', isPro: false, fairValue: 87.6, yahooTicker: 'ESP',
        stars: 5, sector: 'Industrials', sectorIcon: '🔧',
        irLink: 'https://www.espey.com/investors',
        company: 'Espey Manufacturing', ticker: 'ESP',
        tag: 'Defence electronics. Undervalued.', tagBold: 'Critical US military supplier.',
        tagFull: "Espey builds power electronics for US military applications — transformers, power supplies, and frequency converters for radar and communication systems. Niche, sticky, and virtually recession-proof.",
        pick: 'Defence niche. Consistent growth.', pickBold: 'Strong earnings momentum.',
        pickFull: "A small-cap US defence contractor with a niche monopoly in military-grade power electronics. Consistent earnings growth, minimal debt, and high switching costs from its military customers.",
        ind1l: 'FCF YIELD', ind1v: '28.5%', ind2l: 'ROIC', ind2v: '52.7%',
        metrics: [{ l: 'P/E', v: '15.5' }, { l: 'ROIC', v: '52.7%' }, { l: 'FCF Yield', v: '28.5%' }, { l: 'D/E', v: '0.6' }],
        scores: [{ l: 'Dividend', v: 3, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Low' }, { l: 'Momentum', v: 8, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '110%' }, { l: 'Profit', v: 9, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '52.7%' }, { l: 'Low Debt', v: 7, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Low' }, { l: 'Fair Price', v: 8, max: 10, color: '#D4884A', raw: 'JACK Signal', rawV: 'STRONGLY UNDERVALUED' }],
        bullets: ["US military-grade power electronics — transformers, converters, radar power supplies.", "ROIC of 52.7% — exceptional capital efficiency for an industrial manufacturer.", "EPS grew 116% over 5 years; consistent defence contract backlog provides visibility.", "Stock up 110% in one year but still trading at 64% of fair value."],
    },
    {
        id: 3, type: 'JACK', isPro: false, fairValue: 3.16, yahooTicker: 'N4Q1.DE',
        stars: 5, sector: 'Energy', sectorIcon: '🛢️',
        irLink: 'https://www.hemisphereenergyinc.com/investors',
        company: 'Hemisphere Energy', ticker: 'N4Q1',
        tag: 'Canadian oil. Exceptional FCF.', tagBold: 'FCF yield of 46% at current price.',
        tagFull: "Hemisphere Energy is a profitable Canadian heavy oil producer with low-cost operations in the Athabasca region. Trading at roughly half fair value with exceptional free cash flow generation.",
        pick: 'Heavy oil. Priced for disaster.', pickBold: 'FCF machine at current price.',
        pickFull: "A highly profitable small-cap Canadian heavy oil producer generating extraordinary free cash flow from low-cost polymer flood operations. The business is self-funding, carries modest debt, and has a consistent earnings track record.",
        ind1l: 'FCF YIELD', ind1v: '46.5%', ind2l: 'P/E', ind2v: '8.5',
        metrics: [{ l: 'P/E', v: '8.5' }, { l: 'ROIC', v: '30.7%' }, { l: 'FCF Yield', v: '46.5%' }, { l: 'D/E', v: '0.6' }],
        scores: [{ l: 'Dividend', v: 3, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Moderate' }, { l: 'Momentum', v: 7, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '48%' }, { l: 'Profit', v: 7, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '30.7%' }, { l: 'Low Debt', v: 7, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Low' }, { l: 'Fair Price', v: 9, max: 10, color: '#D4884A', raw: 'JACK Signal', rawV: 'STRONGLY UNDERVALUED' }],
        bullets: ["Canadian heavy oil producer using cost-effective polymer flood technology.", "FCF yield of 46.5% — extraordinary cash generation relative to market cap.", "EPS grew 134% over 5 years; operations are low-cost and self-funding.", "Trading at 53% of fair value with minimal debt — significant margin of safety."],
    },
    {
        id: 4, type: 'KING', isPro: false, fairValue: 23.02, yahooTicker: 'BSM',
        stars: 4, sector: 'Energy', sectorIcon: '⚡',
        irLink: 'https://ir.blackstoneminerals.com/',
        company: 'Black Stone Minerals', ticker: 'BSM',
        tag: 'Royalty income. No drilling risk.', tagBold: 'Dividend yield of 7.8%.',
        tagFull: "Black Stone Minerals is one of the largest mineral rights owners in the US — collecting royalties from oil and gas production without drilling risk, capital expenditure, or operational complexity.",
        pick: 'Mineral royalties. Pure income.', pickBold: 'No drilling risk. Just cash.',
        pickFull: "One of the largest mineral rights holders in the United States — earning royalties on oil and gas production across 20 states. No drilling costs, no capex, no operational risk. Pure income compounding over time.",
        ind1l: 'DIV YIELD', ind1v: '7.8%', ind2l: 'P/E', ind2v: '12.1',
        metrics: [{ l: 'P/E', v: '12.1' }, { l: 'ROIC', v: '27.2%' }, { l: 'FCF Yield', v: '45.2%' }, { l: 'Div. Yield', v: '7.8%' }],
        scores: [{ l: 'Dividend', v: 8, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: '7.8%' }, { l: 'Momentum', v: 5, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '2.7%' }, { l: 'Profit', v: 6, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '27.2%' }, { l: 'Low Debt', v: 9, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Very Low' }, { l: 'Fair Price', v: 7, max: 10, color: '#D4884A', raw: 'KING Signal', rawV: 'UNDERVALUED' }],
        bullets: ["Mineral rights across 20 US states — royalties with zero drilling risk.", "7.8% dividend yield backed by consistent distribution history.", "FCF yield of 45.2% — substantial cash generation supporting the distribution.", "Trading at 33% below fair value with very low debt."],
    },
    {
        id: 5, type: 'KING', isPro: false, fairValue: 1173.61, yahooTicker: 'EVO.ST',
        stars: 4, sector: 'Consumer Durables', sectorIcon: '🎮',
        irLink: 'https://www.evolution.com/investors/',
        company: 'Evolution AB', ticker: 'EVO',
        tag: 'Live casino monopoly. Deep value.', tagBold: 'Dominant market position.',
        tagFull: "Evolution is the undisputed world leader in live casino technology — powering the live dealer games for virtually every major online casino globally. Asset-light, extraordinarily cash generative, and trading near multi-year lows.",
        pick: 'Casino tech leader. Cheap.', pickBold: 'Quality at a discount.',
        pickFull: "The dominant global supplier of live casino technology, serving virtually every major online gambling operator in the world. Asset-light business model with extraordinary free cash flow, high switching costs, and a decade of consistent growth.",
        ind1l: 'FCF YIELD', ind1v: '9.6%', ind2l: 'ROIC', ind2v: '28.5%',
        metrics: [{ l: 'P/E', v: '10.2' }, { l: 'ROIC', v: '28.5%' }, { l: 'FCF Yield', v: '9.6%' }, { l: 'D/E', v: '0.4' }],
        scores: [{ l: 'Dividend', v: 5, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Suspended 2026' }, { l: 'Momentum', v: 3, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '-26%' }, { l: 'Profit', v: 8, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '28.5%' }, { l: 'Low Debt', v: 8, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Low' }, { l: 'Fair Price', v: 8, max: 10, color: '#D4884A', raw: 'KING Signal', rawV: 'STRONGLY UNDERVALUED' }],
        bullets: ["Powers live dealer casino games for virtually every major online gambling operator globally.", "Asset-light model — near-zero marginal cost per additional casino client.", "FCF yield of 9.6% despite no dividend this year — all cash retained on balance sheet.", "Trading at 50% of fair value; P/E of 10 for a dominant market leader is historically cheap."],
    },
    {
        id: 6, type: 'KING', isPro: false, fairValue: 43.92, yahooTicker: 'VDE.BR',
        stars: 4, sector: 'Consumer Durables', sectorIcon: '👗',
        irLink: 'https://www.vandeveldegroup.com/en/investors',
        company: 'Van de Velde', ticker: 'VAN',
        tag: 'Belgian luxury lingerie. 8% yield.', tagBold: 'Consistent 20-year dividend payer.',
        tagFull: "Van de Velde is a premium Belgian lingerie manufacturer with globally recognised brands. Conservatively managed, debt-light, and committed to a reliable dividend for over two decades.",
        pick: 'Premium lingerie. Reliable income.', pickBold: 'Steady dividend. Low risk.',
        pickFull: "A premium Belgian lingerie brand with niche market leadership and a 20-year dividend track record. Low debt, solid ROIC, and a loyal retail customer base make this a classic defensive income compounder.",
        ind1l: 'DIV YIELD', ind1v: '8.0%', ind2l: 'ROIC', ind2v: '26.7%',
        metrics: [{ l: 'P/E', v: '11.9' }, { l: 'ROIC', v: '26.7%' }, { l: 'FCF Yield', v: '19.1%' }, { l: 'Div. Yield', v: '8.0%' }],
        scores: [{ l: 'Dividend', v: 8, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: '8.0%' }, { l: 'Momentum', v: 5, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '-1.1%' }, { l: 'Profit', v: 7, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '26.7%' }, { l: 'Low Debt', v: 9, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Very Low' }, { l: 'Fair Price', v: 7, max: 10, color: '#D4884A', raw: 'KING Signal', rawV: 'UNDERVALUED' }],
        bullets: ["Premium Belgian lingerie brand with over 20 years of consistent dividend payments.", "8.0% dividend yield with low payout ratio — well covered by earnings.", "ROIC of 26.7% — strong returns on conservative capital base.", "Trading at 31% below fair value with essentially zero net debt."],
    },
    {
        id: 7, type: 'KING', isPro: false, fairValue: 30.31, yahooTicker: 'MPE.L',
        stars: 4, sector: 'Food and Beverage', sectorIcon: '🌴',
        irLink: 'https://www.mpevans.co.uk/investors/',
        company: 'M P Evans Group', ticker: 'MPE',
        tag: 'Palm oil estates. Deeply cheap.', tagBold: '51% below fair value.',
        tagFull: "M P Evans is a UK-listed palm oil plantation group operating in Indonesia. Vertically integrated, sustainable certified, and generating strong earnings from its own planted estates.",
        pick: 'Palm oil producer. Undervalued.', pickBold: 'Strong earnings visibility.',
        pickFull: "A UK-listed palm oil plantation operator in Indonesia with certified sustainable production. Vertically integrated from plantation to mill, with strong earnings visibility from its own planted estates and consistent EPS growth.",
        ind1l: 'P/E', ind1v: '9.9', ind2l: 'EPS GROWTH', ind2v: '40.2%',
        metrics: [{ l: 'P/E', v: '9.9' }, { l: 'ROIC', v: '16.5%' }, { l: 'EPS Growth 5y', v: '40.2%' }, { l: 'D/E', v: '0.2' }],
        scores: [{ l: 'Dividend', v: 5, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Moderate' }, { l: 'Momentum', v: 5, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: 'Flat' }, { l: 'Profit', v: 6, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '16.5%' }, { l: 'Low Debt', v: 9, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Very Low' }, { l: 'Fair Price', v: 9, max: 10, color: '#D4884A', raw: 'KING Signal', rawV: 'STRONGLY UNDERVALUED' }],
        bullets: ["Indonesian palm oil plantation operator — vertically integrated from estates to mills.", "RSPO-certified sustainable production; increasingly important for institutional buyers.", "EPS grew 40% over 5 years with strong earnings visibility from planted estates.", "Trading at P/E 9.9 — significant discount for a consistently profitable agricultural producer."],
    },
    {
        id: 8, type: 'JACK', isPro: false, fairValue: 87.84, yahooTicker: 'MPCC.OL',
        stars: 4, sector: 'Industrials', sectorIcon: '🚢',
        irLink: 'https://www.mpccontainerships.com/investor-relations/',
        company: 'MPC Container Ships', ticker: 'MPCC',
        tag: 'Container shipping. 74% below FV.', tagBold: 'P/E of 4.3 with strong FCF.',
        tagFull: "MPC Container Ships operates a fleet of feeder and intermediate container vessels. Trading at a massive discount to fair value with extraordinary cash flow generation and improving charter market fundamentals.",
        pick: 'Feeder containers. Deep value.', pickBold: 'Massive discount to NAV.',
        pickFull: "A Nordic-listed container shipping company focused on the feeder segment — the last mile of global container logistics. Extraordinary free cash flow generation, trading at a fraction of net asset value, with improving charter market conditions.",
        ind1l: 'FCF YIELD', ind1v: '42.2%', ind2l: 'P/E', ind2v: '4.3',
        metrics: [{ l: 'P/E', v: '4.3' }, { l: 'ROIC', v: '37.2%' }, { l: 'FCF Yield', v: '42.2%' }, { l: 'D/E', v: '0.6' }],
        scores: [{ l: 'Dividend', v: 4, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Variable' }, { l: 'Momentum', v: 7, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '36%' }, { l: 'Profit', v: 8, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '37.2%' }, { l: 'Low Debt', v: 7, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Moderate' }, { l: 'Fair Price', v: 9, max: 10, color: '#D4884A', raw: 'JACK Signal', rawV: 'STRONGLY UNDERVALUED' }],
        bullets: ["Nordic container shipping company operating feeder vessels in inter-regional trade lanes.", "FCF yield of 42.2% — extraordinary cash generation relative to current market cap.", "ROIC of 37.2% demonstrates strong capital efficiency across the fleet.", "Stock up 36% in the past year yet still trading at 26% of fair value."],
    },
    {
        id: 9, type: 'KING', isPro: false, fairValue: 41.12, yahooTicker: 'ARLP',
        stars: 4, sector: 'Energy', sectorIcon: '⛏️',
        irLink: 'https://ir.arlp.com/',
        company: 'Alliance Resource Partners', ticker: 'ARLP',
        tag: 'Coal royalties. 9.5% yield.', tagBold: 'Consistent distribution history.',
        tagFull: "Alliance Resource Partners is a US coal producer and mineral royalty owner with one of the highest dividend yields in the market. Strategically expanding into oil and gas mineral rights for long-term diversification.",
        pick: 'Coal MLP. High income.', pickBold: '9.5% yield, low debt.',
        pickFull: "A US coal and mineral royalty partnership with exceptional distribution history and one of the highest yields in the market. Strategically diversifying into oil and gas mineral rights while maintaining very conservative debt levels.",
        ind1l: 'DIV YIELD', ind1v: '9.5%', ind2l: 'P/E', ind2v: '11.4',
        metrics: [{ l: 'P/E', v: '11.4' }, { l: 'ROIC', v: '17.7%' }, { l: 'FCF Yield', v: '17.3%' }, { l: 'Div. Yield', v: '9.5%' }],
        scores: [{ l: 'Dividend', v: 9, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: '9.5%' }, { l: 'Momentum', v: 5, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '8.9%' }, { l: 'Profit', v: 6, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '17.7%' }, { l: 'Low Debt', v: 8, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Low' }, { l: 'Fair Price', v: 7, max: 10, color: '#D4884A', raw: 'KING Signal', rawV: 'UNDERVALUED' }],
        bullets: ["US coal producer and mineral royalty owner with 9.5% distribution yield.", "Strategically diversifying into oil and gas mineral rights for long-term resilience.", "Conservative debt levels — financial discipline is a defining characteristic of management.", "Trading at 33% below fair value with consistent earnings and distribution history."],
    },
    {
        id: 10, type: 'KING', isPro: false, fairValue: 32.81, yahooTicker: 'CIX',
        stars: 3, sector: 'Industrials', sectorIcon: '🔒',
        irLink: 'https://www.compx.com/investor-relations/',
        company: 'CompX International', ticker: 'CIX',
        tag: 'Security products. Reliable income.', tagBold: '5.2% yield. Zero debt.',
        tagFull: "CompX International manufactures security products and marine components for the US market. Conservatively managed with zero net debt, consistent dividends, and a loyal industrial customer base.",
        pick: 'Security products. Zero debt.', pickBold: 'Reliable small-cap compounder.',
        pickFull: "A US manufacturer of security products and marine propulsion components. Exceptionally conservatively managed — essentially no debt, consistent dividend, and steady earnings from a loyal industrial customer base.",
        ind1l: 'DIV YIELD', ind1v: '5.2%', ind2l: 'P/E', ind2v: '14.7',
        metrics: [{ l: 'P/E', v: '14.7' }, { l: 'ROIC', v: '20.7%' }, { l: 'FCF Yield', v: '12.1%' }, { l: 'Div. Yield', v: '5.2%' }],
        scores: [{ l: 'Dividend', v: 6, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: '5.2%' }, { l: 'Momentum', v: 5, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '4.0%' }, { l: 'Profit', v: 6, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '20.7%' }, { l: 'Low Debt', v: 10, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Zero' }, { l: 'Fair Price', v: 7, max: 10, color: '#D4884A', raw: 'KING Signal', rawV: 'UNDERVALUED' }],
        bullets: ["US manufacturer of security products and marine components — niche industrial market.", "5.2% dividend yield backed by zero net debt and consistent earnings.", "ROIC of 20.7% on a conservative capital base with virtually no leverage.", "Trading at 29% below fair value — quiet compounder often overlooked by the market."],
    },
    {
        id: 11, type: 'KING', isPro: false, fairValue: 26.39, yahooTicker: 'AEP.L',
        stars: 4, sector: 'Food and Beverage', sectorIcon: '🌿',
        irLink: 'https://www.aepplantations.co.uk/investors',
        company: 'AEP Plantations', ticker: 'AEP',
        tag: 'UK palm oil. Up 125% in one year.', tagBold: 'Trading at 39% of fair value.',
        tagFull: "AEP Plantations is a UK-listed palm oil group with operations in Southeast Asia. Exceptional 1-year performance reflects recovering plantation yields and commodity prices, yet the stock remains significantly below intrinsic value.",
        pick: 'Palm oil. Momentum building.', pickBold: 'Strong recent earnings growth.',
        pickFull: "A UK-listed palm oil plantation company with sustainable operations in Southeast Asia. Strong EPS growth of 23% annualised over five years, 1-year price appreciation of 125%, and still trading at a significant discount to fair value.",
        ind1l: 'P/E', ind1v: '9.7', ind2l: 'EPS GROWTH', ind2v: '22.7%',
        metrics: [{ l: 'P/E', v: '9.7' }, { l: 'ROIC', v: '22.8%' }, { l: 'EPS Growth 5y', v: '22.7%' }, { l: 'D/E', v: '0.1' }],
        scores: [{ l: 'Dividend', v: 4, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Moderate' }, { l: 'Momentum', v: 9, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '125%' }, { l: 'Profit', v: 6, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '22.8%' }, { l: 'Low Debt', v: 10, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Minimal' }, { l: 'Fair Price', v: 8, max: 10, color: '#D4884A', raw: 'KING Signal', rawV: 'STRONGLY UNDERVALUED' }],
        bullets: ["UK-listed palm oil plantation group operating in Southeast Asia — sustainable certified.", "Stock up 125% in the past year, reflecting recovering yields and commodity tailwinds.", "ROIC of 22.8% with minimal debt — capital-efficient plantation operations.", "Still trading at 39% of fair value despite the strong run — significant upside remains."],
    },
    {
        id: 12, type: 'KING', isPro: false, fairValue: 282.14, yahooTicker: 'BETS-B.ST',
        stars: 4, sector: 'Consumer Durables', sectorIcon: '🎰',
        irLink: 'https://www.betsson.com/en/investor-relations',
        company: 'Betsson AB', ticker: 'BETS B',
        tag: 'Online gaming. 65% below FV.', tagBold: '7.3% dividend yield.',
        tagFull: "Betsson is one of Europe\'s largest online gaming companies, operating in regulated markets across Europe and Latin America. A consistent dividend payer trading at a deep discount after regulatory concerns hammered the sector.",
        pick: 'Gaming operator. Undervalued.', pickBold: 'Regulated markets. Income.',
        pickFull: "One of Europe\'s largest online gaming operators, with a diversified portfolio across regulated European and Latin American markets. A consistent earnings and dividend track record, yet trading at a deep discount driven by sector-wide regulatory concerns.",
        ind1l: 'DIV YIELD', ind1v: '7.3%', ind2l: 'P/E', ind2v: '7.0',
        metrics: [{ l: 'P/E', v: '7.0' }, { l: 'ROIC', v: '22.9%' }, { l: 'FCF Yield', v: '13.7%' }, { l: 'Div. Yield', v: '7.3%' }],
        scores: [{ l: 'Dividend', v: 7, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: '7.3%' }, { l: 'Momentum', v: 2, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '-38%' }, { l: 'Profit', v: 7, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '22.9%' }, { l: 'Low Debt', v: 8, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Low' }, { l: 'Fair Price', v: 9, max: 10, color: '#D4884A', raw: 'KING Signal', rawV: 'STRONGLY UNDERVALUED' }],
        bullets: ["Major European online gaming operator in regulated markets across Europe and Latin America.", "7.3% dividend yield — consistent payout despite sector headwinds.", "P/E of 7.0 for a company with 22.9% ROIC reflects extreme market pessimism on gaming sector.", "Stock down 38% in one year — trading at 35% of fair value after regulatory concerns."],
    },
    {
        id: 13, type: 'JACK', isPro: false, fairValue: 388.82, yahooTicker: 'DAC',
        stars: 4, sector: 'Industrials', sectorIcon: '🚢',
        irLink: 'https://www.danaos.com/investors/',
        company: 'Danaos Corp', ticker: 'DAC',
        tag: 'Container ships. 72% below FV.', tagBold: 'P/E of 4.1. No debt concerns.',
        tagFull: "Danaos operates one of the largest independent container shipping fleets, with long-term charter contracts providing earnings visibility. Trading at an extraordinary discount to net asset value.",
        pick: 'Large containers. Very cheap.', pickBold: 'Long charters. Low risk.',
        pickFull: "One of the largest independent container ship owners, with a fleet of large vessels on long-term charter contracts to the world\'s top shipping lines. Exceptional earnings visibility from multi-year fixed-rate contracts and trading at a fraction of net asset value.",
        ind1l: 'FCF YIELD', ind1v: '33.4%', ind2l: 'P/E', ind2v: '4.1',
        metrics: [{ l: 'P/E', v: '4.1' }, { l: 'ROIC', v: '20.7%' }, { l: 'FCF Yield', v: '33.4%' }, { l: 'D/E', v: '0.3' }],
        scores: [{ l: 'Dividend', v: 3, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Low' }, { l: 'Momentum', v: 7, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '39%' }, { l: 'Profit', v: 7, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '20.7%' }, { l: 'Low Debt', v: 8, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Low' }, { l: 'Fair Price', v: 9, max: 10, color: '#D4884A', raw: 'JACK Signal', rawV: 'STRONGLY UNDERVALUED' }],
        bullets: ["Major independent container ship owner with vessels chartered to top global shipping lines.", "Long-term fixed-rate charters provide exceptional earnings visibility — low market risk.", "FCF yield of 33.4% at current price — extraordinary cash generation.", "Trading at 28% of fair value — P/E of 4.1 for a consistently profitable fleet operator."],
    },
    {
        id: 14, type: 'JACK', isPro: false, fairValue: 284.74, yahooTicker: '9TG.DE',
        stars: 4, sector: 'Energy', sectorIcon: '⚡',
        irLink: 'https://www.gtt.fr/en/investors',
        company: 'Gaztransport et Technigaz', ticker: '9TG',
        tag: 'LNG tech monopoly. 30% below FV.', tagBold: 'ROIC of 205%. Zero competitors.',
        tagFull: "GTT holds the patents for the membrane containment systems used in virtually every LNG carrier in the world. A genuine technological monopoly with extraordinary returns and LNG demand growth driving the order book.",
        pick: 'LNG patents. Monopoly returns.', pickBold: 'Every new LNG ship pays GTT.',
        pickFull: "The global monopoly on LNG carrier containment technology — nearly every LNG ship built in the world uses GTT\'s membrane system under licence. Extraordinary ROIC, no real competitors, and a decade of rising LNG demand driving a strong order book.",
        ind1l: 'ROIC', ind1v: '205.2%', ind2l: 'FCF YIELD', ind2v: '52.7%',
        metrics: [{ l: 'P/E', v: '17.8' }, { l: 'ROIC', v: '205.2%' }, { l: 'FCF Yield', v: '52.7%' }, { l: 'D/E', v: '0.8' }],
        scores: [{ l: 'Dividend', v: 4, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Moderate' }, { l: 'Momentum', v: 7, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '40%' }, { l: 'Profit', v: 10, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '205%' }, { l: 'Low Debt', v: 6, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Moderate' }, { l: 'Fair Price', v: 7, max: 10, color: '#D4884A', raw: 'JACK Signal', rawV: 'UNDERVALUED' }],
        bullets: ["Holds patents on membrane LNG containment technology used in virtually every LNG carrier built.", "ROIC of 205% — one of the highest returns on capital of any public company in the world.", "FCF yield of 52.7% — extraordinary cash generation from a pure intellectual property model.", "LNG demand growth driving a strong order book — new licences compound the royalty stream."],
    },
    {
        id: 15, type: 'JACK', isPro: false, fairValue: 32.47, yahooTicker: 'SD',
        stars: 4, sector: 'Energy', sectorIcon: '🛢️',
        irLink: 'https://www.sandridgeenergy.com/investors',
        company: 'SandRidge Energy', ticker: 'SD',
        tag: 'US oil & gas. 49% below FV.', tagBold: 'ROIC of 43%. Very low debt.',
        tagFull: "SandRidge Energy is a lean US oil and gas company that emerged from bankruptcy restructured and financially disciplined. Trading at half its fair value with exceptional returns on capital and a conservative balance sheet.",
        pick: 'Lean US oil. Deep value.', pickBold: 'Rebuilt. Highly profitable.',
        pickFull: "A restructured US oil and gas company that emerged from a period of financial difficulty as a leaner, more disciplined operator. High ROIC of 43%, minimal debt, and trading at a significant discount to fair value.",
        ind1l: 'ROIC', ind1v: '43.1%', ind2l: 'P/E', ind2v: '8.6',
        metrics: [{ l: 'P/E', v: '8.6' }, { l: 'ROIC', v: '43.1%' }, { l: 'D/E', v: '0.3' }, { l: '1y Perf', v: '44.3%' }],
        scores: [{ l: 'Dividend', v: 2, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'None' }, { l: 'Momentum', v: 8, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '44.3%' }, { l: 'Profit', v: 8, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '43.1%' }, { l: 'Low Debt', v: 9, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Very Low' }, { l: 'Fair Price', v: 8, max: 10, color: '#D4884A', raw: 'JACK Signal', rawV: 'STRONGLY UNDERVALUED' }],
        bullets: ["Restructured US oil and gas company now operating with financial discipline and low costs.", "ROIC of 43.1% — exceptional capital efficiency for an energy producer.", "Stock up 44% in the past year yet still trading at 51% of fair value.", "Very low debt gives financial flexibility through commodity price cycles."],
    },
    {
        id: 16, type: 'KING', isPro: false, fairValue: 105.36, yahooTicker: 'STNG',
        stars: 4, sector: 'Energy', sectorIcon: '🛢️',
        irLink: 'https://www.scorpiotankers.com/investors/',
        company: 'Scorpio Tankers', ticker: 'STNG',
        tag: 'Product tankers. 35% below FV.', tagBold: 'FCF yield of 44.4%.',
        tagFull: "Scorpio Tankers is the world\'s largest owner of product tankers — transporting refined petroleum products globally. The fleet is modern, cash generative, and trading at a meaningful discount to net asset value.",
        pick: 'Product tankers. High FCF.', pickBold: 'Fleet generating strong cash.',
        pickFull: "The world\'s largest owner of modern product tankers, transporting refined petroleum products across global trade routes. Extraordinary free cash flow, active balance sheet management, and a modern, fuel-efficient fleet trading below intrinsic value.",
        ind1l: 'FCF YIELD', ind1v: '44.4%', ind2l: 'P/E', ind2v: '9.2',
        metrics: [{ l: 'P/E', v: '9.2' }, { l: 'ROIC', v: '12.0%' }, { l: 'FCF Yield', v: '44.4%' }, { l: 'D/E', v: '0.2' }],
        scores: [{ l: 'Dividend', v: 5, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Variable' }, { l: 'Momentum', v: 8, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '73%' }, { l: 'Profit', v: 5, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '12.0%' }, { l: 'Low Debt', v: 9, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Very Low' }, { l: 'Fair Price', v: 7, max: 10, color: '#D4884A', raw: 'KING Signal', rawV: 'UNDERVALUED' }],
        bullets: ["World\'s largest owner of product tankers — transporting refined petroleum products globally.", "Modern, fuel-efficient fleet with low operating costs relative to peers.", "FCF yield of 44.4% — significant cash generation being returned to shareholders.", "Stock up 73% in one year yet still trading at 35% below fair value."],
    },
    {
        id: 17, type: 'JACK', isPro: false, fairValue: 30.61, yahooTicker: 'SA2D.DE',
        stars: 4, sector: 'Energy', sectorIcon: '🛢️',
        irLink: 'https://www.sandridgeenergy.com/investors',
        company: 'SandRidge Energy', ticker: 'SA2D',
        tag: 'US oil & gas. European listing.', tagBold: 'Same deep value as USD ticker.',
        tagFull: "SandRidge Energy German-listed shares. A restructured US oil and gas company trading at approximately half its intrinsic value with high capital returns and minimal debt.",
        pick: 'Lean US oil. Deep value.', pickBold: 'Rebuilt. Highly profitable.',
        pickFull: "The German-listed version of SandRidge Energy — a restructured US oil and gas company with ROIC of 43%, minimal debt, and trading significantly below fair value. The European listing often creates additional pricing inefficiency.",
        ind1l: 'ROIC', ind1v: '43.1%', ind2l: 'P/E', ind2v: '9.1',
        metrics: [{ l: 'P/E', v: '9.1' }, { l: 'ROIC', v: '43.1%' }, { l: 'D/E', v: '0.3' }, { l: '1y Perf', v: '44.2%' }],
        scores: [{ l: 'Dividend', v: 2, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'None' }, { l: 'Momentum', v: 8, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '44.2%' }, { l: 'Profit', v: 8, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '43.1%' }, { l: 'Low Debt', v: 9, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Very Low' }, { l: 'Fair Price', v: 8, max: 10, color: '#D4884A', raw: 'JACK Signal', rawV: 'STRONGLY UNDERVALUED' }],
        bullets: ["German-listed shares of SandRidge Energy — same business, often with additional pricing inefficiency.", "Restructured US oil and gas operator with ROIC of 43.1% and minimal leverage.", "EPS grew 17.6% annualised over five years; consistent operational improvement.", "Trading at 49% of fair value — exceptional margin of safety at current price."],
    },
    {
        id: 18, type: 'JACK', isPro: false, fairValue: 97.57, yahooTicker: 'MPTI',
        stars: 3, sector: 'Technology', sectorIcon: '📡',
        irLink: 'https://www.mtronindustries.com/investors',
        company: 'M-Tron Industries', ticker: 'MPTI',
        tag: 'Frequency control devices. Defence.', tagBold: 'ROIC of 25%. Growing backlog.',
        tagFull: "M-Tron Industries manufactures frequency control products for military and aerospace applications. A small-cap niche manufacturer with growing defence demand and consistent earnings.",
        pick: 'Military frequency tech. Growing.', pickBold: 'Defence backlog expanding.',
        pickFull: "A US manufacturer of frequency control products for military, aerospace, and industrial applications. Consistent earnings growth, strong ROIC, and an expanding defence market providing backlog visibility.",
        ind1l: 'FCF YIELD', ind1v: '13.5%', ind2l: 'ROIC', ind2v: '25.0%',
        metrics: [{ l: 'P/E', v: '26.5' }, { l: 'ROIC', v: '25.0%' }, { l: 'FCF Yield', v: '13.5%' }, { l: 'D/E', v: '0.1' }],
        scores: [{ l: 'Dividend', v: 2, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'None' }, { l: 'Momentum', v: 8, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '76%' }, { l: 'Profit', v: 7, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '25.0%' }, { l: 'Low Debt', v: 10, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Minimal' }, { l: 'Fair Price', v: 7, max: 10, color: '#D4884A', raw: 'JACK Signal', rawV: 'UNDERVALUED' }],
        bullets: ["Manufactures precision frequency control products for US military and aerospace — niche monopoly.", "ROIC of 25% with minimal debt — disciplined capital allocation in a growing defence market.", "EPS grew 42.6% annualised over five years, driven by rising defence electronics demand.", "Stock up 76% in one year, still trading at 31% below fair value."],
    },
    {
        id: 19, type: 'JOKER', isPro: true, fairValue: 190.0, yahooTicker: 'NVDA',
        stars: 4, sector: 'Technology', sectorIcon: '💻',
        irLink: 'https://investor.nvidia.com/',
        company: 'NVIDIA Corp', ticker: 'NVDA',
        tag: 'AI infrastructure. Market leader.', tagBold: 'Blackwell demand off the charts.',
        tagFull: "NVIDIA is the dominant supplier of AI training and inference chips — Blackwell GPUs are sold out globally and the Rubin platform extends this leadership into the next cycle. Revenue up 73% year over year.",
        pick: 'AI chips. Dominant platform.', pickBold: 'Compounding at scale.',
        pickFull: "The world\'s dominant AI infrastructure company — supplying the GPUs that power virtually all major AI training and inference workloads globally. Blackwell demand is exceeding supply, cloud hyperscalers are locked in, and the Rubin platform secures leadership into the next generation.",
        ind1l: 'PEG', ind1v: '0.18', ind2l: 'ROIC', ind2v: '85.4%',
        metrics: [{ l: 'P/E', v: '35.9' }, { l: 'ROIC', v: '85.4%' }, { l: 'EPS Growth 5y', v: '94.9%' }, { l: 'Signal', v: 'FAIRLY VALUED' }],
        scores: [{ l: 'Dividend', v: 1, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Minimal' }, { l: 'Momentum', v: 9, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '51%' }, { l: 'Profit', v: 10, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '85.4%' }, { l: 'Low Debt', v: 8, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Low' }, { l: 'Fair Price', v: 6, max: 10, color: '#D4884A', raw: 'JOKER Signal', rawV: 'FAIRLY VALUED' }],
        bullets: ["Dominant AI chip supplier — Blackwell GPUs sold out globally with demand accelerating.", "ROIC of 85.4% — extraordinary capital efficiency at massive scale.", "Revenue up 73% year over year; EPS grew 95% annualised over five years.", "Next earnings May 20 — well clear of reporting window."],
    },
    {
        id: 20, type: 'JOKER', isPro: true, fairValue: 123.15, yahooTicker: 'TDW',
        stars: 4, sector: 'Energy', sectorIcon: '🚢',
        irLink: 'https://www.tdw.com/investor-relations/',
        company: 'Tidewater Inc', ticker: 'TDW',
        tag: 'Offshore vessels. 39% below FV.', tagBold: 'Benefiting from offshore capex boom.',
        tagFull: "Tidewater operates the world\'s largest fleet of offshore support vessels for the oil and gas industry. Offshore capex is accelerating globally as energy security drives new field development.",
        pick: 'Offshore vessels. Capex boom.', pickBold: 'Structural tailwind from energy.',
        pickFull: "The world\'s largest offshore support vessel company, providing marine services to oil and gas operators globally. Strong tailwind from rising offshore energy investment as energy security drives new field development outside the Middle East.",
        ind1l: 'FCF YIELD', ind1v: '26.1%', ind2l: 'P/E', ind2v: '11.3',
        metrics: [{ l: 'P/E', v: '11.3' }, { l: 'ROIC', v: '4.6%' }, { l: 'FCF Yield', v: '26.1%' }, { l: 'D/E', v: '0.8' }],
        scores: [{ l: 'Dividend', v: 1, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'None' }, { l: 'Momentum', v: 8, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '82%' }, { l: 'Profit', v: 4, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '4.6%' }, { l: 'Low Debt', v: 6, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Moderate' }, { l: 'Fair Price', v: 7, max: 10, color: '#D4884A', raw: 'JOKER Signal', rawV: 'UNDERVALUED' }],
        bullets: ["World\'s largest offshore support vessel fleet serving oil and gas operators globally.", "Structural tailwind: rising energy security spending driving offshore capex globally.", "Stock up 82% in one year; EPS grew 28% annualised over five years.", "FCF yield of 26.1% — significant cash generation from a utilisation-driven model."],
    },
    {
        id: 21, type: 'JOKER', isPro: true, fairValue: 122.33, yahooTicker: 'ZM',
        stars: 3, sector: 'Technology', sectorIcon: '💻',
        irLink: 'https://investors.zoom.us/',
        company: 'Zoom Video Communications', ticker: 'ZM',
        tag: 'Video collaboration platform.', tagBold: 'ROIC of 96%. Undervalued.',
        tagFull: "Zoom evolved from a pandemic-era video call tool into a broader AI-powered collaboration platform. Despite the narrative turning negative, the underlying business generates extraordinary returns on capital.",
        pick: 'Video platform. AI pivot.', pickBold: 'Exceptional cash generation.',
        pickFull: "Zoom has transitioned from a pandemic-era darling to a profitable, AI-augmented enterprise collaboration platform. Despite market indifference, the underlying business generates extraordinary ROIC and free cash flow at a modest valuation.",
        ind1l: 'FCF YIELD', ind1v: '8.2%', ind2l: 'ROIC', ind2v: '95.9%',
        metrics: [{ l: 'ROIC', v: '95.9%' }, { l: 'FCF Yield', v: '8.2%' }, { l: 'EPS Growth 5y', v: '21.7%' }, { l: 'Signal', v: 'UNDERVALUED' }],
        scores: [{ l: 'Dividend', v: 1, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'None' }, { l: 'Momentum', v: 5, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '1%' }, { l: 'Profit', v: 10, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '95.9%' }, { l: 'Low Debt', v: 9, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Net Cash' }, { l: 'Fair Price', v: 7, max: 10, color: '#D4884A', raw: 'JOKER Signal', rawV: 'UNDERVALUED' }],
        bullets: ["Enterprise video and AI collaboration platform used by millions of businesses globally.", "ROIC of 95.9% — one of the highest capital returns in enterprise software.", "Net cash balance sheet — no financial risk, strong buyback capacity.", "Unloved by the market despite strong fundamentals — creates the valuation opportunity."],
    },
    {
        id: 22, type: 'JOKER', isPro: true, fairValue: 40.85, yahooTicker: 'EXEL',
        stars: 3, sector: 'Health Care', sectorIcon: '🧬',
        irLink: 'https://ir.exelixis.com/',
        company: 'Exelixis Inc', ticker: 'EXEL',
        tag: 'Oncology biotech. Growing pipeline.', tagBold: 'ROIC of 29.5%. Active buybacks.',
        tagFull: "Exelixis is a commercial oncology company with CABOMETYX as its flagship product — approved across multiple cancer types. Consistently growing revenue, high ROIC, and an aggressive buyback programme.",
        pick: 'Cancer drugs. Cash machine.', pickBold: 'Pipeline expanding fast.',
        pickFull: "A commercial oncology company built around CABOMETYX (cabozantinib), a small molecule cancer drug approved across kidney, liver, and thyroid cancers. Strong and growing revenue, exceptional ROIC, and management returning substantial capital through buybacks.",
        ind1l: 'FCF YIELD', ind1v: '9.1%', ind2l: 'ROIC', ind2v: '29.5%',
        metrics: [{ l: 'ROIC', v: '29.5%' }, { l: 'EPS Growth 5y', v: '51.6%' }, { l: '1y Perf', v: '12.1%' }, { l: 'Signal', v: 'FAIRLY VALUED' }],
        scores: [{ l: 'Dividend', v: 1, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'None' }, { l: 'Momentum', v: 6, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '12.1%' }, { l: 'Profit', v: 7, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '29.5%' }, { l: 'Low Debt', v: 9, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Net Cash' }, { l: 'Fair Price', v: 6, max: 10, color: '#D4884A', raw: 'JOKER Signal', rawV: 'FAIRLY VALUED' }],
        bullets: ["Commercial oncology company with CABOMETYX approved across kidney, liver, and thyroid cancers.", "ROIC of 29.5% — strong capital efficiency from a royalty and product revenue mix.", "EPS grew 51.6% annualised over five years — consistent commercial execution.", "$2.16 billion in buybacks since 2023 — management highly disciplined on capital return."],
    },
    {
        id: 23, type: 'JOKER', isPro: true, fairValue: 29.46, yahooTicker: 'CRDO',
        stars: 3, sector: 'Technology', sectorIcon: '💻',
        irLink: 'https://investors.credosemi.com/',
        company: 'Credo Technology Group', ticker: 'CRDO',
        tag: 'AI connectivity chips. Explosive.', tagBold: 'Revenue up 200% year over year.',
        tagFull: "Credo makes Active Electrical Cables that are becoming the standard for AI data centre interconnects — replacing optical cables with 50% lower power and 1000x higher reliability. Revenue tripled in one year.",
        pick: 'AI interconnects. Hypergrowth.', pickBold: 'Replacing optical cables in AI.',
        pickFull: "A fabless semiconductor company whose Active Electrical Cables are becoming the de facto standard for inter-rack connectivity in AI data centres. Revenue up 200% year over year as hyperscalers adopt Credo\'s lower-power, higher-reliability solution over traditional optical cables.",
        ind1l: 'EPS GROWTH', ind1v: '64.0%', ind2l: 'ROIC', ind2v: '4.8%',
        metrics: [{ l: 'P/E', v: '52.4' }, { l: 'EPS Growth 5y', v: '64.0%' }, { l: '1y Perf', v: '116%' }, { l: 'Signal', v: 'FAIRLY VALUED' }],
        scores: [{ l: 'Dividend', v: 1, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'None' }, { l: 'Momentum', v: 9, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '116%' }, { l: 'Profit', v: 3, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '4.8%' }, { l: 'Low Debt', v: 10, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Net Cash' }, { l: 'Fair Price', v: 5, max: 10, color: '#D4884A', raw: 'JOKER Signal', rawV: 'FAIRLY VALUED' }],
        bullets: ["Makes Active Electrical Cables becoming the standard for AI data centre rack-to-rack connections.", "Revenue up 200% year over year — hyperscalers adopting AECs at accelerating pace.", "50% lower power and 1000x higher reliability versus optical — compelling technical advantage.", "Next earnings ~June — well clear of reporting window."],
    },
    {
        id: 24, type: 'JOKER', isPro: true, fairValue: 11.69, yahooTicker: 'CEK.DE',
        stars: 3, sector: 'Technology', sectorIcon: '📡',
        irLink: 'https://www.ceotronics.de/en/investor-relations/',
        company: 'CeoTronics AG', ticker: 'CEK',
        tag: 'Defence comms. Near fair value.', tagBold: 'FCF yield 35%. Low debt.',
        tagFull: "CeoTronics makes communication systems for police, military, and emergency services. A niche German small-cap with consistent profitability and strong free cash flow trading near fair value.",
        pick: 'Police comms niche. Profitable.', pickBold: 'Steady earnings. Low profile.',
        pickFull: "A German manufacturer of professional communication systems for police, military, and emergency responders. Niche market leadership with consistent profitability, strong free cash flow, and modest but growing defence demand.",
        ind1l: 'FCF YIELD', ind1v: '35.2%', ind2l: 'P/E', ind2v: '11.8',
        metrics: [{ l: 'P/E', v: '11.8' }, { l: 'ROIC', v: '11.5%' }, { l: 'FCF Yield', v: '35.2%' }, { l: 'D/E', v: '0.5' }],
        scores: [{ l: 'Dividend', v: 3, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Low' }, { l: 'Momentum', v: 5, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '8.3%' }, { l: 'Profit', v: 4, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '11.5%' }, { l: 'Low Debt', v: 8, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Low' }, { l: 'Fair Price', v: 6, max: 10, color: '#D4884A', raw: 'JOKER Signal', rawV: 'FAIRLY VALUED' }],
        bullets: ["German manufacturer of communication systems for police, military, and emergency services.", "FCF yield of 35.2% — extraordinary cash generation relative to its modest market cap.", "Niche market with high switching costs — customers are government and security agencies.", "EPS grew 25.3% annualised over five years with consistent contract renewals."],
    },
    {
        id: 25, type: 'JOKER', isPro: true, fairValue: 62.14, yahooTicker: 'GMED',
        stars: 3, sector: 'Health Care', sectorIcon: '🏥',
        irLink: 'https://ir.globusmedical.com/',
        company: 'Globus Medical', ticker: 'GMED',
        tag: 'Spine implants. Growing fast.', tagBold: 'EPS up 31% over 5 years.',
        tagFull: "Globus Medical is a spine surgery implant company that merged with NuVasive to create one of the largest musculoskeletal device businesses in the world. Strong growth from an ageing population driving spinal surgery volumes.",
        pick: 'Spine surgery devices. Growth.', pickBold: 'Ageing population tailwind.',
        pickFull: "A leading spine surgery implant company with expanded scale following its merger with NuVasive. Strong secular demand from an ageing global population driving spinal surgery volumes, combined with a growing robotics and enabling technology portfolio.",
        ind1l: 'EPS GROWTH', ind1v: '30.8%', ind2l: 'FCF YIELD', ind2v: '19.7%',
        metrics: [{ l: 'P/E', v: '21.8' }, { l: 'ROIC', v: '8.5%' }, { l: 'FCF Yield', v: '19.7%' }, { l: 'D/E', v: '0.2' }],
        scores: [{ l: 'Dividend', v: 1, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'None' }, { l: 'Momentum', v: 6, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '20%' }, { l: 'Profit', v: 3, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '8.5%' }, { l: 'Low Debt', v: 9, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Low' }, { l: 'Fair Price', v: 5, max: 10, color: '#D4884A', raw: 'JOKER Signal', rawV: 'OVERVALUED' }],
        bullets: ["Leading spine surgery implant company — one of the largest musculoskeletal device firms globally.", "Secular demand from ageing populations driving consistent spinal procedure volume growth.", "Growing robotics and enabling technology portfolio differentiates from commodity implant makers.", "EPS grew 30.8% annualised over five years — consistent commercial and operational execution."],
    },
    {
        id: 26, type: 'JOKER', isPro: true, fairValue: 76.63, yahooTicker: 'AGYS',
        stars: 3, sector: 'Technology', sectorIcon: '💻',
        irLink: 'https://ir.agilysys.com/',
        company: 'Agilysys Inc', ticker: 'AGYS',
        tag: 'Hospitality SaaS. Sticky revenue.', tagBold: 'ROIC of 27.5%.',
        tagFull: "Agilysys provides property management and point-of-sale software exclusively for the hospitality industry — hotels, casinos, and resorts. High switching costs, recurring revenue, and consistent earnings growth.",
        pick: 'Hotel software. SaaS model.', pickBold: 'High switching costs.',
        pickFull: "The leading provider of property management and hospitality technology to hotels, casinos, and resorts. Subscription-based revenue with high switching costs, consistent earnings growth, and a growing installed base of premium hospitality clients.",
        ind1l: 'FCF YIELD', ind1v: '19.1%', ind2l: 'ROIC', ind2v: '27.5%',
        metrics: [{ l: 'P/E', v: '62.0' }, { l: 'ROIC', v: '27.5%' }, { l: 'FCF Yield', v: '19.1%' }, { l: 'D/E', v: '0.5' }],
        scores: [{ l: 'Dividend', v: 1, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'None' }, { l: 'Momentum', v: 4, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '-10%' }, { l: 'Profit', v: 7, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '27.5%' }, { l: 'Low Debt', v: 8, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Low' }, { l: 'Fair Price', v: 6, max: 10, color: '#D4884A', raw: 'JOKER Signal', rawV: 'FAIRLY VALUED' }],
        bullets: ["Exclusive hospitality technology provider — property management and POS for hotels, casinos, resorts.", "High switching costs: once a large hotel installs Agilysys, replacement is disruptive and rare.", "ROIC of 27.5% — strong capital returns from a subscription-first business model.", "EPS grew 25.2% annualised over five years; consistent client additions and upsell."],
    },
    {
        id: 27, type: 'JOKER', isPro: true, fairValue: 100.67, yahooTicker: 'INCY',
        stars: 3, sector: 'Health Care', sectorIcon: '🧬',
        irLink: 'https://investor.incyte.com/',
        company: 'Incyte Corp', ticker: 'INCY',
        tag: 'Oncology biotech. Strong pipeline.', tagBold: 'ROIC of 38%. Growing earnings.',
        tagFull: "Incyte is a commercial-stage oncology and inflammation biotech with Jakafi as its flagship product. Consistent earnings growth, strong ROIC, and an expanding pipeline of next-generation treatments.",
        pick: 'Cancer biotech. Pipeline depth.', pickBold: 'Profitable with strong ROIC.',
        pickFull: "A commercial oncology company with Jakafi (ruxolitinib) as its flagship product for myelofibrosis and GVHD. Consistent double-digit earnings growth, expanding into dermatology and additional indications, with a rich pipeline of follow-on compounds.",
        ind1l: 'FCF YIELD', ind1v: '9.4%', ind2l: 'ROIC', ind2v: '38.0%',
        metrics: [{ l: 'ROIC', v: '38.0%' }, { l: 'EPS Growth 5y', v: '46.9%' }, { l: '1y Perf', v: '37.0%' }, { l: 'Signal', v: 'FAIRLY VALUED' }],
        scores: [{ l: 'Dividend', v: 1, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'None' }, { l: 'Momentum', v: 7, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '37%' }, { l: 'Profit', v: 8, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '38.0%' }, { l: 'Low Debt', v: 9, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Net Cash' }, { l: 'Fair Price', v: 6, max: 10, color: '#D4884A', raw: 'JOKER Signal', rawV: 'FAIRLY VALUED' }],
        bullets: ["Commercial oncology and inflammation biotech with Jakafi — approved for myelofibrosis and GVHD.", "ROIC of 38% — strong capital returns from a profitable commercial-stage biotech.", "EPS grew 46.9% annualised over five years — consistent pipeline and commercial execution.", "Expanding into dermatology and new oncology indications — growing addressable market."],
    },
    {
        id: 28, type: 'JOKER', isPro: true, fairValue: 336.21, yahooTicker: 'CAMB.BR',
        stars: 3, sector: 'Materials', sectorIcon: '♻️',
        irLink: 'https://www.campine.be/en/investors',
        company: 'Campine NV', ticker: 'CAMB',
        tag: 'Lead recycling. Circular economy.', tagBold: 'EPS grew 76% over 5 years.',
        tagFull: "Campine is a Belgian lead recycler and specialty antimony products producer. A circular economy business processing industrial waste into high-value materials — strong demand from battery recycling and growing EV sector.",
        pick: 'Lead recycler. Circular economy.', pickBold: 'EV battery recycling tailwind.',
        pickFull: "A Belgian specialist in lead recycling and antimony compounds — processing used batteries and industrial waste into high-purity materials for battery, electronics, and flame retardant applications. Strong secular tailwind from EV battery recycling demand.",
        ind1l: 'EPS GROWTH', ind1v: '76.2%', ind2l: 'ROIC', ind2v: '24.7%',
        metrics: [{ l: 'ROIC', v: '24.7%' }, { l: 'EPS Growth 5y', v: '76.2%' }, { l: '1y Perf', v: '12.5%' }, { l: 'Signal', v: 'UNDERVALUED' }],
        scores: [{ l: 'Dividend', v: 3, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Moderate' }, { l: 'Momentum', v: 5, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '12.5%' }, { l: 'Profit', v: 7, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '24.7%' }, { l: 'Low Debt', v: 7, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Low' }, { l: 'Fair Price', v: 7, max: 10, color: '#D4884A', raw: 'JOKER Signal', rawV: 'UNDERVALUED' }],
        bullets: ["Belgian specialist in lead recycling and antimony compounds — circular economy model.", "Processes used batteries and industrial waste into high-purity materials for batteries and electronics.", "Strong secular tailwind: EV battery recycling demand growing rapidly across Europe.", "EPS grew 76.2% annualised over five years — extraordinary growth for a specialty materials company."],
    },
    {
        id: 29, type: 'ACE', isPro: true, fairValue: 136.87, yahooTicker: 'MLI',
        stars: 4, sector: 'Industrials', sectorIcon: '🏭',
        irLink: 'https://www.muellerindustries.com/investor-relations/',
        company: 'Mueller Industries', ticker: 'MLI',
        tag: 'Copper products. 19% below FV.', tagBold: 'ROIC of 43%. Strong fundamentals.',
        tagFull: "Mueller Industries is a leading manufacturer of copper and brass products for plumbing, HVAC, and industrial applications. Consistently high ROIC, low debt, and a Piotroski score that reflects improving financial health.",
        pick: 'Copper products. Quality compounder.', pickBold: 'Strong financials. Low debt.',
        pickFull: "A leading US manufacturer of copper tubing, fittings, and brass products for plumbing, HVAC, refrigeration, and industrial markets. Consistent high ROIC of 43%, improving financial metrics across all Piotroski dimensions, and trading below fair value.",
        ind1l: 'ROIC', ind1v: '43.1%', ind2l: 'P/E', ind2v: '15.8',
        metrics: [{ l: 'P/E', v: '15.8' }, { l: 'ROIC', v: '43.1%' }, { l: 'EPS Growth 5y', v: '41.1%' }, { l: 'D/E', v: '0.2' }],
        scores: [{ l: 'Earnings Stability', v: 8, max: 10, color: '#4CAF82', raw: 'Earnings', rawV: 'Stable 5y' }, { l: 'Momentum', v: 7, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '39%' }, { l: 'Profit', v: 8, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '43.1%' }, { l: 'Low Debt', v: 9, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Very Low' }, { l: 'Fair Price', v: 6, max: 10, color: '#D4884A', raw: 'ACE Signal', rawV: 'UNDERVALUED' }],
        bullets: ["Leading US manufacturer of copper tubing and brass fittings for plumbing, HVAC, and industrial uses.", "ROIC of 43.1% — exceptional capital efficiency for an industrial manufacturer.", "EPS grew 41.1% annualised over five years with consistent improvement across Piotroski metrics.", "Trading at 19% below fair value with minimal debt — strong Piotroski F-Score."],
    },
    {
        id: 30, type: 'ACE', isPro: true, fairValue: 103.6, yahooTicker: 'STRA',
        stars: 3, sector: 'Industrials', sectorIcon: '📚',
        irLink: 'https://ir.strategiceducation.com/',
        company: 'Strategic Education', ticker: 'SQE',
        tag: 'Online education. 32% below FV.', tagBold: 'Improving fundamentals across board.',
        tagFull: "Strategic Education operates Strayer University and Capella University — two accredited online universities serving working adults. Improving financial metrics, low debt, and trading below fair value.",
        pick: 'Online university. Improving.', pickBold: 'Adult education compounder.',
        pickFull: "Operates Strayer University and Capella University serving working adult students with online degree programs. Consistent improvement across financial health metrics, low debt, and significant valuation discount create a compelling Piotroski case.",
        ind1l: 'P/E', ind1v: '14.8', ind2l: 'EPS GROWTH', ind2v: '7.9%',
        metrics: [{ l: 'P/E', v: '14.8' }, { l: 'ROIC', v: '4.8%' }, { l: 'EPS Growth 5y', v: '7.9%' }, { l: 'D/E', v: '0.2' }],
        scores: [{ l: 'Earnings Stability', v: 7, max: 10, color: '#4CAF82', raw: 'Earnings', rawV: 'Stable' }, { l: 'Momentum', v: 4, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '-3.4%' }, { l: 'Profit', v: 3, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '4.8%' }, { l: 'Low Debt', v: 9, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Very Low' }, { l: 'Fair Price', v: 7, max: 10, color: '#D4884A', raw: 'ACE Signal', rawV: 'UNDERVALUED' }],
        bullets: ["Operates Strayer University and Capella University — accredited online programs for working adults.", "Low debt and improving Piotroski metrics across profitability, leverage, and efficiency.", "Growing demand for flexible, affordable online degrees from working adult population.", "Trading at 32% below fair value — overlooked by market focused on growth tech."],
    },
    {
        id: 31, type: 'QUEEN', isPro: true, fairValue: 10.35, yahooTicker: 'EXAE.AT',
        stars: 3, sector: 'Financials', sectorIcon: '🏛️',
        irLink: 'https://www.helex.gr/en/investor-relations',
        company: 'Hellenic Exchanges', ticker: 'HEE',
        tag: 'Athens Stock Exchange operator.', tagBold: 'ROIC of 34.7%. Monopoly.',
        tagFull: "Hellenic Exchanges operates the Athens Stock Exchange — a regulated monopoly on Greek capital markets infrastructure. Consistent dividends, high ROIC, and benefiting from reviving Greek economic activity.",
        pick: 'Stock exchange monopoly. Greece.', pickBold: 'Regulated infrastructure. Income.',
        pickFull: "The operator of the Athens Stock Exchange — a regulated market infrastructure monopoly benefiting from Greece\'s economic recovery and rising market activity. High ROIC, consistent dividends, and an asset-light business model.",
        ind1l: 'ROIC', ind1v: '34.7%', ind2l: 'EPS GROWTH', ind2v: '55.6%',
        metrics: [{ l: 'ROIC', v: '34.7%' }, { l: 'EPS Growth 5y', v: '55.6%' }, { l: '1y Perf', v: '28.1%' }, { l: 'Signal', v: 'UNDERVALUED' }],
        scores: [{ l: 'Dividend', v: 6, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Moderate' }, { l: 'Momentum', v: 6, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '28.1%' }, { l: 'Profit', v: 7, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '34.7%' }, { l: 'Low Debt', v: 9, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Net Cash' }, { l: 'Fair Price', v: 7, max: 10, color: '#D4884A', raw: 'QUEEN Signal', rawV: 'UNDERVALUED' }],
        bullets: ["Operates the Athens Stock Exchange — a regulated monopoly on Greek capital market infrastructure.", "ROIC of 34.7% from an asset-light, fee-based business model with no capital intensity.", "Greece\'s economic recovery driving rising market activity and transaction volumes.", "EPS grew 55.6% annualised over five years — strong leverage to improving Greek capital markets."],
    },
    {
        id: 32, type: 'QUEEN', isPro: true, fairValue: 45.99, yahooTicker: 'CMRE',
        stars: 3, sector: 'Industrials', sectorIcon: '🚢',
        irLink: 'https://www.costamare.com/investor-relations/',
        company: 'Costamare Inc', ticker: 'CMRE',
        tag: 'Container ships. 64% below FV.', tagBold: 'EPS grew 80% over 5 years.',
        tagFull: "Costamare is a major container ship owner operating on long-term fixed-rate charters to the world\'s top shipping lines. Extraordinary discount to intrinsic value with consistent earnings and a growing dividend.",
        pick: 'Container ships. Long charters.', pickBold: 'Massive discount to fair value.',
        pickFull: "A major independent container ship owner with vessels chartered to leading global shipping lines on long-term fixed-rate contracts. Exceptional earnings visibility, consistent dividend, and trading at 64% below fair value.",
        ind1l: 'EPS GROWTH', ind1v: '80.5%', ind2l: 'P/E', ind2v: '5.4',
        metrics: [{ l: 'P/E', v: '5.4' }, { l: 'ROIC', v: '11.9%' }, { l: 'EPS Growth 5y', v: '80.5%' }, { l: 'D/E', v: '0.8' }],
        scores: [{ l: 'Dividend', v: 6, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Moderate' }, { l: 'Momentum', v: 9, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '118%' }, { l: 'Profit', v: 5, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '11.9%' }, { l: 'Low Debt', v: 6, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Moderate' }, { l: 'Fair Price', v: 9, max: 10, color: '#D4884A', raw: 'QUEEN Signal', rawV: 'STRONGLY UNDERVALUED' }],
        bullets: ["Major container ship owner with vessels on long-term fixed-rate charters to global shipping lines.", "EPS grew 80.5% annualised over five years — one of the strongest earnings growth records in shipping.", "Stock up 118% in one year yet still trading at 36% of fair value.", "Long-term charter contracts provide exceptional earnings visibility and downside protection."],
    },
    {
        id: 33, type: 'QUEEN', isPro: true, fairValue: 306.64, yahooTicker: 'WAWI.OL',
        stars: 3, sector: 'Industrials', sectorIcon: '🚢',
        irLink: 'https://www.walleniuswilhelmsen.com/investors/',
        company: 'Wallenius Wilhelmsen', ticker: 'WAWI',
        tag: 'Car carrier leader. 61% below FV.', tagBold: 'P/E of 4.9. Strong cash flow.',
        tagFull: "Wallenius Wilhelmsen is the world\'s leading vehicle logistics company — transporting cars, trucks, and high-value machinery across global trade routes. Trading at an extraordinary discount with P/E below 5.",
        pick: 'World car shipping leader.', pickBold: 'Deep discount to fair value.',
        pickFull: "The world\'s leading vehicle logistics company — operating the largest fleet of roll-on/roll-off vessels transporting cars, trucks, and high-value machinery globally. Trading at P/E 4.9 despite strong earnings and consistent cash flow generation.",
        ind1l: 'FCF YIELD', ind1v: '34.6%', ind2l: 'P/E', ind2v: '4.9',
        metrics: [{ l: 'P/E', v: '4.9' }, { l: 'ROIC', v: '14.7%' }, { l: 'FCF Yield', v: '34.6%' }, { l: 'D/E', v: '1.4' }],
        scores: [{ l: 'Dividend', v: 5, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Moderate' }, { l: 'Momentum', v: 6, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '32%' }, { l: 'Profit', v: 5, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '14.7%' }, { l: 'Low Debt', v: 4, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Moderate-High' }, { l: 'Fair Price', v: 9, max: 10, color: '#D4884A', raw: 'QUEEN Signal', rawV: 'STRONGLY UNDERVALUED' }],
        bullets: ["World\'s leading vehicle logistics company — transporting cars, trucks, and machinery by sea.", "Largest RoRo fleet globally; scale and network advantages are difficult to replicate.", "EPS grew 41% annualised over five years with consistent contract renewals from OEM customers.", "Trading at 39% of fair value — P/E of 4.9 for the global market leader in vehicle shipping."],
    },
    {
        id: 34, type: 'QUEEN', isPro: true, fairValue: 44.72, yahooTicker: 'LPG',
        stars: 3, sector: 'Energy', sectorIcon: '⚡',
        irLink: 'https://ir.dorianlpg.com/',
        company: 'Dorian LPG', ticker: 'LPG',
        tag: 'LPG tankers. 31% below FV.', tagBold: 'FCF yield 33.5%. Low debt.',
        tagFull: "Dorian LPG operates Very Large Gas Carriers transporting liquefied petroleum gas globally. Solid FCF generation and moderate debt with LPG trade projected to grow 6% in 2026 from rising US and Middle East exports.",
        pick: 'LPG shipping. Gas trade growth.', pickBold: 'FCF machine. Rising exports.',
        pickFull: "A leading VLGC operator transporting liquefied petroleum gas across global trade routes. LPG trade growth of 6% projected for 2026 driven by rising US and Middle East exports, with Dorian well-positioned to capture the volume growth.",
        ind1l: 'FCF YIELD', ind1v: '33.5%', ind2l: 'P/E', ind2v: '10.9',
        metrics: [{ l: 'P/E', v: '10.9' }, { l: 'ROIC', v: '10.9%' }, { l: 'FCF Yield', v: '33.5%' }, { l: 'D/E', v: '0.6' }],
        scores: [{ l: 'Dividend', v: 5, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Variable' }, { l: 'Momentum', v: 7, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '43%' }, { l: 'Profit', v: 4, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '10.9%' }, { l: 'Low Debt', v: 7, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Moderate' }, { l: 'Fair Price', v: 7, max: 10, color: '#D4884A', raw: 'QUEEN Signal', rawV: 'UNDERVALUED' }],
        bullets: ["Operates Very Large Gas Carriers transporting LPG across global trade routes.", "LPG trade projected to grow 6% in 2026, driven by rising US and Middle East exports.", "FCF yield of 33.5% — strong cash generation supporting returns to shareholders.", "Trading at 31% below fair value with moderate leverage in a growing trade market."],
    },
    {
        id: 35, type: 'JOKER', isPro: true, fairValue: 500.0, yahooTicker: 'BIOA-B.ST',
        stars: 4, sector: 'Health Care', sectorIcon: '🧬',
        irLink: 'https://www.bioarctic.se/en/investors/',
        company: 'BioArctic AB', ticker: 'BIOA B',
        tag: 'Alzheimer drug royalties. Growth.', tagBold: 'Leqembi royalty stream growing.',
        tagFull: "BioArctic co-developed Leqembi (lecanemab) with Eisai — the first approved disease-modifying Alzheimer\'s treatment. BioArctic earns royalties on global sales, which are ramping as reimbursement expands globally.",
        pick: 'Alzheimer royalties. Leqembi.', pickBold: 'First approved Alzheimer drug.',
        pickFull: "BioArctic co-developed Leqembi (lecanemab) with Eisai — the first approved disease-modifying Alzheimer\'s treatment. As the royalty recipient, BioArctic\'s revenue grows with global Leqembi reimbursement expansion, with the EU and Japan approvals driving the next phase of growth.",
        ind1l: 'ROIC', ind1v: '36.7%', ind2l: 'EPS GROWTH', ind2v: '75.9%',
        metrics: [{ l: 'ROIC', v: '36.7%' }, { l: 'EPS Growth 5y', v: '75.9%' }, { l: '1y Perf', v: '51%' }, { l: 'Signal', v: 'UNDERVALUED' }],
        scores: [{ l: 'Dividend', v: 1, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'None' }, { l: 'Momentum', v: 8, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '51%' }, { l: 'Profit', v: 8, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '36.7%' }, { l: 'Low Debt', v: 9, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Net Cash' }, { l: 'Fair Price', v: 7, max: 10, color: '#D4884A', raw: 'JOKER Signal', rawV: 'UNDERVALUED' }],
        bullets: ["Co-developer of Leqembi — the first approved disease-modifying Alzheimer\'s treatment globally.", "Earns royalties on Leqembi sales as reimbursement expands across the US, EU, and Japan.", "ROIC of 36.7% — high returns from an asset-light royalty and licensing model.", "EPS grew 75.9% annualised over five years as the pipeline and commercial products matured."],
    },
    {
        id: 36, type: 'QUEEN', isPro: true, fairValue: 23.72, yahooTicker: '6QK.DE',
        stars: 3, sector: 'Industrials', sectorIcon: '🔫',
        irLink: 'https://www.msiplc.com/investor-relations/',
        company: 'MS International PLC', ticker: '6QK',
        tag: 'Defence. 34% below fair value.', tagBold: 'ROIC 25.5%. EPS up 65% in 5y.',
        tagFull: "MS International is a UK defence company manufacturing naval gun systems and petrol station forecourt equipment. A niche dual-market operator with strong earnings growth and low debt trading below fair value.",
        pick: 'Naval guns. Defence niche.', pickBold: 'Dual market. Strong growth.',
        pickFull: "A UK defence company with two distinct businesses: naval gun systems sold to navies globally, and petrol station forecourt equipment. Niche market positions in both segments, strong EPS growth, and trading at a discount to fair value.",
        ind1l: 'ROIC', ind1v: '25.5%', ind2l: 'EPS GROWTH', ind2v: '65.2%',
        metrics: [{ l: 'P/E', v: '15.5' }, { l: 'ROIC', v: '25.5%' }, { l: 'EPS Growth 5y', v: '65.2%' }, { l: 'D/E', v: '1.0' }],
        scores: [{ l: 'Dividend', v: 4, max: 10, color: '#4CAF82', raw: 'Div. Yield', rawV: 'Low' }, { l: 'Momentum', v: 6, max: 10, color: '#5B8FD4', raw: '1y Perf', rawV: '30%' }, { l: 'Profit', v: 6, max: 10, color: '#5B8FD4', raw: 'ROIC', rawV: '25.5%' }, { l: 'Low Debt', v: 5, max: 10, color: '#9B6ED4', raw: 'Net Debt', rawV: 'Moderate' }, { l: 'Fair Price', v: 7, max: 10, color: '#D4884A', raw: 'QUEEN Signal', rawV: 'UNDERVALUED' }],
        bullets: ["UK defence manufacturer of naval gun systems sold to navies across Europe and Asia.", "Dual-market operator: naval weapons and petrol station forecourt equipment — two stable niches.", "EPS grew 65.2% annualised over five years — strong earnings trajectory.", "Trading at 34% below fair value with consistent earnings from long-cycle defence contracts."],
    }'''

with open(src, 'r', encoding='utf-8') as f:
    html = f.read()

import re
old_match = re.search(r'(const cards\s*=\s*\[)(.*?)(\];)', html, re.DOTALL)
if not old_match:
    print('ERROR: cards array not found')
    exit(1)

print(f'Old cards: {len(old_match.group(2))} chars')
new_html = html[:old_match.start()] + 'const cards = [\n' + new_cards + '\n];' + html[old_match.end():]
print(f'New cards: {len(new_cards)} chars')

with open(src, 'w', encoding='utf-8') as f:
    f.write(new_html)
print('Done — 36 cards written.')
