import re

CARDS_PATH = '/Users/radekmajewski/Downloads/valujack/public/cards.js'

descriptions = {
    387: ('ACT Energy Technologies Ltd', 'Canadian oilfield tubular services. Recovery play.', 'Oilfield services recovery.', "ACT Energy Technologies provides tubular running services and equipment rental to the Canadian oil and gas industry. The company operates in the Western Canadian Sedimentary Basin and benefits from rising Canadian energy investment as oilsands and tight oil activity expands.", 'Canadian oilfield services. Recovery momentum.', 'Energy services recovery.', "A Canadian oilfield tubular services company recovering in the Western Canadian energy sector. ACT Energy benefits from rising Canadian energy investment and tight oil activity expansion, with revenue growing 9.8% annualised.", ["Tubular running services and equipment rental for Canadian oil and gas producers.", "Operations in the Western Canadian Sedimentary Basin — core Canadian energy geography.", "Revenue grew 9.8% annualised as Canadian energy investment activity expanded.", "Recovery play with improving margins as oilfield services pricing strengthens."]),
    406: ('Evertz Technologies Ltd', 'Canadian broadcast technology. High ROIC momentum.', 'Broadcast infrastructure leader.', "Evertz Technologies is a Canadian manufacturer of broadcast infrastructure equipment — the routing, monitoring, and production systems that sit at the heart of television studios and streaming facilities worldwide. The company has a strong market position in live broadcast infrastructure with accelerating demand from streaming platform investment.", 'Broadcast tech. High ROIC momentum.', 'Broadcast infrastructure momentum.', "A Canadian broadcast technology company with a 32.8% ROIC and EPS growth of 8.3% annualised. Evertz routing and monitoring systems are embedded in virtually every major broadcaster and streaming facility globally — benefiting from accelerating streaming infrastructure investment.", ["Broadcast infrastructure equipment — routing, monitoring and production systems for TV and streaming.", "ROIC of 32.8% reflects strong intellectual property and switching costs in broadcast technology.", "EPS grew 8.3% annualised with consistent demand from broadcaster infrastructure upgrades.", "Accelerating demand from streaming platform investment in broadcast infrastructure."]),
    407: ('Filtronic PLC', 'UK defence and telecoms components. High growth momentum.', 'Defence and telecoms components.', "Filtronic is a UK manufacturer of advanced electronic components for defence, space, and telecoms — including solid-state power amplifiers and mmWave transceivers. The company has secured significant contracts for satellite communications components and is growing rapidly from a small base.", 'Defence components. Exceptional growth.', 'Defence electronics momentum.', "A UK defence and telecoms components manufacturer with a 32.3% ROIC and EPS growth of 172.9% from a low base. Filtronic is winning significant satellite and defence communications contracts — mmWave components for low-earth-orbit satellite constellations represent a major structural growth opportunity.", ["Advanced electronic components for defence, space and telecoms applications.", "ROIC of 32.3% reflects high value-add in mission-critical defence and satellite components.", "EPS grew 172.9% annualised from a low base as defence and satellite contracts accelerated.", "Revenue grew 31.6% annualised driven by mmWave satellite and defence communications demand."]),
    408: ('Firan Technology Group Corp', 'Canadian aerospace electronics. High growth momentum.', 'Aerospace electronics manufacturer.', "Firan Technology Group manufactures precision printed circuit boards and cockpit illumination systems for aerospace and defence applications. The company supplies components to Boeing, Airbus, and major defence contractors — benefiting from the global commercial aviation recovery and defence spending growth.", 'Aerospace electronics. Strong growth momentum.', 'Aerospace electronics compounder.', "A Canadian aerospace electronics manufacturer with a 10.6% ROIC and EPS growth of 54.0% annualised. Firan Technology supplies precision circuit boards and cockpit systems to Boeing, Airbus, and defence contractors — benefiting from commercial aviation recovery and rising defence spending.", ["Precision printed circuit boards and cockpit illumination for aerospace and defence.", "Supplies Boeing, Airbus and major defence contractors — long-term qualified supplier relationships.", "EPS grew 54.0% annualised as commercial aviation recovery drove component demand sharply higher.", "Revenue grew 17.8% annualised with aerospace and defence backlogs at multi-year highs."]),
    409: ('Games Workshop Group PLC', 'UK tabletop miniatures. Exceptional ROIC.', 'Warhammer IP monopoly.', "Games Workshop is the UK creator and manufacturer of Warhammer tabletop miniatures and games — one of the most recognisable intellectual property franchises in the hobby gaming world. The company controls the entire value chain from design through manufacturing and retail, generating extraordinary returns on capital.", 'Warhammer monopoly. Exceptional returns.', 'IP-driven monopoly compounder.', "The creator of Warhammer with a 107.7% ROIC — one of the highest in UK equity markets. Games Workshop owns, manufactures, and retails its own miniatures globally — a vertically integrated IP monopoly with passionate, highly loyal customers who spend consistently over decades.", ["Creator and owner of the Warhammer tabletop miniatures franchise — globally recognised IP.", "ROIC of 107.7% reflects extraordinary vertical integration and intellectual property economics.", "EPS grew 10.9% annualised with consistent global expansion of the Warhammer universe.", "Licensing revenue from video games and media adding a growing royalty income stream."]),
    410: ('Garmin Ltd', 'US GPS and navigation devices. High ROIC compounder.', 'GPS technology leader.', "Garmin is a US manufacturer of GPS navigation and wearable technology across automotive, aviation, marine, outdoor, and fitness markets. The company has successfully diversified from automotive sat-navs into high-growth smartwatch and aviation markets.", 'GPS technology. Multi-market compounder.', 'Navigation technology compounder.', "A US GPS and navigation technology company with a 25.5% ROIC and EPS growth of 10.8% annualised. Garmin has successfully diversified across aviation, marine, outdoor, and fitness markets — reducing automotive dependency and building high-margin recurring revenue from subscription services.", ["GPS navigation and wearable technology across aviation, marine, outdoor and fitness markets.", "ROIC of 25.5% reflects strong brand and technology moat across multiple GPS verticals.", "EPS grew 10.8% annualised with consistent growth from aviation and wearables segments.", "Revenue grew 15.1% annualised as smartwatch and aviation growth accelerated strongly."]),
    411: ('Gaztransport et technigaz SA', 'French LNG tank designer. Exceptional momentum.', 'LNG technology licensor.', "GTT designs the membrane containment systems used in virtually all LNG carriers and floating storage units worldwide. The company holds the dominant intellectual property position in LNG tank technology — earning royalties on every new LNG vessel ordered globally as the energy transition drives unprecedented LNG fleet expansion.", 'LNG royalties. Exceptional momentum.', 'LNG technology momentum.', "The dominant LNG tank technology licensor with a 114.5% ROIC and EPS growth of 15.8% annualised showing exceptional momentum as global LNG fleet orders accelerate. GTT earns royalties on virtually every new LNG carrier ordered — a pure IP model benefiting from the global energy transition to cleaner gas.", ["Dominant LNG tank membrane technology licensor — royalties on virtually every new LNG vessel.", "ROIC of 114.5% — extraordinary pure intellectual property business model.", "EPS grew 15.8% annualised as global LNG fleet expansion drove royalty order backlog higher.", "Revenue grew 25.2% annualised as LNG infrastructure investment accelerated globally."]),
    412: ('Gorman-Rupp Co', 'US pump manufacturer. Consistent compounder.', 'US pump manufacturer.', "Gorman-Rupp is a US manufacturer of pumps and pump systems for water, wastewater, construction, industrial, and military applications. The company has paid dividends for over 80 consecutive years — one of the longest dividend streaks in US manufacturing.", 'Pump manufacturer. Dividend compounder.', 'Industrial pump compounder.', "A US pump manufacturer with a 7.3% ROIC and over 80 consecutive years of dividend payments. Gorman-Rupp pumps serve water utilities, wastewater treatment, and military applications — defensive, recurring demand from infrastructure maintenance and upgrade cycles.", ["Pumps and pump systems for water, wastewater, construction and military applications.", "Over 80 consecutive years of dividend payments — exceptional dividend consistency.", "EPS grew 15.8% annualised as infrastructure spending and pump replacement demand increased.", "Defensive demand from water utility maintenance and municipal infrastructure upgrades."]),
    413: ('Gulfport Energy Corp', 'US natural gas producer. High growth momentum.', 'US natural gas producer.', "Gulfport Energy is a US independent natural gas producer operating in the Utica and SCOOP/STACK shale plays. The company has restructured its balance sheet and is generating strong free cash flow from its natural gas and NGL production as LNG export demand drives structural improvement in US gas prices.", 'US natural gas. Strong momentum.', 'Natural gas momentum play.', "A US natural gas producer with a 16.1% ROIC and EPS growth of 30.2% annualised operating in the Utica and SCOOP shale plays. Gulfport benefits from structurally improving US natural gas prices as LNG export capacity expansion drives sustained demand for domestic gas production.", ["Natural gas and NGL production from Utica and SCOOP shale plays in the US.", "ROIC of 16.1% reflects improving capital efficiency from restructured balance sheet.", "EPS grew 30.2% annualised as natural gas prices and production volumes improved.", "Revenue grew 42.5% annualised as US LNG export demand drove gas price improvement."]),
    414: ('Halma PLC', 'UK safety and environmental technology. Quality compounder.', 'Safety technology compounder.', "Halma is a UK company that acquires and grows niche safety, environmental, and analysis technology businesses. The group has delivered 40+ consecutive years of dividend growth by identifying and acquiring small, high-quality businesses in defensible niches.", 'Safety tech. Forty years of dividend growth.', 'Safety technology compounder.', "A UK safety and environmental technology group with a 13.2% ROIC and over 40 consecutive years of dividend growth. Halma acquires niche businesses making fire detection, gas sensing, and water analysis instruments — products that are legally required in buildings, utilities, and industrial facilities worldwide.", ["Acquires niche safety, environmental and analysis technology businesses globally.", "Over 40 consecutive years of dividend growth — exceptional capital allocation track record.", "ROIC of 13.2% reflects consistent value creation from disciplined acquisition strategy.", "EPS grew 11.4% annualised with consistent compounding from the acquisition platform."]),
    416: ('Hydratec Industries NV', 'Dutch agri-food technology. High ROIC.', 'Agri-food technology niche.', "Hydratec Industries is a Dutch holding company with businesses in agriculture technology, food processing equipment, and industrial automation. The company operates specialist businesses serving dairy, horticulture, and food processing customers across the Netherlands and internationally.", 'Agri-food technology. High ROIC.', 'Dutch agri-tech compounder.', "A Dutch agri-food technology holding company with a 21.7% ROIC and EPS growth of 46.6% annualised. Hydratec operates specialist businesses in dairy technology, greenhouse horticulture, and food processing equipment — niche markets with high barriers to entry and long customer relationships.", ["Agri-food technology across dairy, horticulture and food processing equipment.", "ROIC of 21.7% reflects high value-add in specialist agri-food technology niches.", "EPS grew 46.6% annualised from improved margins across specialist business units.", "Long customer relationships in dairy and greenhouse technology create recurring demand."]),
    418: ('Innoviva Inc', 'US respiratory pharma royalties. High ROIC.', 'Respiratory pharma royalties.', "Innoviva is a US company that receives royalties from GlaxoSmithKline on respiratory drug sales — primarily the blockbuster RELVAR/BREO ELLIPTA and ANORO ELLIPTA products. The company is a pure royalty vehicle with minimal operating costs and near-100% cash conversion.", 'GSK respiratory royalties. High ROIC.', 'Pharmaceutical royalty income.', "A US pharmaceutical royalty company with a 26.6% ROIC receiving royalties from GlaxoSmithKline on blockbuster respiratory drugs. Innoviva has minimal operating costs and converts virtually all royalty income to free cash flow — an exceptionally capital-efficient income model.", ["GSK respiratory drug royalties — RELVAR, BREO ELLIPTA and ANORO ELLIPTA products.", "ROIC of 26.6% from a near-pure royalty model with minimal operating costs.", "EPS grew 12.7% annualised as GSK respiratory drug sales grew consistently.", "Near-100% cash conversion — virtually all royalty income flows through to free cash flow."]),
    419: ('Itafos Inc', 'Canadian phosphate fertiliser producer. High growth.', 'Phosphate fertiliser producer.', "Itafos is a Canadian phosphate fertiliser company operating mines and processing facilities in the US and Brazil. The company produces MAP and DAP fertilisers essential for global crop production — benefiting from structural food security demand and tight global phosphate supply.", 'Phosphate fertiliser. Strong momentum.', 'Fertiliser producer momentum.', "A Canadian phosphate fertiliser company with an 18.1% ROIC and EPS growth of 30.4% annualised. Itafos benefits from structural demand for phosphate fertilisers as global food production must expand to feed a growing population — and phosphate rock is a finite, geographically concentrated resource.", ["MAP and DAP phosphate fertiliser production from US and Brazilian operations.", "ROIC of 18.1% reflects improving margins from phosphate processing efficiency.", "EPS grew 30.4% annualised as fertiliser demand and pricing remained structurally elevated.", "Revenue grew 13.6% annualised as global food security demand underpinned fertiliser consumption."]),
    420: ('ITT Inc', 'US industrial technology. High EPS growth.', 'US industrial technology.', "ITT is a US industrial manufacturer of motion and flow control products — friction materials, shock absorbers, pumps, and connectors for automotive, aerospace, rail, and industrial applications. The company has transformed from a conglomerate into a focused industrial technology business.", 'Industrial technology. Strong momentum.', 'US industrial compounder.', "A US industrial technology company with a 14.9% ROIC and EPS growth of 50.7% annualised. ITT produces friction materials, pumps, and connectors for automotive, aerospace, and industrial applications — benefiting from electrification-driven demand for new friction and motion control solutions.", ["Friction materials, pumps and connectors for automotive, aerospace and industrial applications.", "ROIC of 14.9% with improving trajectory from focused industrial technology strategy.", "EPS grew 50.7% annualised as electrification drove demand for new friction and motion solutions.", "Revenue grew 8.5% annualised with consistent outperformance across industrial end markets."]),
    421: ('John B Sanfilippo & Son Inc', 'US specialty nut processor. Consistent compounder.', 'US nut processor.', "John B Sanfilippo is a US processor and distributor of pecans, walnuts, cashews, and mixed nuts sold under the Fisher, Orchard Valley Harvest, and Southern Style Nuts brands. The company supplies US retail, foodservice, and industrial channels with branded and private-label nut products.", 'Specialty nuts. Consistent compounder.', 'US food compounder.', "A US specialty nut processor with a 15.1% ROIC and consistent earnings from branded nut products. Sanfilippo produces Fisher nuts and Orchard Valley Harvest — strong retail brands with consistent consumer demand from the growing healthy snacking market.", ["Pecans, walnuts, cashews and mixed nuts under Fisher and Orchard Valley Harvest brands.", "ROIC of 15.1% reflects consistent returns from branded nut processing and distribution.", "Strong retail shelf presence in the growing healthy snacking category.", "Consistent demand from retail, foodservice and industrial nut ingredient customers."]),
    422: ('Kendrion NV', 'Dutch electromagnetic technology. Recovery momentum.', 'Electromagnetic technology specialist.', "Kendrion is a Dutch manufacturer of electromagnetic components — solenoids, brakes, clutches, and actuators for automotive and industrial applications. The company is recovering from a difficult period as automotive production normalises and its industrial automation business grows.", 'Electromagnetic components. Recovery momentum.', 'Industrial automation recovery.', "A Dutch electromagnetic component manufacturer with a 9.6% ROIC and EPS growth of 24.6% annualised showing recovery momentum. Kendrion solenoids and electromagnetic brakes are essential components in automotive systems and industrial automation equipment.", ["Solenoids, brakes, clutches and actuators for automotive and industrial applications.", "ROIC of 9.6% recovering as automotive production normalises and industrial demand grows.", "EPS grew 24.6% annualised as the business recovers from supply chain disruptions.", "Industrial automation growth providing new revenue streams beyond automotive."]),
    423: ('KWS SAAT SE & Co KGaA', 'German seed technology. Consistent compounder.', 'Agricultural seed innovator.', "KWS SAAT is a German family-controlled agricultural seed company producing corn, sugarbeet, cereal, and oilseed varieties for farmers globally. The company invests heavily in plant breeding and biotechnology — developing higher-yielding, disease-resistant crop varieties that command premium prices.", 'Agricultural seeds. Quality compounder.', 'Seed technology compounder.', "A German agricultural seed company with a 10.8% ROIC and EPS growth of 11.5% annualised. KWS develops and sells premium crop seeds for corn, sugarbeet, and cereals globally — benefiting from structural demand for higher-yielding varieties as farmers seek to maximise productivity per hectare.", ["Premium agricultural seeds for corn, sugarbeet, cereals and oilseeds globally.", "Heavy investment in plant breeding and biotechnology — proprietary high-yield variety pipeline.", "ROIC of 10.8% reflects consistent returns from patented seed varieties with premium pricing.", "EPS grew 11.5% annualised as global demand for high-performance crop seeds expanded."]),
    424: ('L3Harris Technologies Inc', 'US defence electronics giant. Quality compounder.', 'US defence electronics.', "L3Harris Technologies is a major US defence electronics company providing communication systems, electronic warfare, space sensors, and mission-critical networks for the US military and allied forces. The company was formed from the 2019 merger of L3 Technologies and Harris Corporation.", 'US defence electronics. Quality compounder.', 'Defence electronics compounder.', "A major US defence electronics company with a 4.9% ROIC and EPS growth of 10.3% annualised providing communication systems and electronic warfare to the US military. L3Harris benefits from sustained US and NATO defence spending increases and rising demand for advanced electronic warfare capabilities.", ["Communication systems, electronic warfare and space sensors for US military and allies.", "EPS grew 10.3% annualised as defence spending and programme wins accelerated.", "Revenue growing 2.5% annualised with a large defence contract backlog providing visibility.", "Structural tailwind from NATO alliance defence spending commitments."]),
    425: ('Limes Schlosskliniken AG', 'German premium health resort clinics. High growth.', 'German premium health clinics.', "Limes Schlosskliniken operates a network of premium preventive health and rehabilitation clinics in Germany. The company serves affluent clients seeking medically supervised preventive healthcare, stress treatment, and executive health programmes in luxury castle hotel settings.", 'Premium health clinics. High growth.', 'Preventive healthcare compounder.', "A German premium preventive health clinic operator with a 17.5% ROIC and EPS growth of 53.8% annualised. Limes operates luxury health resorts in castle hotels targeting affluent executives seeking medically supervised preventive healthcare — a growing niche as wealthy consumers invest in preventive medicine.", ["Premium preventive health and rehabilitation clinics in luxury German castle hotel settings.", "ROIC of 17.5% reflects strong pricing power in premium medical wellness services.", "EPS grew 53.8% annualised as demand for executive preventive healthcare expanded rapidly.", "Growing niche as affluent consumers increasingly invest in preventive medicine and wellbeing."]),
    426: ('Liquidity Services Inc', 'US surplus asset marketplace. High ROIC.', 'Surplus asset marketplace.', "Liquidity Services operates online marketplaces for surplus and salvage assets — government surplus, retail returns, and industrial equipment. The company connects sellers of unwanted assets with buyers globally through its AllSurplus and GovPlanet platforms.", 'Surplus marketplace. High ROIC momentum.', 'Asset marketplace compounder.', "A US surplus asset marketplace with a 66.9% ROIC connecting sellers of government surplus, retail returns, and industrial equipment with global buyers. Liquidity Services asset-light marketplace model generates exceptional returns with minimal capital requirements.", ["Online marketplaces for government surplus, retail returns and industrial equipment.", "ROIC of 66.9% — exceptional returns from an asset-light marketplace model.", "Revenue growing 14.8% annualised as surplus asset volumes and marketplace adoption expanded.", "Asset-light model with network effects — more sellers attract more buyers and vice versa."]),
}

with open(CARDS_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

updated = 0
for card_id, (company, tag, tagBold, tagFull, pick, pickBold, pickFull, bullets) in descriptions.items():
    pattern = re.compile(
        rf"(id: {card_id}, type: 'JACK'.*?tag: ')[^']*('.*?tagBold: ')[^']*('.*?tagFull: \")[^\"]*(\",.*?pick: ')[^']*('.*?pickBold: ')[^']*('.*?pickFull: \")[^\"]*(\",)",
        re.DOTALL
    )
    replacement = rf"\g<1>{tag}\g<2>{tagBold}\g<3>{tagFull}\g<4>{pick}\g<5>{pickBold}\g<6>{pickFull}\g<7>"
    new_content = pattern.sub(replacement, content)
    if new_content != content:
        content = new_content
        updated += 1
        print(f"✅ {card_id}: {company}")
    else:
        print(f"❌ {card_id}: pattern not matched")
    bullets_str = ', '.join([f'"{b}"' for b in bullets])
    bullets_pattern = re.compile(rf"(id: {card_id},.*?bullets: \[)[^\]]*\]", re.DOTALL)
    content = bullets_pattern.sub(rf"\g<1>{bullets_str}]", content)

with open(CARDS_PATH, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n✅ Updated {updated}/20 JACK cards")
print(f"Remaining generic: {content.count('operates in')}")
