import re

CARDS_PATH = '/Users/radekmajewski/Downloads/valujack/public/cards.js'

descriptions = {
    386: ('Acomo NV', 'Dutch spice and food ingredients trader.', 'Specialty food ingredients.', "Acomo is a Dutch trader and distributor of specialty food ingredients — spices, nuts, seeds, and tea — sourced globally and sold to food manufacturers across Europe. The company has built a diversified portfolio of specialty ingredient businesses with strong market positions.", 'Specialty ingredients. Consistent compounder.', 'Food ingredients compounder.', "A Dutch specialty food ingredients trader with a 12.7% ROIC and EPS growth of 17.9% annualised. Acomo sources spices, nuts, and specialty ingredients globally and distributes to European food manufacturers — a niche with strong relationships and consistent recurring demand.", ["Dutch trader of spices, nuts, seeds and tea for European food manufacturers.", "ROIC of 12.7% reflects consistent returns from a diversified specialty ingredients portfolio.", "EPS grew 17.9% annualised with steady demand from food industry customers.", "Well-established supplier relationships across global spice and specialty ingredient markets."]),
    387: ('ACT Energy Technologies Ltd', 'Canadian oilfield tubular services. Recovery play.', 'Oilfield services recovery.', "ACT Energy Technologies provides tubular running services and equipment rental to the Canadian oil and gas industry. The company operates in the Western Canadian Sedimentary Basin and benefits from rising Canadian energy investment as oilsands and tight oil activity expands.", 'Canadian oilfield services. Recovery momentum.', 'Energy services recovery.', "A Canadian oilfield tubular services company with a 5.2% ROIC recovering from a low base in the Western Canadian energy sector. ACT Energy benefits from rising Canadian energy investment and tight oil activity expansion, with revenue growing 9.8% annualised.", ["Tubular running services and equipment rental for Canadian oil and gas producers.", "Operations in the Western Canadian Sedimentary Basin — core Canadian energy geography.", "Revenue grew 9.8% annualised as Canadian energy investment activity expanded.", "Recovery play with improving margins as oilfield services pricing strengthens."]),
    388: ('American Public Education Inc', 'US online military education. Government-backed demand.', 'Military online education.', "American Public Education operates online universities primarily serving US military personnel, veterans, and public service workers. The flagship American Military University is the largest provider of online education to the US military — a captive, government-supported student base.", 'Military education. Government-backed demand.', 'Defence education compounder.', "A US online university specialising in military and public service education with an 11.6% ROIC. American Public Education serves US military personnel and veterans through American Military University — a captive student base supported by military tuition assistance programmes.", ["American Military University — largest online education provider to the US military.", "Captive student base supported by military tuition assistance and veterans benefits.", "ROIC of 11.6% reflects improving operational efficiency following restructuring.", "Revenue growing steadily as military and veteran education demand expands."]),
    389: ('Applied Materials Inc', 'US semiconductor equipment giant. High ROIC.', 'Chip equipment leader.', "Applied Materials is the world's largest semiconductor equipment company, providing the deposition, etching, and inspection systems used to manufacture chips at every major foundry globally. The company sits at the heart of the global semiconductor supply chain — every advanced chip requires Applied Materials equipment.", 'Semiconductor equipment. Essential infrastructure.', 'Chip equipment monopoly.', "The world's largest semiconductor equipment company with a 36.7% ROIC and EPS growth of 8.7% annualised. Applied Materials equipment is used at every major semiconductor foundry — TSMC, Samsung, Intel — making it indispensable to the global chip manufacturing supply chain.", ["World's largest semiconductor equipment company — deposition, etching and inspection systems.", "Equipment used at every major foundry globally — TSMC, Samsung, Intel and all others.", "ROIC of 36.7% reflects dominant market position and pricing power in equipment supply.", "EPS grew 8.7% annualised with structural demand from AI chip capacity expansion."]),
    390: ('Atria', 'Finnish meat processor. Nordic staple.', 'Nordic food producer.', "Atria is a Finnish meat processing and food company operating across Finland, Sweden, Denmark, and Russia. The company produces branded meat products, convenience foods, and foodservice items for retail and professional customers across the Nordic region.", 'Nordic meat producer. Defensive income.', 'Nordic food compounder.', "A Finnish meat processor with a 5.7% ROIC operating across the Nordic region. Atria produces branded meat and convenience foods for Nordic retail and foodservice — a defensive, structurally stable business with consistent demand from an established regional customer base.", ["Branded meat products and convenience foods for Nordic retail and foodservice.", "Operations across Finland, Sweden, Denmark and Russia — diversified Nordic exposure.", "Defensive food business with consistent demand from established retail relationships.", "EPS growing steadily as Nordic food consumption remains structurally stable."]),
    391: ('Biosyent Inc', 'Canadian specialty pharma. Exceptional ROIC.', 'Canadian specialty pharma.', "Biosyent is a Canadian specialty pharmaceutical company focused on niche prescription drugs and healthcare products in Canada. The company licenses and distributes specialty drugs that address underserved medical needs — a capital-light model generating exceptional returns on invested capital.", 'Specialty pharma. Exceptional returns.', 'Niche pharma compounder.', "A Canadian specialty pharmaceutical company with a 66.4% ROIC and EPS growth of 22.3% annualised. Biosyent licenses and distributes niche specialty drugs in Canada — an asset-light model that generates extraordinary capital efficiency from a small but highly profitable drug portfolio.", ["Canadian specialty pharmaceutical distributor of niche prescription drugs.", "ROIC of 66.4% — extraordinary capital efficiency from an asset-light licensing model.", "EPS grew 22.3% annualised with consistent demand from niche drug portfolio.", "Revenue grew 22.9% annualised reflecting successful drug launches and market expansion."]),
    392: ('BK Technologies Corp', 'US public safety radio manufacturer. High ROIC.', 'Public safety communications.', "BK Technologies manufactures mission-critical communication devices for public safety agencies — police, fire, and emergency medical services across the United States. The company produces portable and mobile radios that meet rigorous government certification standards.", 'Public safety comms. High ROIC.', 'Mission-critical communications.', "A US manufacturer of public safety communication devices with a 46.1% ROIC and EPS growth of 105.8% from a low base. BK Technologies serves police, fire, and EMS agencies with mission-critical radios — a government-certified niche with long procurement cycles and recurring replacement demand.", ["Mission-critical portable and mobile radios for US public safety agencies.", "ROIC of 46.1% reflects strong pricing power in government-certified communications equipment.", "EPS grew 105.8% annualised as public safety radio demand and margins recovered strongly.", "Long government procurement cycles create revenue visibility and recurring replacement demand."]),
    393: ('Bloomsbury Publishing PLC', 'UK publisher. Momentum in academic and digital.', 'UK publishing momentum.', "Bloomsbury Publishing is the UK publisher behind the Harry Potter series, academic publishing, and a growing digital content business. The company has delivered consistent earnings growth from its diversified publishing portfolio and is accelerating its digital and academic revenue streams.", 'Publishing momentum. Quality compounder.', 'Intellectual property momentum.', "A UK publishing company with a 10.2% ROIC and EPS growth of 10.3% annualised showing strong momentum in academic and digital publishing. Bloomsbury's Harry Potter backlist provides evergreen revenue while its academic division generates high-margin subscription income with growing digital penetration.", ["Publisher of the Harry Potter series — evergreen backlist with consistent royalty income.", "Academic publishing division with growing high-margin digital subscription revenue.", "ROIC of 10.2% with improving trajectory as digital revenue mix increases.", "EPS grew 10.3% annualised with accelerating momentum in academic and digital segments."]),
    394: ('Boston Pizza Royalties Income', 'Canadian pizza royalty. Post-COVID momentum.', 'Pizza royalty momentum.', "Boston Pizza Royalties Income Fund collects royalties on all Boston Pizza restaurant sales across Canada. Post-COVID dining recovery has driven strong system sales growth — the royalty model captures all revenue upside with zero restaurant operating risk.", 'Pure royalty. Post-COVID momentum.', 'Royalty income momentum.', "A Canadian pizza royalty trust with a 12.3% ROIC showing strong post-COVID recovery momentum. The fund collects royalties on Boston Pizza system sales regardless of individual restaurant profitability — EPS grew 35.1% annualised as dining recovered across Canada.", ["Pure royalty trust on all Boston Pizza Canada system sales — zero restaurant operating risk.", "ROIC of 12.3% from a pure intellectual property and brand royalty model.", "EPS grew 35.1% annualised as post-COVID dining recovery boosted system sales strongly.", "Revenue growing 4.8% annualised as the Canadian casual dining market continues to recover."]),
    395: ('Cembre SpA', 'Italian electrical connectors. Grid investment momentum.', 'Electrical connector momentum.', "Cembre is an Italian manufacturer of electrical connectors and cable accessories for utilities, railways, and industrial customers. The company is benefiting from accelerating investment in European electrical grid infrastructure and railway electrification.", 'Grid investment momentum. High ROIC.', 'European infrastructure momentum.', "An Italian electrical connector manufacturer with a 20.6% ROIC and EPS growth of 19.6% annualised. Cembre is a direct beneficiary of European grid infrastructure investment and railway electrification — its safety-critical connectors are specified into every major infrastructure upgrade.", ["Safety-critical electrical connectors for utilities, railways and industrial applications.", "ROIC of 20.6% with accelerating momentum from European infrastructure investment.", "EPS grew 19.6% annualised driven by grid upgrade and railway electrification demand.", "Revenue growing 6.3% annualised as European electrical infrastructure spending accelerates."]),
    396: ('CES Energy Solutions Corp', 'Canadian oilfield chemicals. High ROIC momentum.', 'Oilfield chemistry specialist.', "CES Energy Solutions is a Canadian provider of specialty chemical systems for oil and gas production — drilling fluids, production chemicals, and completion systems. The company serves producers across the Western Canadian Sedimentary Basin and the US Permian Basin.", 'Oilfield chemicals. High ROIC momentum.', 'Energy chemistry compounder.', "A Canadian oilfield specialty chemical company with a 16.1% ROIC and EPS growth of 25.3% annualised. CES Energy Solutions provides essential production chemistry to oil and gas producers — a recurring consumable business with high switching costs and consistent reorder demand.", ["Specialty drilling fluids, production chemicals and completion systems for oil and gas.", "Operations in the Western Canadian Sedimentary Basin and US Permian Basin.", "ROIC of 16.1% reflects recurring consumable demand and strong customer relationships.", "EPS grew 25.3% annualised as oilfield activity and chemical pricing strengthened."]),
    397: ('Cheffelo', 'Nordic meal kit leader. Growth momentum.', 'Nordic meal kit growth.', "Cheffelo is a Swedish meal kit delivery company operating across the Nordic region. The company provides weekly recipe boxes with pre-portioned ingredients — targeting time-pressed consumers seeking convenient home-cooked meals. Cheffelo has expanded from Sweden into Norway and Finland.", 'Nordic meal kits. Growth momentum.', 'Nordic food delivery growth.', "A Swedish meal kit company with a 5.0% ROIC showing recovery momentum with EPS growth of 22.5% annualised. Cheffelo operates across Sweden, Norway, and Finland — benefiting from structural growth in convenient home cooking as consumers seek alternatives to restaurant spending.", ["Weekly recipe box delivery across Sweden, Norway and Finland — Nordic market leader.", "EPS grew 22.5% annualised as meal kit adoption and customer retention improved.", "Revenue growing 9.4% annualised with expanding Nordic geographic footprint.", "Structural tailwind from growing consumer preference for convenient home-cooked meals."]),
    398: ('Costain Group PLC', 'UK infrastructure contractor. High ROIC momentum.', 'UK infrastructure contractor.', "Costain is a UK smart infrastructure solutions company delivering complex engineering projects for the transport, water, and energy sectors. The company has transformed from a traditional contractor into a technology-enabled infrastructure delivery partner for major UK government clients.", 'UK infrastructure. High ROIC momentum.', 'Infrastructure delivery compounder.', "A UK infrastructure contractor with a 43.1% ROIC and EPS growth of 18.9% annualised. Costain delivers complex engineering projects for UK Highways England, Network Rail, and water utilities — long-term framework contracts providing multi-year revenue visibility.", ["Smart infrastructure solutions for UK transport, water and energy sectors.", "ROIC of 43.1% — exceptional for an infrastructure contractor, reflecting asset-light delivery model.", "Long-term framework contracts with UK government clients provide multi-year revenue visibility.", "EPS grew 18.9% annualised as UK infrastructure investment accelerated."]),
    399: ('DHT Holdings Inc', 'Norwegian VLCC crude tanker. High yield.', 'VLCC crude tanker operator.', "DHT Holdings is a Norwegian operator of Very Large Crude Carriers — the supertankers that transport crude oil across major long-haul routes. The company operates a fleet of VLCCs serving Middle East to Asia and Middle East to US trade lanes.", 'VLCC tankers. High yield income.', 'Crude tanker income play.', "A Norwegian VLCC crude tanker operator with a 14.6% ROIC. DHT supertankers serve the largest crude oil trade routes globally. The company returns significant cash to shareholders through its dividend policy backed by strong free cash flow generation.", ["Very Large Crude Carrier fleet serving major global crude oil trade routes.", "Middle East to Asia and Middle East to US — the highest-volume crude routes globally.", "ROIC of 14.6% reflects efficient fleet management and disciplined capital allocation.", "Consistent cash returns to shareholders through a generous dividend policy."]),
    400: ('Diploma PLC', 'UK specialty distribution compounder. High earnings growth.', 'Specialty distribution compounder.', "Diploma is a UK specialty distributor of technical products across seals, life sciences, and controls sectors. The company acquires niche distributors of essential technical components and grows them through a decentralised, entrepreneurial operating model.", 'Specialty distribution. Quality compounder.', 'UK distribution compounder.', "A UK specialty distribution company with a 12.9% ROIC and EPS growth of 26.0% annualised. Diploma acquires niche distributors of essential technical components and grows them organically — a proven acquisition-led compounding model delivering consistent double-digit earnings growth.", ["Specialty distribution of seals, life sciences and controls technical components.", "Acquisition-led growth model — acquires niche distributors and compounds them organically.", "ROIC of 12.9% reflects consistent value creation from disciplined acquisitions.", "EPS grew 26.0% annualised — consistent double-digit compounding from the distribution platform."]),
    401: ('Draegerwerk AG & Co KGaA', 'German medical and safety technology. Quality niche.', 'Medical safety technology.', "Draeger is a German manufacturer of medical and safety technology — anaesthesia machines, patient monitoring systems, and gas detection equipment for industrial safety. The company serves hospitals and industrial facilities globally with life-critical equipment.", 'Medical safety technology. Quality niche.', 'Life-critical technology niche.', "A German medical and safety technology manufacturer with a 7.2% ROIC producing anaesthesia machines, patient monitors, and industrial gas detection equipment. Draeger serves hospitals and industrial facilities with life-critical equipment — a niche with high switching costs and recurring service revenue.", ["Anaesthesia machines, patient monitoring and industrial gas detection equipment.", "Life-critical medical and safety applications — high switching costs and regulatory requirements.", "Significant recurring aftermarket service revenue from a large global installed base.", "Long-term hospital and industrial customer relationships built over decades."]),
    402: ('DT Midstream Inc', 'US natural gas pipeline infrastructure. High yield.', 'Gas pipeline infrastructure.', "DT Midstream is a US natural gas pipeline and storage company operating in the Appalachian Basin and Midwest. The company provides gathering, transportation, and storage services to natural gas producers under long-term, fixed-fee contracts.", 'US gas pipeline. Contracted income.', 'Gas infrastructure income.', "A US natural gas midstream company with revenue growth of 26.7% annualised under long-term fixed-fee contracts. DT Midstream pipeline and storage infrastructure serves Appalachian producers with predictable, contracted cash flows independent of commodity prices.", ["Natural gas gathering, transportation and storage in Appalachian Basin and Midwest.", "Long-term fixed-fee contracts provide predictable cash flows independent of gas prices.", "Revenue grew 26.7% annualised as pipeline capacity additions came online.", "Contracted infrastructure model with high barriers to entry from pipeline right-of-way."]),
    403: ('El Pollo Loco Holdings Inc', 'US fire-grilled chicken chain. Loyal following.', 'US Mexican chicken chain.', "El Pollo Loco is a US quick-service restaurant chain specialising in citrus-marinated fire-grilled chicken and Mexican-inspired dishes. The chain operates primarily in the Western US with a loyal Hispanic-American customer base and a growing delivery and catering business.", 'Fire-grilled chicken. Loyal following.', 'US restaurant growth.', "A US quick-service restaurant chain with a 5.1% ROIC and consistent same-store sales growth. El Pollo Loco fire-grilled chicken concept targets a loyal Hispanic-American demographic with a differentiated menu commanding premium positioning versus traditional fast food.", ["Fire-grilled citrus-marinated chicken — differentiated Mexican-inspired quick-service concept.", "Loyal Hispanic-American customer base with strong repeat visit frequency.", "Growing delivery and catering business adding incremental revenue streams.", "Consistent same-store sales growth from an established Western US restaurant network."]),
    404: ('Element Solutions Inc', 'US electronics specialty chemicals. Growth momentum.', 'Electronics specialty chemicals.', "Element Solutions is a US specialty chemicals company providing advanced plating chemicals, surface treatments, and assembly materials for the electronics industry. The company chemicals are essential inputs for printed circuit boards, semiconductors, and advanced packaging.", 'Electronics chemicals. Growth momentum.', 'Electronics materials compounder.', "A US electronics specialty chemicals company with EPS growth of 8.3% annualised providing essential materials for PCB manufacturing, semiconductor packaging, and electronics assembly. Element Solutions benefits from structural growth in electronics complexity and miniaturisation.", ["Specialty plating chemicals and surface treatments for printed circuit boards and semiconductors.", "Essential materials for advanced electronics packaging and assembly.", "Structural growth from increasing electronics complexity and semiconductor content per device.", "EPS grew 8.3% annualised with consistent demand from global electronics manufacturing."]),
    405: ('ENAV SpA', 'Italian air traffic control monopoly. Aviation recovery.', 'Air traffic recovery momentum.', "ENAV is Italy state-owned air traffic control monopoly, managing all civil aviation in Italian airspace. As European aviation recovers to and beyond pre-COVID levels, ENAV revenue grows proportionally with airspace movements.", 'Air traffic recovery. Monopoly income.', 'Aviation recovery momentum.', "Italy air traffic control monopoly with a 6.7% ROIC showing strong recovery momentum as European aviation activity recovers. ENAV revenue is directly linked to Italian airspace movements — a structurally recovering market with regulated returns and growing international traffic.", ["Italy sole air traffic control provider — regulated monopoly over all civil aviation.", "Revenue directly linked to Italian airspace movements — recovering strongly post-COVID.", "Regulated concession provides predictable returns and earnings visibility.", "EPS grew 14.7% annualised as European aviation activity recovered toward pre-COVID levels."]),
}

with open(CARDS_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

updated = 0
for card_id, (company, tag, tagBold, tagFull, pick, pickBold, pickFull, bullets) in descriptions.items():
    pattern = re.compile(
        rf"(id: {card_id}, type: 'JACK'.*?tag: ')[^']*('.*?tagBold: ')[^']*('.*?tagFull: \")[^\"]*(\",.*?pick: ')[^']*('.*?pickBold: ')[^']*('.*?pickFull: \")[^\"]*(\",)",
        re.DOTALL
    )
    replacement = rf"\g<1>{tag}\g<2>{tagBold}\g<3>{tagFull}\g<4>{pick}\g<5>{pickBold}\g<6>{pickFull}\g<7>"
    new_content = pattern.sub(replacement, content)
    if new_content != content:
        content = new_content
        updated += 1
        print(f"✅ {card_id}: {company}")
    else:
        print(f"❌ {card_id}: pattern not matched")
    bullets_str = ', '.join([f'"{b}"' for b in bullets])
    bullets_pattern = re.compile(rf"(id: {card_id},.*?bullets: \[)[^\]]*\]", re.DOTALL)
    content = bullets_pattern.sub(rf"\g<1>{bullets_str}]", content)

with open(CARDS_PATH, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n✅ Updated {updated}/20 JACK cards")
print(f"Remaining generic: {content.count('operates in')}")
