import re

CARDS_PATH = '/Users/radekmajewski/Downloads/valujack/public/cards.js'

descriptions = {
    427: ('Lisi SA', 'French aerospace and automotive fasteners. Quality compounder.', 'Aerospace fastener specialist.', "Lisi is a French manufacturer of high-performance fasteners and assembly components for aerospace, automotive, and medical applications. The company produces titanium and specialty alloy fasteners for Airbus, Boeing, and major automotive OEMs — safety-critical components with stringent certification requirements.", 'Aerospace fasteners. Quality compounder.', 'Aerospace components compounder.', "A French aerospace and automotive fastener manufacturer with a 10.4% ROIC and EPS growth of 31.6% annualised. Lisi produces titanium and specialty fasteners for Airbus and Boeing — safety-critical components with long qualification cycles and high switching costs.", ["High-performance fasteners for aerospace, automotive and medical applications.", "Titanium and specialty alloy fasteners for Airbus, Boeing and major automotive OEMs.", "EPS grew 31.6% annualised as aerospace production rates and fastener demand recovered.", "Safety-critical certification requirements create high barriers and long customer relationships."]),
    428: ('Masterflex SE', 'German specialty hose manufacturer. High growth.', 'Specialty hose technology.', "Masterflex is a German manufacturer of high-performance specialty hoses and connectors for medical, pharmaceutical, food processing, and industrial applications. The company produces hoses that must meet exacting purity and performance standards — commanding premium pricing in regulated markets.", 'Specialty hoses. High growth momentum.', 'Specialty hose compounder.', "A German specialty hose manufacturer with a 12.0% ROIC and EPS growth of 63.3% annualised from a low base. Masterflex produces premium hoses for pharmaceutical, medical, and food processing applications — regulated markets with strict purity requirements and high switching costs.", ["Specialty hoses for pharmaceutical, medical, food processing and industrial applications.", "ROIC of 12.0% with improving trajectory as margins recover from restructuring.", "EPS grew 63.3% annualised as medical and pharma demand for specialty hoses accelerated.", "Premium pricing in regulated markets where purity and performance standards are non-negotiable."]),
    429: ('National Energy Services Reunited', 'US Middle East oilfield services. Growth momentum.', 'Middle East oilfield services.', "National Energy Services Reunited provides oilfield services across the Middle East and North Africa — production testing, cementing, coiled tubing, and drilling fluids. The company is one of the largest independent oilfield services providers in the MENA region.", 'MENA oilfield services. Growth momentum.', 'Middle East energy services.', "A US-listed Middle East oilfield services company with a 4.6% ROIC providing production and drilling services across the MENA region. NESR benefits from sustained high Middle East oil production investment as OPEC nations expand capacity.", ["Oilfield services across Middle East and North Africa — cementing, testing and coiled tubing.", "One of the largest independent oilfield services providers in the MENA region.", "EPS grew 22.3% annualised as Middle East drilling and production activity expanded.", "Revenue growing 1.7% annualised with a large regional contract backlog."]),
    430: ('Navigator Holdings Ltd', 'Marshall Islands LPG tanker operator. High growth.', 'LPG tanker operator.', "Navigator Holdings operates a fleet of liquefied petroleum gas and petrochemical tankers serving global LPG and ethylene trade routes. The company owns one of the largest fleets of handysize gas carriers globally — benefiting from growing LPG export volumes from the US Gulf Coast.", 'LPG tankers. Strong growth momentum.', 'LPG tanker growth play.', "A Marshall Islands LPG tanker operator with EPS growth of 172.8% from a low base as LPG trade volumes recovered. Navigator Holdings fleet of handysize gas carriers serves global LPG and ethylene trade — benefiting from surging US LPG export volumes.", ["Handysize LPG and petrochemical tanker fleet serving global gas trade routes.", "EPS grew 172.8% annualised as LPG trade volumes and tanker rates recovered strongly.", "Benefiting from surging US Gulf Coast LPG export volumes to Asian markets.", "Revenue growing 3.6% annualised with improving fleet utilisation and rate environment."]),
    431: ('New York Times Co', 'US digital media subscription compounder. High ROIC.', 'Digital news subscription leader.', "The New York Times has successfully transformed from a print newspaper into a digital subscription business with over 10 million subscribers. The company generates high-margin recurring revenue from its news, cooking, games, and audio content — building a diversified digital media bundle.", 'Digital subscriptions. Quality compounder.', 'Digital media compounder.', "The New York Times with a 20.4% ROIC and EPS growth of 28.6% annualised, successfully transformed into a digital subscription business with 10+ million subscribers. The NYT bundle — news, cooking, Wordle, The Athletic — creates high-margin recurring revenue with growing switching costs.", ["New York Times digital subscription bundle — news, cooking, games and The Athletic.", "ROIC of 20.4% reflects exceptional digital subscription economics and content moat.", "EPS grew 28.6% annualised as digital subscriber growth and bundle pricing accelerated.", "Revenue grew 9.2% annualised with consistent digital subscription additions."]),
    432: ('Noram Drilling', 'Norwegian oil drilling contractor. Niche recovery.', 'Norwegian drilling contractor.', "Noram Drilling is a Norwegian drilling contractor providing land drilling services to the Norwegian oil and gas industry, including operations on the Norwegian Continental Shelf. The company serves Equinor and other Norwegian energy producers with specialised onshore drilling equipment.", 'Norwegian drilling. Recovery play.', 'Norwegian drilling recovery.', "A Norwegian land drilling contractor with a 10.8% ROIC and EPS growth of 19.2% annualised serving Norwegian oil and gas producers. Noram benefits from sustained Norwegian Continental Shelf development activity as Equinor and partners expand domestic production.", ["Land drilling services for Norwegian oil and gas producers including Equinor.", "ROIC of 10.8% reflects consistent returns from Norwegian Continental Shelf drilling activity.", "EPS grew 19.2% annualised as Norwegian energy investment and drilling demand expanded.", "Niche Norwegian drilling market with limited competition and long-term operator relationships."]),
    433: ('nVent Electric PLC', 'US electrical enclosures and thermal management. High growth.', 'Electrical protection systems.', "nVent Electric manufactures electrical enclosures, cable management, and thermal management solutions for industrial, data centre, and commercial applications. The company benefits from structural growth in data centre construction and industrial electrification.", 'Electrical protection. High growth momentum.', 'Electrification infrastructure play.', "A US electrical enclosures and thermal management company with a 12.7% ROIC and EPS growth of 62.7% annualised. nVent benefits from structural data centre construction growth and industrial electrification — its cable management and thermal solutions are essential infrastructure components.", ["Electrical enclosures, cable management and thermal solutions for data centres and industrial.", "ROIC of 12.7% with improving trajectory from data centre and electrification demand.", "EPS grew 62.7% annualised as data centre construction and industrial electrification accelerated.", "Revenue grew 29.5% annualised driven by structural data centre infrastructure investment."]),
    434: ('Okeanis Eco Tankers', 'Norwegian eco-tanker operator. High yield.', 'Eco crude tanker operator.', "Okeanis Eco Tankers is a Norwegian crude oil tanker company operating a modern fleet of eco-design VLCCs and Suezmaxes. The company fleet is among the most fuel-efficient in the crude tanker market — providing a competitive cost advantage as emissions regulations tighten.", 'Eco tankers. High yield income.', 'Eco crude tanker income.', "A Norwegian crude tanker company with a 12.1% ROIC operating a modern fleet of eco-design VLCCs and Suezmaxes. Okeanis Eco Tankers fuel-efficient fleet provides a cost and emissions advantage as environmental regulations tighten across the global shipping industry.", ["Modern eco-design VLCC and Suezmax fleet — among the most fuel-efficient crude tankers.", "ROIC of 12.1% reflects efficient fleet management and competitive fuel cost advantage.", "Fuel efficiency advantage becomes more valuable as emissions regulations tighten.", "Consistent cash returns through dividend policy from strong tanker market cash generation."]),
    435: ('Perdoceo Education Corp', 'US online for-profit education. High ROIC.', 'US online career education.', "Perdoceo Education operates Colorado Technical University and American InterContinental University — online for-profit universities serving working adults seeking career-focused degree programmes in technology, business, and healthcare.", 'Career education. High ROIC compounder.', 'Career education compounder.', "A US online career education company with a 32.8% ROIC and revenue growth of 24.2% annualised. Perdoceo operates Colorado Technical University and American InterContinental University — serving working adults with career-focused technology and business degrees.", ["Colorado Technical University and American InterContinental University — online career focus.", "ROIC of 32.8% — exceptional returns from an asset-light online education model.", "Revenue grew 24.2% annualised as working adult online education demand expanded.", "EPS grew 6.7% annualised with improving margins from online education operating leverage."]),
    436: ('Perma-Pipe International Holdings', 'US insulated piping systems. High growth.', 'Insulated piping systems.', "Perma-Pipe International manufactures pre-insulated piping systems for district energy, oil and gas, and industrial applications. The company products are used in district heating and cooling networks, pipeline heat tracing, and industrial fluid transport — benefiting from growing district energy infrastructure investment.", 'Insulated piping. High growth momentum.', 'District energy infrastructure.', "A US insulated piping manufacturer with a 13.4% ROIC and EPS growth of 30.9% annualised. Perma-Pipe systems are used in district heating and cooling networks and industrial pipelines — benefiting from growing investment in energy-efficient district energy infrastructure.", ["Pre-insulated piping for district energy, oil and gas and industrial applications.", "ROIC of 13.4% reflects consistent returns from specialised insulated piping systems.", "EPS grew 30.9% annualised as district energy infrastructure investment accelerated.", "Revenue grew 30.7% annualised driven by district heating and industrial piping demand."]),
    437: ('PharmaNutra SpA', 'Italian nutraceutical supplements. High ROIC.', 'Italian nutraceutical innovator.', "PharmaNutra is an Italian company specialising in nutraceutical supplements — particularly iron and mineral supplements using proprietary absorption technology. The company Sucrosomial technology platform enables superior mineral bioavailability, commanding premium pricing in the pharmaceutical supplement market.", 'Nutraceutical innovation. High ROIC.', 'Supplement technology compounder.', "An Italian nutraceutical company with a 31.5% ROIC and EPS growth of 7.6% annualised. PharmaNutra Sucrosomial technology enables superior mineral absorption — a patented platform generating premium pricing from pharmaceutical-grade supplement customers.", ["Proprietary Sucrosomial mineral supplement technology for superior bioavailability.", "ROIC of 31.5% reflects strong intellectual property economics from patented absorption technology.", "Revenue grew 13.8% annualised as Sucrosomial technology adoption expanded across markets.", "Premium pricing from pharmaceutical-grade supplement positioning in regulated markets."]),
    438: ('Photronics Inc', 'US semiconductor photomask manufacturer. Quality niche.', 'Semiconductor photomask specialist.', "Photronics manufactures photomasks — the quartz plates used to transfer circuit patterns onto semiconductor wafers during chip manufacturing. The company is one of only three global suppliers of leading-edge photomasks, serving TSMC, Samsung, and other major foundries.", 'Semiconductor photomasks. Quality niche.', 'Chip manufacturing enabler.', "A US semiconductor photomask manufacturer with a 12.9% ROIC and EPS growth of 21.1% annualised. Photronics is one of only three global suppliers of leading-edge photomasks — an oligopolistic niche supplying TSMC, Samsung, and other advanced foundries with essential chip manufacturing tools.", ["Photomasks for semiconductor wafer patterning — supplied to TSMC, Samsung and leading foundries.", "One of only three global suppliers of leading-edge photomasks — oligopolistic niche.", "ROIC of 12.9% reflects consistent returns from a highly specialised manufacturing niche.", "EPS grew 21.1% annualised with structural demand from advanced semiconductor node transitions."]),
    439: ('PHX Energy Services Corp', 'Canadian directional drilling services. High ROIC.', 'Directional drilling specialist.', "PHX Energy Services is a Canadian directional drilling services company providing measurement-while-drilling and rotary steerable technology to oil and gas producers in Canada and the US. The company technology improves drilling precision and reduces well costs for producers.", 'Directional drilling. High ROIC.', 'Drilling technology compounder.', "A Canadian directional drilling technology company with a 19.0% ROIC and EPS growth of 58.7% annualised. PHX Energy Services measurement-while-drilling technology helps producers drill more precisely — reducing well costs and improving production rates from complex horizontal wells.", ["Directional drilling and measurement-while-drilling technology for oil and gas producers.", "ROIC of 19.0% reflects high value-add from drilling precision technology.", "EPS grew 58.7% annualised as Canadian and US drilling activity and technology adoption grew.", "Revenue grew 7.6% annualised with consistent demand from horizontal well drilling programmes."]),
    440: ('Plexus Corp', 'US electronics manufacturing services. Consistent compounder.', 'Electronics manufacturing services.', "Plexus is a US electronics manufacturing services company specialising in complex, high-reliability products for healthcare, defence, and industrial markets. The company designs, manufactures, and sustains electronics for customers who require rigorous quality and regulatory compliance.", 'Complex electronics manufacturing. Quality niche.', 'Regulated electronics compounder.', "A US electronics manufacturing services company with a 12.7% ROIC and EPS growth of 6.2% annualised serving healthcare, defence, and industrial customers requiring high-reliability electronics. Plexus focus on complex, regulated end markets creates sticky customer relationships.", ["Complex electronics manufacturing for healthcare, defence and industrial applications.", "ROIC of 12.7% reflects consistent returns from high-reliability electronics manufacturing.", "Regulatory compliance expertise creates high barriers to switching manufacturing partners.", "EPS grew 6.2% annualised with consistent demand from regulated end market customers."]),
    441: ('Powell Industries Inc', 'US electrical switchgear manufacturer. Exceptional growth.', 'Electrical switchgear specialist.', "Powell Industries manufactures custom electrical switchgear and motor control centres for oil and gas, petrochemical, and utility industries. The company products are safety-critical infrastructure components for industrial facilities — benefiting from massive US LNG and petrochemical plant investment.", 'Electrical switchgear. Exceptional momentum.', 'Industrial switchgear momentum.', "A US electrical switchgear manufacturer with a 97.6% ROIC and EPS growth of 214.9% annualised from a low base. Powell Industries custom switchgear is essential for US LNG terminals and petrochemical plants — experiencing extraordinary demand as US energy infrastructure investment accelerates.", ["Custom electrical switchgear for oil and gas, petrochemical and utility facilities.", "ROIC of 97.6% — extraordinary returns driven by surging US LNG and petrochemical investment.", "EPS grew 214.9% annualised as US energy infrastructure spending created exceptional demand.", "Safety-critical switchgear with long lead times creates high backlog and revenue visibility."]),
    442: ('Pricesmart Inc', 'US membership warehouse clubs in emerging markets. Consistent compounder.', 'Emerging market warehouse clubs.', "PriceSmart operates membership warehouse clubs across Central America, the Caribbean, and Colombia — bringing the warehouse club model to emerging markets underserved by traditional retail. The company benefits from growing middle-class consumption and strong member loyalty.", 'Emerging market warehouses. Consistent compounder.', 'Emerging market retail compounder.', "A US operator of membership warehouse clubs in Central America, Caribbean, and Colombia with an 11.7% ROIC and EPS growth of 9.0% annualised. PriceSmart brings the Costco-style warehouse model to underserved emerging markets with growing middle-class consumer bases.", ["Membership warehouse clubs across Central America, Caribbean and Colombia.", "ROIC of 11.7% reflects consistent returns from membership fee and retail margin model.", "EPS grew 9.0% annualised with steady middle-class consumer growth in emerging markets.", "Revenue grew 7.8% annualised as new club openings and same-club sales expanded."]),
    443: ('REX American Resources Corp', 'US ethanol producer. High ROIC.', 'US ethanol producer.', "REX American Resources is a US ethanol producer operating plants in the Midwest corn belt. The company benefits from consistent corn ethanol demand from US gasoline blending mandates and has diversified into alternative energy investments.", 'US ethanol. High ROIC compounder.', 'Ethanol production compounder.', "A US ethanol producer with a 23.9% ROIC and EPS growth of 118.7% annualised from improved ethanol margins. REX operates Midwest corn ethanol plants benefiting from consistent US blending mandate demand and improving plant efficiency.", ["Corn ethanol production from Midwest plants serving US gasoline blending mandates.", "ROIC of 23.9% reflects strong ethanol margins from efficient Midwest corn belt operations.", "EPS grew 118.7% annualised as ethanol margins and production efficiency improved.", "Consistent demand from US Renewable Fuel Standard blending requirements."]),
    444: ('Royalty Pharma PLC', 'US pharmaceutical royalty compounder. Consistent income.', 'Pharmaceutical royalty leader.', "Royalty Pharma is the largest buyer of biopharmaceutical royalties globally, owning royalty interests in over 35 marketed therapies including Spinraza, Cystic Fibrosis drugs, and Tysabri. The company earns royalties on drug sales without bearing development or commercial risk.", 'Pharma royalties. Consistent income.', 'Pharmaceutical royalty compounder.', "The world's largest pharmaceutical royalty company with a 4.4% ROIC owning royalties on 35+ marketed drugs including Spinraza and Cystic Fibrosis therapies. Royalty Pharma earns drug revenue without development risk — a pure royalty model with growing income from a diversified drug portfolio.", ["Royalties on 35+ marketed biopharmaceutical therapies including Spinraza and CF drugs.", "World's largest pharma royalty buyer — diversified across therapeutic areas and companies.", "Pure royalty model earns drug revenue without bearing development or commercial risk.", "EPS grew 6.3% annualised as royalty portfolio drugs expanded sales volumes."]),
    445: ('Sandvik', 'Swedish engineering tools and mining equipment. Quality compounder.', 'Engineering tools leader.', "Sandvik is a Swedish global engineering company producing cutting tools, mining equipment, and rock processing machinery. The company is the world leader in cemented carbide cutting tools — essential for metal machining in automotive, aerospace, and general industry.", 'Engineering tools. Quality compounder.', 'Swedish engineering compounder.', "A Swedish global engineering company with an 11.4% ROIC and EPS growth of 11.0% annualised. Sandvik is the world leader in cemented carbide cutting tools — essential for precision metal machining — and a major supplier of underground mining equipment and rock processing systems.", ["World leader in cemented carbide cutting tools for metal machining across industries.", "Mining equipment and rock processing machinery for underground and surface operations.", "ROIC of 11.4% reflects consistent returns from market-leading engineering tool positions.", "EPS grew 11.0% annualised with consistent demand from manufacturing and mining customers."]),
}

with open(CARDS_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

updated = 0
for card_id, (company, tag, tagBold, tagFull, pick, pickBold, pickFull, bullets) in descriptions.items():
    pattern = re.compile(
        rf"(id: {card_id}, type: 'JACK'.*?tag: ')[^']*('.*?tagBold: ')[^']*('.*?tagFull: \")[^\"]*(\",.*?pick: ')[^']*('.*?pickBold: ')[^']*('.*?pickFull: \")[^\"]*(\",)",
        re.DOTALL
    )
    replacement = rf"\g<1>{tag}\g<2>{tagBold}\g<3>{tagFull}\g<4>{pick}\g<5>{pickBold}\g<6>{pickFull}\g<7>"
    new_content = pattern.sub(replacement, content)
    if new_content != content:
        content = new_content
        updated += 1
        print(f"✅ {card_id}: {company}")
    else:
        print(f"❌ {card_id}: pattern not matched")
    bullets_str = ', '.join([f'"{b}"' for b in bullets])
    bullets_pattern = re.compile(rf"(id: {card_id},.*?bullets: \[)[^\]]*\]", re.DOTALL)
    content = bullets_pattern.sub(rf"\g<1>{bullets_str}]", content)

with open(CARDS_PATH, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n✅ Updated {updated}/19 JACK cards")
print(f"Remaining generic: {content.count('operates in')}")
