import re

CARDS_PATH = '/Users/radekmajewski/Downloads/valujack/public/cards.js'

descriptions = {
    319: ('Exxaro Resources Ltd', 'South African coal & minerals. High yield.', 'High dividend yield.', "Exxaro Resources is one of South Africa's largest coal miners, supplying Eskom's power stations with thermal coal while diversifying into minerals and energy transition assets. The business generates substantial free cash flow and returns most of it to shareholders via dividends.", 'High yield. Cheap on earnings.', 'Deep value income.', "A high-yield South African resources company trading at a significant discount to fair value. Coal demand from domestic power generation provides earnings visibility, and the dividend yield of 7.9% reflects a generous payout policy backed by strong free cash flow.", ["South Africa's largest coal supplier to Eskom — captive domestic demand underpins earnings.", "Dividend yield of 7.9% backed by consistent free cash flow generation.", "ROIC of 16.3% demonstrates solid capital efficiency for a resources business.", "Trading below fair value with a low P/E relative to its yield."]),
    320: ('Nippon Yusen Kabushiki Kaisha', 'Japanese shipping giant. High yield.', 'Global shipping leader.', "Nippon Yusen is one of Japan's largest shipping conglomerates, operating container ships, bulk carriers, tankers, and car carriers globally. The group has benefited from elevated freight rates and has dramatically strengthened its balance sheet and dividend capacity.", 'Shipping profits funding a generous yield.', 'Quality income at a discount.', "A diversified Japanese shipping group with a 5.6% dividend yield and strong ROIC of 21.2%. EPS has grown at 21.4% annualised — the market is still pricing this as a cyclical business without crediting the structural improvement in its balance sheet and diversified fleet.", ["One of Japan's three major shipping conglomerates — bulk, container, tanker and car carrier fleets.", "EPS growth of 21.4% annualised over five years — far above the sector average.", "ROIC of 21.2% reflects improved capital discipline since the post-COVID freight boom.", "Dividend yield of 5.6% with strong free cash flow backing."]),
    321: ('Autotrader Group PLC', 'UK automotive marketplace. High ROIC.', 'Digital marketplace monopoly.', "Auto Trader is the UK's dominant online automotive marketplace, connecting car buyers and dealers across the country. The asset-light platform model generates exceptional returns on capital with minimal physical infrastructure — effectively a toll road on UK used car transactions.", 'Dominant marketplace. Exceptional returns.', 'Quality compounder.', "The UK's number one automotive marketplace with a near-monopoly position in online car listings. ROIC of 47.7% and EPS growth of 42.4% reflect the platform's pricing power and operating leverage. A quality compounder trading at a fair entry point.", ["Dominant UK online car marketplace — dealers have no viable alternative platform.", "ROIC of 47.7% — exceptional capital efficiency from an asset-light digital model.", "EPS grew 42.4% annualised over five years, driven by pricing power and volume growth.", "Dividend yield of 2.0% with significant buyback capacity on top."]),
    322: ('Bic', 'French consumer goods. Reliable dividend.', 'Iconic consumer brand.', "BIC is a French consumer goods company best known for disposable pens, lighters, and shavers sold in over 160 countries. The business has iconic brand recognition, stable recurring revenue from consumables, and a consistent dividend history stretching back decades.", 'Iconic brand. Reliable income.', 'Consistent compounder.', "A globally recognised consumer goods brand with a 5.3% dividend yield and over 160 countries of distribution. BIC's disposable products create high-frequency repeat purchases with minimal customer churn. The stock trades below fair value with a low P/E for a business of this quality.", ["Disposable pens, lighters and shavers sold in 160+ countries — recurring consumable demand.", "Dividend yield of 5.3% backed by decades of consistent dividend payments.", "ROIC of 14.1% reflects steady capital returns from a mature, cash-generative business.", "Trading below fair value with a low P/E relative to brand strength and distribution reach."]),
    323: ('Vidrala SA', 'Spanish glass packaging. Steady compounder.', 'Glass packaging leader.', "Vidrala is a leading European glass container manufacturer, producing bottles and jars for the food, beverage, and spirits industries. Glass packaging is a structurally stable business with high barriers to entry — furnaces require hundreds of millions to build and take years to commission.", 'Defensive packaging. Durable cash flow.', 'Industrial compounder.', "A high-quality European glass packaging business with durable cash flows and a growing dividend. Glass containers are a structurally defensive product — food and beverage companies cannot easily switch packaging formats. ROIC of 13.3% reflects consistent capital returns from an asset-intensive but moated business.", ["Leading European glass container manufacturer for food, beverage and spirits — high switching costs.", "Glass furnaces cost hundreds of millions to build — significant barrier to new entrants.", "ROIC of 13.3% is consistent and stable across economic cycles.", "Dividend yield of 1.9% with a long history of dividend growth."]),
    324: ('Jumbo SA', 'Greek toys and stationery retailer. High yield.', 'Greek retail champion.', "Jumbo is Greece's dominant toy, baby products, and seasonal goods retailer, operating large-format stores across Greece, Cyprus, Bulgaria, and Romania. The business has no debt, generates exceptional cash flow, and pays a high dividend — a rare combination in European retail.", 'No debt. High yield. Growing.', 'Retail cash machine.', "A debt-free Greek retailer with a 6.2% dividend yield, 28.4% ROIC, and EPS growth of 18% annualised. Jumbo dominates its niche across southeastern Europe and has consistently grown without taking on debt. A rare quality retail compounder at a fair price.", ["Dominant toy and seasonal goods retailer across Greece, Cyprus, Bulgaria and Romania.", "Zero debt — the business self-funds all expansion from operating cash flow.", "ROIC of 28.4% and EPS growth of 18% annualised — exceptional for a brick-and-mortar retailer.", "Dividend yield of 6.2% backed by strong free cash flow generation."]),
    325: ('Bosideng International Holdings', 'Chinese down apparel. Exceptional ROIC.', 'China apparel leader.', "Bosideng is China's leading down apparel brand, dominating the premium winter jacket market across the country. The company has transformed from a commoditised outerwear producer into a premium lifestyle brand, driving significant margin expansion and return on capital improvement.", 'Premium brand. Exceptional returns.', 'China consumer compounder.', "China's dominant premium down apparel brand with a 61.2% ROIC. Bosideng has successfully repositioned upmarket, expanding margins while growing EPS at 14.6% annualised. The 7.1% dividend yield makes this a rare high-quality income play in emerging markets.", ["China's leading premium down jacket brand — dominant market position in winter outerwear.", "ROIC of 61.2% — exceptional capital efficiency reflecting strong brand pricing power.", "EPS grew 14.6% annualised as brand premiumisation drove margin expansion.", "Dividend yield of 7.1% — unusually high for a quality growth business."]),
    326: ('Grand Pharmaceutical Group Ltd', 'Hong Kong pharma distribution. Steady yield.', 'Healthcare distribution.', "Grand Pharmaceutical is a Hong Kong-listed healthcare group operating pharmaceutical distribution, retail pharmacy chains, and specialty drug manufacturing across Greater China. The business benefits from China's ageing population and growing healthcare expenditure.", 'Healthcare distribution. Defensive yield.', 'Defensive income.', "A diversified Hong Kong healthcare group with exposure to China's growing pharmaceutical distribution and retail pharmacy market. ROIC of 15.1% reflects steady returns from a regulated, defensive sector. The 4.0% dividend yield offers income backed by structural healthcare demand growth.", ["Pharmaceutical distribution and retail pharmacy operations across Greater China.", "Structural tailwind from China's ageing population and rising healthcare expenditure.", "ROIC of 15.1% reflects consistent returns from a regulated defensive business.", "Dividend yield of 4.0% with stable earnings from essential healthcare services."]),
    327: ('ANTA Sports Products Ltd', 'Chinese sportswear giant. High ROIC.', 'China sportswear leader.', "ANTA Sports is China's largest sportswear company by revenue, owning the ANTA, FILA China, and Descente brands. The group has successfully built a multi-brand portfolio targeting different consumer segments, from mass market to premium, and is the official sportswear partner of the Chinese Olympic team.", 'Multi-brand sportswear. Strong growth.', 'China consumer champion.', "China's largest sportswear group with a 35.1% ROIC and EPS growth of 22.7% annualised. ANTA's multi-brand strategy mirrors the playbook of global sportswear leaders. The 2.9% dividend yield is growing alongside strong earnings expansion.", ["China's largest sportswear company — ANTA, FILA China, and Descente brands.", "ROIC of 35.1% reflects strong brand economics and capital-light distribution.", "EPS grew 22.7% annualised over five years — consistent outperformance of the sector.", "Official sportswear partner of the Chinese Olympic Committee — powerful brand endorsement."]),
    328: ('Krka DD', 'Slovenian pharma. High quality. Low profile.', 'European generic pharma.', "Krka is a Slovenian pharmaceutical company specialising in generic drugs, OTC products, and animal health. Operating across Central and Eastern Europe, Russia, and Western Europe, Krka has built a diversified geographic footprint with consistently high margins and returns on capital.", 'Quality pharma. Underappreciated.', 'Hidden European compounder.', "A high-quality Slovenian generic pharmaceutical company with a 19.4% ROIC and a 3.4% dividend yield. Krka operates in structurally growing generic drug markets across Europe and has compounded earnings steadily for over a decade. The stock is largely overlooked by international investors.", ["Leading Slovenian generic pharmaceutical company with operations across 70+ countries.", "ROIC of 19.4% — exceptional for a generic pharma business, reflecting strong operational efficiency.", "EPS grew 7.3% annualised with consistent margins across economic cycles.", "Dividend yield of 3.4% backed by strong free cash flow from a diversified drug portfolio."]),
    329: ('Hexpol', 'Swedish polymer compounder. Reliable yield.', 'Specialty materials compounder.', "Hexpol is a Swedish specialty polymer compounds manufacturer, producing rubber and thermoplastic compounds for the automotive, infrastructure, and industrial sectors. The business operates globally with a highly diversified customer base and consistent free cash flow generation.", 'Specialty materials. Consistent returns.', 'Industrial compounder.', "A Swedish specialty polymer company with a 15.4% ROIC and a 5.2% dividend yield. Hexpol's rubber and thermoplastic compounds are critical inputs for automotive seals, gaskets, and industrial applications — creating sticky customer relationships and recurring revenue.", ["Global leader in specialty rubber and thermoplastic compounds for automotive and industrial use.", "Highly diversified customer base across 80+ countries reduces concentration risk.", "ROIC of 15.4% with consistent free cash flow supporting the 5.2% dividend yield.", "EPS grew 6.6% annualised — steady, not spectacular, but highly reliable."]),
    330: ('Gentex Corp', 'US auto-dimming mirrors. Niche monopoly.', 'Automotive technology monopoly.', "Gentex Corporation holds a near-monopoly in electrochromic auto-dimming rearview mirrors for the global automotive industry. The company supplies virtually every major automaker and has expanded into connected car features including HomeLink garage door integration and full display mirrors.", 'Niche monopoly. Steady compounder.', 'Auto tech monopoly.', "A US automotive technology company with a near-monopoly in auto-dimming mirrors and an 18.7% ROIC. Gentex is embedded in virtually every major automaker's supply chain and generates consistent free cash flow. The 2.7% dividend yield is supported by a long history of dividend growth and buybacks.", ["Near-monopoly in electrochromic auto-dimming mirrors — supplied to virtually all major automakers.", "ROIC of 18.7% reflects the pricing power and switching costs of a deeply embedded supplier.", "EPS grew 4.3% annualised with highly predictable revenue from long-term OEM contracts.", "Dividend yield of 2.7% with consistent dividend growth and significant share buyback programme."]),
    331: ('Aalberts NV', 'Dutch flow control technology. Solid compounder.', 'Industrial flow technology.', "Aalberts is a Dutch industrial technology company specialising in flow control systems, heat emission products, and surface treatment technologies. The group serves the construction, semiconductor, and industrial sectors with mission-critical components that are deeply embedded in customer processes.", 'Industrial technology. Quality at value.', 'Dutch industrial compounder.', "A Dutch industrial technology group with a 3.5% dividend yield and exposure to structural growth in building efficiency and semiconductor manufacturing. ROIC of 8.8% reflects a business in transition — recent acquisitions are diluting returns temporarily.", ["Flow control and heat emission technology for construction, semiconductor and industrial sectors.", "Mission-critical components deeply embedded in customer processes — high switching costs.", "EPS grew 5.3% annualised with a consistent long-term dividend growth track record.", "Dividend yield of 3.5% with exposure to structural semiconductor and building efficiency tailwinds."]),
    332: ('Abbott Laboratories', 'US healthcare giant. Dividend aristocrat.', 'US healthcare stalwart.', "Abbott Laboratories is a diversified US healthcare company operating across medical devices, diagnostics, nutrition, and established pharmaceuticals. Abbott has increased its dividend for over 50 consecutive years, making it a true Dividend King — one of the most exclusive groups in global equity markets.", 'Dividend King. Fifty years of growth.', 'True Dividend King.', "A US Dividend King with over 50 consecutive years of dividend increases and a 14.4% ROIC. Abbott's diversified healthcare portfolio across devices, diagnostics, and nutrition provides resilient earnings through economic cycles.", ["Over 50 consecutive years of dividend increases — a true US Dividend King.", "Diversified across medical devices, diagnostics, nutrition and pharmaceuticals.", "ROIC of 14.4% reflects consistent capital efficiency across a large, complex business.", "EPS grew 8.2% annualised — steady compounding from a resilient healthcare franchise."]),
    333: ('Aubay', 'French IT services. Consistent compounder.', 'French IT services.', "Aubay is a French IT services company providing digital transformation, application development, and technology consulting to financial services, insurance, and energy clients across Europe. The business has grown steadily through a combination of organic growth and bolt-on acquisitions.", 'IT services. Steady growth. Fair price.', 'European IT compounder.', "A French IT services company with a 19.3% ROIC and a 2.7% dividend yield. Aubay's focus on regulated industries — banking, insurance, energy — provides earnings resilience and long-term client relationships.", ["IT consulting and digital transformation services for banks, insurers and energy companies.", "ROIC of 19.3% — high for an IT services business, reflecting asset-light model and pricing power.", "EPS grew 6.7% annualised with consistent margin improvement from scale and specialisation.", "Dividend yield of 2.7% with a track record of steady dividend increases."]),
    334: ('Azbil Corp', 'Japanese industrial automation. High ROIC.', 'Japanese automation leader.', "Azbil Corporation is a Japanese industrial automation and building management systems company, providing measurement, control, and automation solutions to factories, buildings, and laboratories across Asia. The business benefits from Japan's industrial automation push and rising demand for energy-efficient buildings.", 'Japanese automation. Quality compounder.', 'Industrial automation play.', "A Japanese industrial automation company with a 21.4% ROIC and EPS growth of 18.6% annualised. Azbil's building management and factory automation systems are deeply embedded in customer operations, creating recurring maintenance and upgrade revenue.", ["Industrial automation and building management systems for factories and commercial buildings.", "ROIC of 21.4% reflects high value-add automation solutions with long customer relationships.", "EPS grew 18.6% annualised — strong earnings momentum from Japan's automation investment cycle.", "Dividend yield of 1.9% — conservative payout with significant retained earnings for reinvestment."]),
    335: ('Barco NV', 'Belgian visualisation technology. High yield.', 'Visualisation technology leader.', "Barco is a Belgian technology company specialising in professional visualisation solutions — large-scale display systems for control rooms, cinemas, medical imaging, and corporate meeting spaces. The company has a strong global market position in high-value niche display applications.", 'Niche display tech. High yield.', 'Specialty technology income.', "A Belgian professional visualisation company with a 5.2% dividend yield and EPS growth from a low base. Barco's display systems for control rooms, cinemas, and medical imaging serve high-value, mission-critical applications with long replacement cycles.", ["Professional display systems for control rooms, cinemas, medical imaging and enterprise.", "EPS recovering strongly from a restructured base — significant operational improvement underway.", "ROIC of 10.3% improving as restructuring benefits flow through to margins.", "Dividend yield of 5.2% — attractive income while the business recovery matures."]),
    336: ('Bloomsbury Publishing PLC', 'UK book publisher. Harry Potter royalties.', 'UK publishing house.', "Bloomsbury Publishing is the UK publisher behind the Harry Potter series, academic publishing, and a growing digital content business. Beyond its famous franchise, Bloomsbury has built a diversified academic and professional publishing operation generating recurring subscription revenue.", 'Publishing moat. Growing dividend.', 'Intellectual property compounder.', "A UK publishing house with a 14.0% ROIC and EPS growth of 10.3% annualised. Bloomsbury's Harry Potter backlist provides an evergreen revenue stream, while its academic publishing division generates high-margin subscription income.", ["Publisher of the Harry Potter series — evergreen backlist generating recurring royalty income.", "Academic and professional publishing division provides high-margin subscription revenue.", "ROIC of 14.0% reflects strong intellectual property economics and low capital requirements.", "EPS grew 10.3% annualised — consistent compounding from a diversified publishing portfolio."]),
    337: ('Boston Pizza Royalties Income', 'Canadian pizza royalty. High yield.', 'Pizza royalty income.', "Boston Pizza Royalties Income Fund is a Canadian royalty trust that collects royalties on all Boston Pizza restaurant sales across Canada. As a pure royalty vehicle, the fund has minimal capital requirements and distributes virtually all income to unitholders.", 'Pure royalty income. High yield.', 'Canadian royalty income.', "A Canadian pizza restaurant royalty trust with a 6.0% distribution yield and minimal capital requirements. The fund collects royalties on Boston Pizza's Canadian system sales regardless of individual restaurant profitability — a structurally defensive income model.", ["Pure royalty trust collecting fees on all Boston Pizza Canada system sales — asset-light model.", "Distribution yield of 6.0% — virtually all royalty income distributed to unitholders.", "EPS grew strongly as post-COVID dining recovery boosted system sales significantly.", "Minimal capital requirements — the fund owns the brand rights, not the restaurants."]),
    338: ('Cembre SpA', 'Italian electrical connectors. Quality niche.', 'Electrical connector specialist.', "Cembre is an Italian manufacturer of electrical connectors, cable accessories, and railway electrification products. The company serves utilities, railways, and industrial customers across Europe with highly engineered, safety-critical components that require certification and long qualification processes.", 'Niche industrial. Consistent compounder.', 'Italian industrial compounder.', "An Italian manufacturer of safety-critical electrical connectors with a 19.9% ROIC and EPS growth of 19.6% annualised. Cembre's products require lengthy customer qualification processes — creating high switching costs and recurring revenue.", ["Safety-critical electrical connectors for utilities, railways and industrial — lengthy qualification creates moat.", "ROIC of 19.9% — exceptional for an industrial manufacturer, reflecting niche pricing power.", "EPS grew 19.6% annualised — consistent double-digit compounding over five years.", "Dividend yield of 2.5% with a long track record of dividend growth."]),
}

with open(CARDS_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

updated = 0
for card_id, (company, tag, tagBold, tagFull, pick, pickBold, pickFull, bullets) in descriptions.items():
    old_tag = re.search(rf"(id: {card_id},.*?tag: ')(.*?)(' *,)", content, re.DOTALL)
    if not old_tag:
        print(f"❌ ID {card_id} not found")
        continue
    bullets_str = ', '.join([f'"{b}"' for b in bullets])
    pattern = re.compile(
        rf"(id: {card_id}, type: 'KING'.*?tag: ')[^']*('.*?tagBold: ')[^']*('.*?tagFull: \")[^\"]*(\",.*?pick: ')[^']*('.*?pickBold: ')[^']*('.*?pickFull: \")[^\"]*(\",)",
        re.DOTALL
    )
    replacement = rf"\g<1>{tag}\g<2>{tagBold}\g<3>{tagFull}\g<4>{pick}\g<5>{pickBold}\g<6>{pickFull}\g<7>"
    new_content = pattern.sub(replacement, content)
    if new_content != content:
        content = new_content
        updated += 1
        print(f"✅ {card_id}: {company}")
    else:
        print(f"❌ {card_id}: pattern not matched")

    # Fix bullets
    bullets_pattern = re.compile(rf"(id: {card_id},.*?bullets: \[)[^\]]*\]", re.DOTALL)
    content = bullets_pattern.sub(rf"\g<1>{bullets_str}]", content)

with open(CARDS_PATH, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n✅ Updated {updated}/20 KING cards")
print(f"Remaining generic: {content.count('operates in')}")
