import re

CARDS_PATH = '/Users/radekmajewski/Downloads/valujack/public/cards.js'

descriptions = {
    573: ('Miller Industries Inc', 'US towing and recovery equipment. Strong F-Score.', 'Towing equipment F-Score.', "Miller Industries is the world's largest manufacturer of towing and recovery equipment — wreckers, carriers, and rotators used by towing companies globally. The company has strong Piotroski F-Score metrics reflecting consistent financial health from a niche manufacturing business.", 'Towing equipment. Strong F-Score.', 'Towing equipment quality play.', "The world's largest towing and recovery equipment manufacturer with a 10.0% ROIC and strong Piotroski F-Score metrics. Miller Industries serves the global towing industry with wreckers, carriers, and rotators — financially sound niche manufacturer with consistent demand.", ["World's largest manufacturer of towing and recovery equipment globally.", "ROIC of 10.0% reflects consistent returns from a dominant niche manufacturing position.", "Strong Piotroski F-Score reflecting excellent financial health and cash generation.", "Consistent demand from towing companies and municipalities replacing ageing equipment."]),
    574: ('Miquel y Costas & Miquel SA', 'Spanish specialty paper. Strong F-Score.', 'Specialty paper F-Score.', "Miquel y Costas manufactures specialty cigarette and technical papers. The company has strong Piotroski F-Score metrics reflecting consistent profitability and balance sheet health from its niche paper manufacturing business.", 'Specialty paper. Strong F-Score quality.', 'Paper niche quality compounder.', "A Spanish specialty paper manufacturer with a 12.7% ROIC and strong Piotroski F-Score metrics. Miquel y Costas produces cigarette and specialty papers with high barriers to entry — financially sound niche business with excellent balance sheet metrics.", ["Cigarette paper and specialty papers for global tobacco and industrial customers.", "ROIC of 12.7% reflects consistent returns from a niche, defensible paper business.", "Strong Piotroski F-Score reflecting excellent financial health and free cash flow.", "Long-term tobacco supply contracts provide predictable, recurring revenue."]),
    575: ('Movado Group Inc', 'US watch manufacturer. Strong F-Score.', 'Watch brand F-Score.', "Movado Group is a US watch company owning the Movado, EBEL, Concord, and licensed brands including Coach and Tommy Hilfiger watches. The company has strong Piotroski F-Score metrics reflecting consistent financial health from its multi-brand watch portfolio.", 'Watch brands. Strong F-Score quality.', 'Watch brand quality play.', "A US watch manufacturer with a 14.2% ROIC and strong Piotroski F-Score metrics owning Movado, EBEL, and licensed watch brands. Movado Group financially sound multi-brand portfolio generates consistent returns with excellent balance sheet health.", ["Movado, EBEL, Concord and licensed watch brands — diversified watch portfolio.", "ROIC of 14.2% reflects consistent returns from multi-brand watch manufacturing.", "Strong Piotroski F-Score reflecting excellent financial health and cash generation.", "EPS grew 14.2% annualised with consistent watch brand demand and margin management."]),
    576: ('Navigator Holdings Ltd', 'Marshall Islands LPG tanker. Strong F-Score.', 'LPG tanker F-Score.', "Navigator Holdings operates handysize LPG and petrochemical tankers globally. The company has improving Piotroski F-Score metrics reflecting strengthening balance sheet and cash flow from LPG tanker market recovery.", 'LPG tankers. Improving F-Score.', 'LPG tanker quality play.', "A Marshall Islands LPG tanker operator with a 3.2% ROIC and improving Piotroski F-Score metrics. Navigator Holdings LPG fleet serves global propane and ethylene trade — improving financial health from LPG tanker market recovery.", ["Handysize LPG and petrochemical tankers serving global gas trade routes.", "Improving Piotroski F-Score reflecting balance sheet strengthening from tanker recovery.", "EPS grew 172.8% annualised as LPG trade volumes and tanker rates recovered.", "Growing US LPG export volumes providing sustained additional tonne-mile demand."]),
    577: ('Orient Overseas Ltd', 'Hong Kong container shipping. Strong F-Score.', 'Container shipping F-Score.', "Orient Overseas Container Line operates one of the world's top-ten container fleets under the OOCL brand. The company has strong Piotroski F-Score metrics reflecting excellent financial health from exceptional container shipping cash generation.", 'OOCL container shipping. Strong F-Score.', 'Container shipping quality.', "A major container shipping company with an 88.0% ROIC and strong Piotroski F-Score metrics. OOCL one of the world's most efficient container fleets with excellent financial health — strong balance sheet from exceptional cash generation.", ["Top-ten global container shipping company under the OOCL brand.", "ROIC of 88.0% — extraordinary returns from a highly efficient container fleet.", "Strong Piotroski F-Score reflecting excellent financial health and cash generation.", "EPS grew 23.2% annualised as container demand and freight rates remained elevated."]),
    578: ('Pacific Basin Shipping Ltd', 'Hong Kong dry bulk shipping. Strong F-Score.', 'Dry bulk F-Score compounder.', "Pacific Basin Shipping operates Handysize and Supramax dry bulk vessels. The company has strong Piotroski F-Score metrics reflecting consistent financial health from disciplined dry bulk shipping operations.", 'Dry bulk shipping. Strong F-Score.', 'Dry bulk quality compounder.', "A Hong Kong dry bulk shipping company with a 20.5% ROIC and strong Piotroski F-Score metrics. Pacific Basin Handysize and Supramax fleet serves global minor bulk trade — excellent financial health from disciplined fleet management and capital allocation.", ["Handysize and Supramax bulk vessels serving global minor bulk commodity trade.", "ROIC of 20.5% reflects consistent returns from disciplined dry bulk fleet management.", "Strong Piotroski F-Score reflecting excellent balance sheet and cash flow generation.", "EPS grew 17.7% annualised with consistent demand from global agricultural and industrial trade."]),
    579: ('Perdoceo Education Corp', 'US online career education. Strong F-Score.', 'Career education F-Score.', "Perdoceo Education operates Colorado Technical University and American InterContinental University. The company has strong Piotroski F-Score metrics reflecting excellent financial health from scalable online career education operations.", 'Career education. Strong F-Score quality.', 'Online education quality play.', "A US online career education company with a 39.2% ROIC and strong Piotroski F-Score metrics. Perdoceo operates scalable online universities with excellent financial health — strong balance sheet and free cash flow from career-focused education.", ["Colorado Technical University and American InterContinental University.", "ROIC of 39.2% — exceptional returns from an asset-light online education model.", "Strong Piotroski F-Score reflecting excellent financial health and cash generation.", "Revenue grew 24.2% annualised as online career education demand expanded."]),
    580: ('Petrolia', 'Norwegian oil services. Improving F-Score.', 'Norwegian oil services F-Score.', "Petrolia is a Norwegian provider of well services to the oil and gas industry, specialising in well intervention and plugging and abandonment operations. The company has improving Piotroski F-Score metrics reflecting better operational performance and financial management.", 'Norwegian well services. Improving F-Score.', 'Norwegian oil services quality.', "A Norwegian well services company with a 3.5% ROIC and improving Piotroski F-Score metrics. Petrolia provides well intervention and P&A services to Norwegian Continental Shelf operators — improving financial health from recovering North Sea activity.", ["Well intervention and plugging and abandonment services for Norwegian Continental Shelf.", "Improving Piotroski F-Score reflecting better cash generation and balance sheet management.", "EPS grew 35.1% annualised as North Sea well services demand recovered.", "Norwegian Continental Shelf P&A activity providing structural long-term demand."]),
    581: ('Photronics Inc', 'US semiconductor photomasks. Strong F-Score.', 'Photomask F-Score compounder.', "Photronics manufactures photomasks for semiconductor wafer patterning. The company has strong Piotroski F-Score metrics reflecting excellent financial health from its oligopolistic position in advanced semiconductor photomask manufacturing.", 'Semiconductor photomasks. Strong F-Score.', 'Photomask quality compounder.', "A US semiconductor photomask manufacturer with a 13.0% ROIC and strong Piotroski F-Score metrics. Photronics is one of only three global photomask suppliers — excellent financial health from a highly defensible oligopolistic niche.", ["Photomasks for semiconductor wafer patterning — supplied to TSMC, Samsung and foundries.", "ROIC of 13.0% from an oligopolistic niche with only three global suppliers.", "Strong Piotroski F-Score reflecting excellent financial health and free cash flow.", "EPS grew 21.1% annualised with structural demand from advanced semiconductor transitions."]),
    582: ('Prevas', 'Swedish embedded systems consultant. Strong F-Score.', 'Swedish tech consultant F-Score.', "Prevas is a Swedish technology consulting company specialising in embedded systems, product development, and industrial IT. The company serves industrial, medical, and automotive clients with engineering expertise in software and hardware development.", 'Swedish tech consulting. Strong F-Score.', 'Swedish engineering quality play.', "A Swedish embedded systems consultant with a 15.8% ROIC and strong Piotroski F-Score metrics. Prevas provides engineering consulting for industrial and medical clients — financially sound technology consultancy with excellent balance sheet health.", ["Embedded systems and product development consulting for industrial and medical clients.", "ROIC of 15.8% reflects consistent returns from specialist engineering consultancy.", "Strong Piotroski F-Score reflecting excellent financial health and cash generation.", "Consistent demand from Swedish industrial and medical technology development projects."]),
    583: ('Puma Biotechnology Inc', 'US HER2 breast cancer pharma. High ROIC.', 'HER2 breast cancer treatment.', "Puma Biotechnology is a US pharmaceutical company focused on HER2-positive breast cancer treatment. The company's drug Neratinib is approved for early and extended adjuvant treatment of HER2-positive breast cancer — a targeted cancer therapy with a defined patient population.", 'HER2 breast cancer drug. Strong F-Score.', 'Oncology pharmaceutical compounder.', "A US oncology pharmaceutical company with a 49.4% ROIC focused on HER2-positive breast cancer. Puma Biotechnology Neratinib generates consistent prescription revenue from a defined HER2 breast cancer patient population — exceptional capital efficiency from a commercial-stage drug.", ["Neratinib for HER2-positive breast cancer treatment — approved targeted oncology therapy.", "ROIC of 49.4% — exceptional returns from a commercially established oncology drug.", "Strong Piotroski F-Score reflecting improving financial health as commercial revenues grow.", "EPS grew 19.2% annualised with consistent Neratinib prescription growth."]),
    584: ('Scanfil', 'Finnish electronics manufacturing. Strong F-Score.', 'Electronics manufacturing F-Score.', "Scanfil is a Finnish electronics manufacturing services company serving industrial, medtech, and energy technology customers. The company has strong Piotroski F-Score metrics reflecting consistent financial health from quality-certified manufacturing operations.", 'Electronics manufacturing. Strong F-Score.', 'EMS quality compounder.', "A Finnish electronics manufacturing services company with a 13.8% ROIC and strong Piotroski F-Score metrics. Scanfil serves regulated industrial and medtech customers — financially sound EMS business with excellent balance sheet and cash flow metrics.", ["Complex electronics assemblies for industrial, medtech and energy technology customers.", "ROIC of 13.8% reflects consistent returns from quality-certified manufacturing services.", "Strong Piotroski F-Score reflecting excellent financial health and operating efficiency.", "EPS growing steadily as medtech and industrial electronics outsourcing expands."]),
    585: ('Sea1 Offshore', 'Norwegian offshore support vessels. Improving F-Score.', 'Offshore vessel F-Score.', "Sea1 Offshore is a Norwegian offshore support vessel company serving oil and gas exploration and offshore wind. The company has improving Piotroski F-Score metrics reflecting strengthening financial health as offshore activity recovers and vessel utilisation improves.", 'Offshore vessels. Improving F-Score.', 'Offshore support quality recovery.', "A Norwegian offshore support vessel operator with a 17.2% ROIC and improving Piotroski F-Score metrics. Sea1 serves oil and gas exploration and offshore wind installation — improving financial health as offshore activity recovery drives higher vessel utilisation.", ["Offshore support vessels for oil and gas exploration and offshore wind installation.", "ROIC of 17.2% reflects improving utilisation as offshore activity recovers.", "Improving Piotroski F-Score reflecting strengthening balance sheet and cash generation.", "Revenue improving as offshore wind installation and oil exploration activity expands."]),
    587: ('Sipef SA', 'Belgian tropical plantations. Strong F-Score.', 'Plantation F-Score compounder.', "Sipef operates oil palm and rubber plantations across Indonesia and Papua New Guinea. The company has strong Piotroski F-Score metrics reflecting excellent financial health from mature, cash-generating plantation assets.", 'Palm oil plantations. Strong F-Score.', 'Plantation quality compounder.', "A Belgian tropical plantation company with a 9.9% ROIC and strong Piotroski F-Score metrics. Sipef oil palm and rubber plantations generate consistent commodity income — excellent financial health from mature plantation assets.", ["Oil palm and rubber plantations in Indonesia and Papua New Guinea.", "ROIC of 9.9% reflects consistent returns from mature tropical plantation assets.", "Strong Piotroski F-Score reflecting excellent financial health and cash generation.", "EPS grew 54.7% annualised as palm oil prices and plantation productivity improved."]),
    588: ('StealthGas Inc', 'Marshall Islands small LPG tankers. Strong F-Score.', 'Small LPG tanker F-Score.', "StealthGas operates pressurised small LPG carriers globally. The company has strong Piotroski F-Score metrics reflecting improving balance sheet health as LPG tanker market conditions improved.", 'Small LPG tankers. Strong F-Score.', 'LPG tanker quality play.', "A Marshall Islands small LPG tanker operator with a 6.1% ROIC and strong Piotroski F-Score metrics. StealthGas pressurised LPG fleet serves regional propane and butane distribution — improving financial health from LPG market recovery.", ["Pressurised LPG carriers serving regional propane and butane distribution markets.", "Strong Piotroski F-Score reflecting improving balance sheet and cash generation.", "EPS grew 40.4% annualised as small LPG tanker rates and utilisation improved.", "Niche vessel segment with limited new supply supporting sustained rate improvement."]),
    589: ('Strategic Education Inc', 'US online universities. Strong F-Score.', 'Online education F-Score.', "Strategic Education operates Strayer University and Capella University. The company has strong Piotroski F-Score metrics reflecting excellent financial health from scalable online higher education operations.", 'Online education. Strong F-Score quality.', 'Online university quality play.', "A US online university operator with a 4.8% ROIC and strong Piotroski F-Score metrics. Strategic Education Strayer and Capella universities serve working adults — financially sound online education business with consistent tuition revenue and strong balance sheet.", ["Strayer University and Capella University — online higher education for working adults.", "Strong Piotroski F-Score reflecting excellent financial health and free cash flow.", "EPS grew 7.9% annualised with consistent enrolment and tuition revenue.", "Revenue grew 4.0% annualised with stable demand from working adult education market."]),
    590: ('Tenaris SA', 'Argentine steel tubes for oil and gas. Strong F-Score.', 'Steel tubes F-Score compounder.', "Tenaris is the world leader in steel tubes for oil and gas drilling. The company has strong Piotroski F-Score metrics reflecting excellent financial health from its dominant global OCTG market position.", 'Steel tubes. Strong F-Score quality.', 'Oil tubes quality compounder.', "The world's leading OCTG steel tube manufacturer with a 16.4% ROIC and strong Piotroski F-Score metrics. Tenaris dominant global position generates excellent financial health — strong balance sheet and free cash flow from consistent oil drilling demand.", ["World leading OCTG steel tubes for oil and gas drilling and completion globally.", "ROIC of 16.4% reflects consistent returns from dominant market position in steel tubes.", "Strong Piotroski F-Score reflecting excellent financial health and free cash flow.", "EPS grew 40.1% annualised as oil drilling activity and tube pricing strengthened."]),
    591: ('The North West Co Inc', 'Canadian remote community retailer. Strong F-Score.', 'Remote community retail.', "The North West Company operates retail stores in remote and underserved communities across Northern Canada, Alaska, the Pacific Islands, and the Caribbean. The company provides essential grocery and general merchandise to communities with no alternative retail access.", 'Remote community retail. Strong F-Score.', 'Essential retail quality compounder.', "A Canadian remote community retailer with a 12.9% ROIC and strong Piotroski F-Score metrics. North West Company serves communities with no alternative retail access — a captive customer base with defensive, essential merchandise demand.", ["Retail stores in remote communities across Northern Canada, Alaska and Pacific Islands.", "Captive customer base — no alternative retail access in served communities.", "Strong Piotroski F-Score reflecting excellent financial health and consistent free cash flow.", "EPS grew 0.8% annualised with stable demand from essential remote community retail."]),
    592: ('Total Energy Services Inc', 'Canadian oilfield services. Strong F-Score.', 'Energy services F-Score.', "Total Energy Services provides contract drilling, well servicing, and compression across Western Canada and the US. The company has strong Piotroski F-Score metrics reflecting improving financial health from oilfield services recovery.", 'Canadian oilfield services. Strong F-Score.', 'Energy services quality play.', "A Canadian diversified oilfield services company with a 6.0% ROIC and strong Piotroski F-Score metrics. Total Energy Services provides drilling, compression, and well servicing — improving financial health from Western Canadian energy activity recovery.", ["Contract drilling, well servicing and compression in Western Canada and US.", "Strong Piotroski F-Score reflecting improving financial health and cash generation.", "EPS grew 37.6% annualised as Canadian drilling activity and service pricing strengthened.", "Revenue grew 17.4% annualised with organic growth and disciplined acquisition expansion."]),
    593: ('Utah Medical Products Inc', 'US obstetrics medical devices. Exceptional ROIC.', 'Obstetrics device F-Score.', "Utah Medical Products manufactures specialty disposable devices for obstetrics and neonatal care. The company has strong Piotroski F-Score metrics combined with exceptional returns on capital from its niche medical device business.", 'Obstetrics devices. Exceptional ROIC.', 'Niche medical quality compounder.', "A US specialty medical device manufacturer with a 36.7% ROIC and strong Piotroski F-Score metrics. Utah Medical Products produces disposable obstetrics devices — exceptional financial health combined with extraordinary capital efficiency in a niche device market.", ["Specialty disposable devices for obstetrics, gynaecology and neonatal intensive care.", "ROIC of 36.7% — exceptional returns from a niche, highly defensible medical device business.", "Strong Piotroski F-Score reflecting excellent financial health and free cash flow.", "Recurring demand from hospital labour and delivery and NICU units globally."]),
    594: ('Viscofan SA', 'Spanish food casings leader. Strong F-Score.', 'Food casings F-Score.', "Viscofan is the global leader in food casings for processed meat. The company has strong Piotroski F-Score metrics reflecting excellent financial health from its dominant global food casings position.", 'Food casings leader. Strong F-Score.', 'Food casing quality compounder.', "The global food casings leader with a 15.1% ROIC and strong Piotroski F-Score metrics. Viscofan dominant niche position generates excellent financial health — strong balance sheet and free cash flow from consistent processed meat industry demand.", ["Global leader in collagen, cellulose and plastic food casings for processed meat.", "ROIC of 15.1% reflects consistent returns from a dominant food ingredient niche.", "Strong Piotroski F-Score reflecting excellent financial health and free cash flow.", "Dividend yield of 5.5% backed by consistent free cash flow from a stable food business."]),
    595: ('Winpak Ltd', 'Canadian specialty packaging. Strong F-Score.', 'Food packaging F-Score.', "Winpak manufactures specialty food packaging materials extending shelf life for perishable foods. The company has strong Piotroski F-Score metrics reflecting consistent financial health from a defensive food packaging business.", 'Specialty packaging. Strong F-Score quality.', 'Packaging quality compounder.', "A Canadian specialty packaging company with a 14.3% ROIC and strong Piotroski F-Score metrics. Winpak produces modified atmosphere and high-barrier food packaging — excellent financial health from a defensive, recurring food industry business.", ["High-barrier films and modified atmosphere packaging for perishable food and beverage.", "ROIC of 14.3% reflects consistent returns from specialty food packaging materials.", "Strong Piotroski F-Score reflecting excellent financial health and cash generation.", "Defensive food packaging business with recurring demand through economic cycles."]),
    596: ('Yara International', 'Norwegian nitrogen fertiliser giant. Strong F-Score.', 'Global fertiliser leader.', "Yara International is the world's largest nitrogen fertiliser company, producing ammonia, urea, and nitrate fertilisers for global agriculture. The company has a strong Piotroski F-Score reflecting improving financial health from fertiliser market recovery and balance sheet management.", 'Nitrogen fertiliser giant. Strong F-Score.', 'Global fertiliser quality play.', "The world's largest nitrogen fertiliser company with a 7.5% ROIC and strong Piotroski F-Score metrics. Yara produces ammonia and urea for global agriculture — improving financial health from disciplined balance sheet management and fertiliser market recovery.", ["World's largest nitrogen fertiliser producer — ammonia, urea and nitrate globally.", "ROIC of 7.5% with improving trajectory from fertiliser market normalisation.", "Strong Piotroski F-Score reflecting improving financial health and balance sheet management.", "EPS grew 15.8% annualised as fertiliser demand and operational efficiency improved."]),
    597: ('Yue Yuen Industrial Ltd', 'Hong Kong athletic footwear manufacturer. Strong F-Score.', 'Athletic footwear manufacturer.', "Yue Yuen is the world's largest manufacturer of athletic and casual footwear, producing shoes for Nike, Adidas, New Balance, and other global brands from factories across Asia. The company has strong Piotroski F-Score metrics reflecting consistent financial health from its dominant manufacturing position.", 'Athletic footwear. Strong F-Score quality.', 'Footwear manufacturing quality play.', "The world's largest athletic footwear manufacturer with a 6.2% ROIC and strong Piotroski F-Score metrics. Yue Yuen produces shoes for Nike, Adidas, and New Balance — financially sound dominant manufacturer with excellent balance sheet health.", ["World's largest athletic footwear manufacturer — Nike, Adidas, New Balance and others.", "ROIC of 6.2% reflects consistent returns from a dominant footwear manufacturing position.", "Strong Piotroski F-Score reflecting excellent financial health and cash generation.", "EPS grew 44.0% annualised as post-COVID footwear demand and margins recovered."]),
    598: ('ZTO Express Inc', 'Chinese parcel delivery. Strong F-Score.', 'China logistics F-Score.', "ZTO Express is one of China's largest parcel delivery networks. The company has strong Piotroski F-Score metrics reflecting excellent financial health from its leading e-commerce logistics position in China.", 'China parcel delivery. Strong F-Score.', 'China logistics quality play.', "A Chinese parcel delivery network with a 17.7% ROIC and strong Piotroski F-Score metrics. ZTO Express serves Chinese e-commerce platforms — excellent financial health from a leading logistics position in China's growing parcel market.", ["One of China's largest parcel delivery networks serving major e-commerce platforms.", "ROIC of 17.7% reflects strong network economics from China e-commerce logistics.", "Strong Piotroski F-Score reflecting excellent financial health and free cash flow.", "EPS grew 15.3% annualised as Chinese e-commerce parcel volumes expanded consistently."]),
}

with open(CARDS_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

updated = 0
for card_id, (company, tag, tagBold, tagFull, pick, pickBold, pickFull, bullets) in descriptions.items():
    pattern = re.compile(
        rf"(id: {card_id}, type: 'ACE'.*?tag: ')[^']*('.*?tagBold: ')[^']*('.*?tagFull: \")[^\"]*(\",.*?pick: ')[^']*('.*?pickBold: ')[^']*('.*?pickFull: \")[^\"]*(\",)",
        re.DOTALL
    )
    replacement = rf"\g<1>{tag}\g<2>{tagBold}\g<3>{tagFull}\g<4>{pick}\g<5>{pickBold}\g<6>{pickFull}\g<7>"
    new_content = pattern.sub(replacement, content)
    if new_content != content:
        content = new_content
        updated += 1
        print(f"✅ {card_id}: {company}")
    else:
        print(f"❌ {card_id}: pattern not matched")
    bullets_str = ', '.join([f'"{b}"' for b in bullets])
    bullets_pattern = re.compile(rf"(id: {card_id},.*?bullets: \[)[^\]]*\]", re.DOTALL)
    content = bullets_pattern.sub(rf"\g<1>{bullets_str}]", content)

with open(CARDS_PATH, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n✅ Updated {updated}/25 ACE cards")
print(f"Remaining generic: {content.count('operates in')}")
