import re

CARDS_PATH = '/Users/radekmajewski/Downloads/valujack/public/cards.js'

descriptions = {
    328: ('Krka DD', 'Slovenian pharma. High quality. Low profile.', 'European generic pharma.', "Krka is a Slovenian pharmaceutical company specialising in generic drugs, OTC products, and animal health. Operating across Central and Eastern Europe, Russia, and Western Europe, Krka has built a diversified geographic footprint with consistently high margins and returns on capital.", 'Quality pharma. Underappreciated.', 'Hidden European compounder.', "A high-quality Slovenian generic pharmaceutical company with a 19.4% ROIC and a 3.4% dividend yield. Krka operates in structurally growing generic drug markets across Europe and has compounded earnings steadily for over a decade. The stock is largely overlooked by international investors.", ["Leading Slovenian generic pharmaceutical company with operations across 70+ countries.", "ROIC of 19.4% — exceptional for a generic pharma business, reflecting strong operational efficiency.", "EPS grew 7.3% annualised with consistent margins across economic cycles.", "Dividend yield of 3.4% backed by strong free cash flow from a diversified drug portfolio."]),
    339: ('Clarkson PLC', 'World\'s largest shipbroker. High ROIC.', 'Shipbroking monopoly.', "Clarkson is the world's largest shipbroking firm, acting as intermediary in the buying, selling, and chartering of ships globally. The business is deeply embedded in global trade infrastructure and generates extraordinary returns on capital from its asset-light advisory model.", 'Shipbroking leader. Exceptional returns.', 'Asset-light trade infrastructure.', "The world's largest shipbroker with an 89.5% ROIC and EPS growth of 33.5% annualised. Clarkson's advisory model requires minimal capital yet sits at the centre of global shipping transactions. The 2.3% dividend yield is conservative relative to cash generation — the business retains significant earnings for growth.", ["World's largest shipbroking firm — intermediary in global ship chartering, sale and purchase.", "ROIC of 89.5% — exceptional returns from a capital-light advisory business model.", "EPS grew 33.5% annualised over five years, driven by elevated shipping market activity.", "Dividend yield of 2.3% with significant additional cash generation retained for growth."]),
    340: ('COSCO SHIPPING International Co', 'Hong Kong shipping services. High yield.', 'COSCO shipping services.', "COSCO SHIPPING International is the Hong Kong-listed service arm of China's state-owned COSCO shipping group, providing ship agency, ship trading, and marine insurance services. The business benefits from COSCO's massive global shipping network.", 'Shipping services. High yield.', 'State-backed shipping income.', "A Hong Kong-listed shipping services company backed by China's COSCO group with a 7.8% dividend yield and ROIC of 21.2%. The business provides ship agency and marine services to one of the world's largest shipping fleets — a captive revenue stream with minimal competitive risk.", ["Ship agency, trading and marine insurance services for the COSCO global shipping network.", "ROIC of 21.2% reflects efficient capital use in a service-based shipping model.", "EPS grew 20.1% annualised — strong earnings growth from rising shipping market activity.", "Dividend yield of 7.8% backed by consistent cash generation from captive COSCO business."]),
    341: ('EBARA JITSUGYO Co Ltd', 'Japanese pump distributor. High ROIC.', 'Industrial pump specialist.', "Ebara Jitsugyo is a Japanese distributor and manufacturer of industrial pumps, compressors, and fluid handling equipment for chemical, pharmaceutical, and semiconductor industries. The company benefits from Japan's precision engineering reputation and long-term customer relationships.", 'Industrial pumps. Quality compounder.', 'Japanese industrial compounder.', "A Japanese industrial pump specialist with a 33.3% ROIC and EPS growth of 14.8% annualised. Ebara Jitsugyo's fluid handling equipment serves mission-critical applications in semiconductor fabs and chemical plants — creating sticky, long-term customer relationships with high switching costs.", ["Industrial pump and fluid handling equipment for semiconductor, chemical and pharmaceutical industries.", "ROIC of 33.3% — high for an industrial distributor, reflecting specialised product expertise.", "EPS grew 14.8% annualised with consistent demand from semiconductor manufacturing expansion.", "Dividend yield of 2.5% with a conservative payout and strong retained earnings growth."]),
    342: ('ENAV SpA', 'Italian air traffic control. Monopoly yield.', 'Air traffic control monopoly.', "ENAV is Italy's state-owned air traffic control provider, holding a regulated monopoly over all civil aviation navigation services in Italian airspace. As air travel recovers and grows, ENAV's revenues grow with it — underpinned by a government concession with regulated returns.", 'Regulated monopoly. Growing dividend.', 'Infrastructure income.', "Italy's monopoly air traffic control provider with a 5.3% dividend yield. ENAV's revenues are directly linked to Italian airspace movements — structurally growing as European aviation recovers. The regulated concession model provides predictable cash flows and a reliable dividend.", ["Italy's sole air traffic control provider — government-regulated monopoly over all civil aviation.", "Revenue grows with Italian airspace movements — structural recovery in European aviation.", "Regulated concession model provides predictable cash flows and earnings visibility.", "Dividend yield of 5.3% backed by stable, government-backed revenue streams."]),
    343: ('EUROKAI GmbH & Co KGaA', 'German container terminal. Steady yield.', 'Container terminal operator.', "Eurokai is a German container terminal operator running major port facilities in Hamburg and Trieste. Container terminals are infrastructure assets with high barriers to entry — port concessions take decades to secure and terminal infrastructure requires massive capital investment.", 'Container terminal. Infrastructure income.', 'Port infrastructure compounder.', "A German container terminal operator with a 3.3% dividend yield and EPS growth of 27.5% annualised. Eurokai's Hamburg and Trieste terminals handle millions of TEUs annually — generating stable, long-term concession revenues from an asset that cannot be easily replicated.", ["Container terminal operator at Hamburg and Trieste — strategic European port locations.", "Port concessions and terminal infrastructure represent extremely high barriers to entry.", "EPS grew 27.5% annualised as container volumes and terminal revenues recovered strongly.", "Dividend yield of 3.3% from a stable, long-term infrastructure cash flow base."]),
    344: ('Evertz Technologies Ltd', 'Canadian broadcast technology. High yield.', 'Broadcast infrastructure leader.', "Evertz Technologies is a Canadian manufacturer of broadcast infrastructure equipment — the routing, monitoring, and production systems that sit at the heart of television studios and streaming facilities worldwide. The company has a strong market position in live broadcast infrastructure.", 'Broadcast tech. Exceptional yield.', 'Niche technology income.', "A Canadian broadcast technology company with an 11.0% dividend yield and 32.2% ROIC. Evertz's routing and monitoring systems are embedded in virtually every major broadcaster and streaming facility globally. The high yield reflects exceptional cash generation from a capital-light technology business.", ["Broadcast infrastructure equipment — routing, monitoring and production systems for TV and streaming.", "ROIC of 32.2% reflects strong intellectual property and switching costs in broadcast technology.", "EPS grew 8.3% annualised with consistent demand from broadcaster infrastructure upgrades.", "Dividend yield of 11.0% — exceptional income from a cash-generative technology business."]),
    345: ('EVS Broadcast Equipment SA', 'Belgian live broadcast tech. High ROIC.', 'Live production technology.', "EVS Broadcast Equipment is a Belgian company making live video production systems used in sports broadcasting, news, and entertainment worldwide. EVS servers and replay systems are the industry standard for live sports production — used at every major sporting event globally.", 'Live sports broadcast standard. High ROIC.', 'Sports broadcast infrastructure.', "A Belgian broadcast technology company with a 25.9% ROIC and EPS growth of 40.3% annualised. EVS systems are the global standard for live sports replay and production — present at every major sporting event from the Olympics to the World Cup. The 3.3% dividend yield is growing alongside strong earnings expansion.", ["Live video production systems used at every major global sporting event and news broadcast.", "ROIC of 25.9% reflects strong intellectual property and market leadership in live sports production.", "EPS grew 40.3% annualised from a restructured base — significant operational improvement.", "Dividend yield of 3.3% growing alongside strong free cash flow generation."]),
    346: ('Frosta AG', 'German frozen food. Consistent compounder.', 'Premium frozen food brand.', "Frosta is a German premium frozen food manufacturer known for its clean-label products — meals and vegetables made without artificial additives. The brand commands premium pricing in German retail and has expanded across European markets on the back of growing consumer demand for clean-label foods.", 'Premium frozen food. Clean label leader.', 'German food compounder.', "A German premium frozen food company with a 13.2% ROIC and EPS growth of 8.1% annualised. Frosta's clean-label positioning — no artificial additives — commands premium pricing and loyalty in a structurally growing market segment. The 2.5% dividend yield is supported by consistent free cash flow.", ["Premium frozen food brand with clean-label positioning — no artificial additives or preservatives.", "Strong brand loyalty in Germany and expanding European distribution.", "ROIC of 13.2% reflects consistent returns from a branded food business with pricing power.", "Dividend yield of 2.5% backed by steady free cash flow from a defensive food business."]),
    347: ('Gaztransport et technigaz SA', 'French LNG tank designer. Exceptional ROIC.', 'LNG infrastructure monopoly.', "GTT designs the membrane containment systems used in virtually all LNG carriers and floating storage units worldwide. The company holds the dominant intellectual property position in LNG tank technology — earning royalties on every new LNG vessel built globally.", 'LNG royalties. Extraordinary returns.', 'LNG technology monopoly.', "The world's dominant LNG tank technology licensor with a 205% ROIC and EPS growth of 15.8% annualised. GTT earns royalties on virtually every new LNG carrier ordered globally — a pure intellectual property model with minimal capital requirements. The 4.0% dividend yield reflects a business that generates far more cash than it needs.", ["Dominant LNG tank membrane technology licensor — royalties on virtually every new LNG vessel built.", "ROIC of 205% reflects an extraordinary pure intellectual property business model.", "EPS grew 15.8% annualised as global LNG fleet expansion drove royalty income higher.", "Dividend yield of 4.0% from a business generating exceptional free cash flow per share."]),
    348: ('Genuit Group PLC', 'UK water management systems. Dividend grower.', 'UK water infrastructure.', "Genuit Group is a UK manufacturer of water and climate management systems — pipes, drainage, and ventilation products for residential and commercial construction. The business benefits from structural demand for sustainable water management and building ventilation in the UK housing market.", 'UK water infrastructure. Dividend grower.', 'Construction materials income.', "A UK water management systems manufacturer with a 2.5% dividend yield serving structural demand in UK construction. Genuit's drainage and ventilation products are specified into new housing developments — creating recurring demand driven by planning approvals and housebuilding volumes.", ["Water management and climate systems for UK residential and commercial construction markets.", "Products specified into new housing — demand driven by structural UK housebuilding activity.", "Exposure to growing regulatory requirements for sustainable drainage and building ventilation.", "Dividend yield of 2.5% with a long track record of dividend payments."]),
    349: ('Giordano International Ltd', 'Hong Kong fashion retailer. High yield.', 'Asian casual fashion retailer.', "Giordano is a Hong Kong-based casual fashion retailer operating across Asia, the Middle East, and Australia. The brand focuses on affordable basics and has maintained a loyal customer base across multiple markets through decades of consistent quality positioning.", 'Asian fashion. High yield income.', 'Asian retail income.', "A Hong Kong casual fashion retailer with an 8.6% dividend yield and ROIC of 13.0%. Giordano's affordable basics positioning provides resilience through economic cycles — customers trade down to Giordano during downturns, not away from it. EPS grew 31.3% annualised as post-COVID retail recovered across Asia.", ["Casual fashion retailer across Asia, Middle East and Australia — affordable basics positioning.", "ROIC of 13.0% reflects consistent returns from a lean retail model with low inventory risk.", "EPS grew 31.3% annualised as post-COVID retail recovery boosted Asian consumer spending.", "Dividend yield of 8.6% — attractive income from a cash-generative, asset-light retail model."]),
    350: ('Gr. Sarantis SA', 'Greek consumer goods. Growing dividend.', 'Balkan consumer goods leader.', "Sarantis is a Greek consumer goods company distributing personal care, household, and baby products across Central and Eastern Europe. The company acts as a regional distributor for global brands while also building its own proprietary brand portfolio.", 'CEE consumer goods. Growing dividend.', 'Balkan distribution compounder.', "A Greek consumer goods company with a 12.4% ROIC and EPS growth of 7.6% annualised, distributing personal care and household products across Central and Eastern Europe. Sarantis benefits from growing consumer spending in emerging European markets with a diversified brand portfolio.", ["Personal care, household and baby products distributed across Central and Eastern Europe.", "ROIC of 12.4% reflects consistent returns from a regional distribution business with own brands.", "EPS grew 7.6% annualised from a growing consumer base across CEE markets.", "Dividend yield of 2.1% with consistent growth as earnings compound steadily."]),
    351: ('HF Sinclair Corp', 'US independent refiner. High yield.', 'US petroleum refiner.', "HF Sinclair is a US independent petroleum refiner and marketer, operating refineries across the Rockies, Southwest, and Mid-Continent. The company also has a growing lubricants business and a midstream segment providing additional earnings diversification.", 'US refining. High yield income.', 'Independent refining income.', "A US independent petroleum refiner with a 3.5% dividend yield and EPS growth of 23.1% annualised. HF Sinclair's geographically diversified refinery network and growing lubricants business provide earnings resilience through commodity cycles. The stock trades at a discount to fair value on normalised refining margins.", ["Independent petroleum refiner across the Rockies, Southwest and Mid-Continent US.", "Growing lubricants business provides higher-margin, less cyclical earnings diversification.", "EPS grew 23.1% annualised over five years across refining and lubricants segments.", "Dividend yield of 3.5% with a consistent history of cash returns to shareholders."]),
    352: ('Hirose Electric Co Ltd', 'Japanese connector manufacturer. Quality niche.', 'Precision connector specialist.', "Hirose Electric is a Japanese manufacturer of high-precision electrical connectors for industrial, medical, and automotive applications. The company's connectors are specified into mission-critical equipment where reliability is paramount — creating long qualification cycles and high switching costs.", 'Precision connectors. Quality compounder.', 'Japanese precision engineering.', "A Japanese precision connector manufacturer with a 16.2% ROIC and EPS growth of 10.8% annualised. Hirose's connectors are specified into industrial robots, medical devices, and automotive electronics — applications where switching suppliers carries high risk and cost.", ["High-precision electrical connectors for industrial robots, medical devices and automotive electronics.", "ROIC of 16.2% reflects strong intellectual property and switching costs in precision connectors.", "EPS grew 10.8% annualised with consistent demand from industrial automation expansion.", "Dividend yield of 2.5% with a conservative payout and significant retained earnings growth."]),
    353: ('Innospec Inc', 'US specialty chemicals. Consistent compounder.', 'Specialty fuel additives.', "Innospec is a US specialty chemicals company focused on fuel additives, personal care ingredients, and oilfield chemicals. The fuel additives business provides performance chemicals that improve fuel efficiency and reduce emissions — a growing regulatory requirement globally.", 'Specialty chemicals. Consistent returns.', 'Niche chemicals compounder.', "A US specialty chemicals company with a 9.3% ROIC and EPS growth of 32.0% annualised. Innospec's fuel additives improve performance and reduce emissions — regulatory tailwinds support long-term demand. The 2.2% dividend yield is growing alongside strong earnings expansion.", ["Fuel additives, personal care ingredients and oilfield chemicals — diversified specialty portfolio.", "Fuel performance additives benefit from regulatory tailwinds for cleaner emissions.", "EPS grew 32.0% annualised over five years — strong earnings momentum from specialty chemicals.", "Dividend yield of 2.2% growing alongside consistent free cash flow generation."]),
    354: ('Interparfums Inc', 'US luxury fragrance licensor. High ROIC.', 'Licensed luxury fragrance.', "Interparfums is a US company that licenses and manufactures fragrances for luxury brands including Montblanc, Jimmy Choo, GUESS, and Coach. The asset-light licensing model generates high returns on capital — Interparfums does not own the brands but earns royalties on their fragrance lines.", 'Luxury fragrance licensing. High returns.', 'Asset-light luxury compounder.', "A US luxury fragrance licensor with a 16.9% ROIC and EPS growth of 34.1% annualised. Interparfums licenses fragrance rights from premium fashion brands and manufactures and distributes the products globally — capturing luxury brand economics without owning the underlying IP.", ["Licensed fragrances for Montblanc, Jimmy Choo, GUESS and Coach — premium brand exposure.", "Asset-light licensing model generates high ROIC without owning the underlying luxury brands.", "EPS grew 34.1% annualised over five years — exceptional growth from expanding brand portfolio.", "Dividend yield of 3.2% growing alongside strong free cash flow from the licensing model."]),
    355: ('J&J Snack Foods Corp', 'US specialty snack foods. Consistent dividend.', 'US snack food compounder.', "J&J Snack Foods is a US manufacturer and distributor of specialty snack foods and frozen beverages — including SuperPretzel soft pretzels, ICEE frozen drinks, and Slush Puppie. The company supplies food service operators, retailers, and amusement venues across North America.", 'Specialty snacks. Defensive compounder.', 'US food service compounder.', "A US specialty snack food company with a 3.9% dividend yield serving food service and retail channels. J&J Snack Foods' branded portfolio — SuperPretzel, ICEE, Slush Puppie — provides recurring demand from stadiums, cinemas, and convenience stores.", ["Specialty snack foods and frozen beverages for food service, retail and amusement venues.", "Branded portfolio includes SuperPretzel, ICEE and Slush Puppie — strong consumer recognition.", "Consistent demand from stadiums, cinemas and convenience stores — resilient to economic cycles.", "Dividend yield of 3.9% backed by steady free cash flow from a defensive food business."]),
    356: ('KB Home', 'US homebuilder. Dividend grower.', 'US homebuilder.', "KB Home is one of the largest US homebuilders, constructing single-family homes primarily for first-time and move-up buyers across California, Texas, and the Southeast. The company benefits from a structural US housing shortage and focuses on affordable price points with high energy efficiency.", 'US housing shortage. Dividend grower.', 'US homebuilder compounder.', "A US homebuilder with an 11.8% ROIC and EPS growth of 14.0% annualised, benefiting from structural US housing undersupply. KB Home's focus on affordable, energy-efficient homes for first-time buyers targets the most undersupplied segment of the US housing market.", ["US homebuilder focused on affordable single-family homes for first-time and move-up buyers.", "Structural US housing shortage provides multi-year demand tailwind for new homebuilders.", "ROIC of 11.8% reflects disciplined land management and consistent operational execution.", "Dividend yield of 1.8% with consistent growth as earnings compound through the housing cycle."]),
    357: ('Komori Corp', 'Japanese printing press manufacturer. High yield.', 'Printing press specialist.', "Komori is a Japanese manufacturer of commercial printing presses, currency printing equipment, and industrial machinery. The company supplies printing equipment to commercial printers, packaging companies, and central banks globally — with a strong position in high-security currency printing.", 'Japanese printing tech. High yield.', 'Niche machinery compounder.', "A Japanese printing press manufacturer with a 5.9% dividend yield and EPS growth of 44.9% annualised from a low base. Komori's currency printing equipment serves central banks globally — a niche with extremely high barriers to entry and long replacement cycles.", ["Commercial and currency printing press manufacturer serving global commercial and government clients.", "Currency printing equipment for central banks — extremely high barriers to entry in this niche.", "EPS grew 44.9% annualised from a restructured base — significant operational turnaround.", "Dividend yield of 5.9% — attractive income from a recovering, cash-generative business."]),
}

with open(CARDS_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

updated = 0
for card_id, (company, tag, tagBold, tagFull, pick, pickBold, pickFull, bullets) in descriptions.items():
    pattern = re.compile(
        rf"(id: {card_id}, type: 'KING'.*?tag: ')[^']*('.*?tagBold: ')[^']*('.*?tagFull: \")[^\"]*(\",.*?pick: ')[^']*('.*?pickBold: ')[^']*('.*?pickFull: \")[^\"]*(\",)",
        re.DOTALL
    )
    replacement = rf"\g<1>{tag}\g<2>{tagBold}\g<3>{tagFull}\g<4>{pick}\g<5>{pickBold}\g<6>{pickFull}\g<7>"
    new_content = pattern.sub(replacement, content)
    if new_content != content:
        content = new_content
        updated += 1
        print(f"✅ {card_id}: {company}")
    else:
        print(f"❌ {card_id}: pattern not matched")
    bullets_str = ', '.join([f'"{b}"' for b in bullets])
    bullets_pattern = re.compile(rf"(id: {card_id},.*?bullets: \[)[^\]]*\]", re.DOTALL)
    content = bullets_pattern.sub(rf"\g<1>{bullets_str}]", content)

with open(CARDS_PATH, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n✅ Updated {updated}/20 KING cards")
print(f"Remaining generic: {content.count('operates in')}")
