import re

CARDS_PATH = '/Users/radekmajewski/Downloads/valujack/public/cards.js'

descriptions = {
    527: ('SNGN Romgaz SA', 'Romanian natural gas producer. High ROIC.', 'Romanian gas monopoly.', "Romgaz is Romania's largest natural gas producer and a major gas storage operator, supplying the majority of Romanian domestic gas consumption. The company holds a dominant position in Romanian gas production with long-life fields and a regulated storage business.", 'Romanian gas monopoly. High ROIC.', 'Eastern European gas income.', "Romania's largest natural gas producer with a 26.1% ROIC and EPS growth of 21.7% annualised. Romgaz supplies the majority of Romanian domestic gas consumption from long-life fields — a dominant national gas position with predictable regulated returns.", ["Romania's largest natural gas producer — dominant domestic supply position.", "ROIC of 26.1% reflects strong margins from long-life gas fields with low production costs.", "EPS grew 21.7% annualised as gas prices and production volumes remained supportive.", "Gas storage operations provide additional regulated revenue stream."]),
    528: ('Societatea Nationala', 'Romanian nuclear energy producer. High ROIC.', 'Romanian nuclear power.', "Societatea Nationala Nuclearelectrica is Romania's nuclear power producer, operating the Cernavoda nuclear plant — the only nuclear facility in Romania. The company provides approximately 20% of Romania's electricity from its two CANDU reactor units.", 'Romanian nuclear power. High ROIC.', 'Nuclear energy income.', "Romania's nuclear power producer with a 25.4% ROIC and EPS growth of 27.3% annualised. Nuclearelectrica operates the Cernavoda plant providing around 20% of Romanian electricity — low-cost baseload generation with regulated returns from long-life nuclear assets.", ["Romanian nuclear power producer — Cernavoda plant with two CANDU reactor units.", "ROIC of 25.4% reflects strong returns from low-cost nuclear baseload generation.", "EPS grew 27.3% annualised as electricity prices and generation volumes expanded.", "Provides approximately 20% of Romanian electricity — essential national energy infrastructure."]),
    529: ('SUESS MicroTec SE', 'German semiconductor equipment. High growth.', 'Semiconductor equipment specialist.', "SUESS MicroTec is a German manufacturer of lithography and wafer processing equipment for semiconductor, MEMS, and advanced packaging applications. The company produces mask aligners, wafer bonders, and photoresist processing systems for advanced chip manufacturing.", 'Semiconductor equipment. High growth momentum.', 'Chip equipment growth play.', "A German semiconductor equipment manufacturer with a 22.1% ROIC and EPS growth of 35.3% annualised. SUESS MicroTec produces lithography and wafer bonding equipment for advanced semiconductor and MEMS manufacturing — benefiting from structural growth in chip complexity and advanced packaging.", ["Lithography, wafer bonding and photoresist systems for semiconductor and MEMS manufacturing.", "ROIC of 22.1% reflects strong market position in specialty semiconductor equipment.", "EPS grew 35.3% annualised as advanced packaging and MEMS demand accelerated.", "Revenue grew 34.8% annualised driven by structural semiconductor complexity growth."]),
    530: ('Teekay Tankers Ltd', 'Canadian crude tanker. Magic formula value.', 'Crude tanker value play.', "Teekay Tankers operates Suezmax and Aframax crude tankers globally. The company screens on the Magic Formula — a high ROIC from elevated crude tanker markets at an attractive earnings yield.", 'Crude tankers. Magic formula value.', 'Tanker value play.', "A Canadian crude tanker operator with an 18.8% ROIC screening on the Magic Formula. Teekay Tankers Suezmax and Aframax fleet serves global crude trade — quality tanker business at an attractive earnings yield as the market normalises from peak earnings.", ["Suezmax and Aframax crude tankers serving global crude oil trade routes.", "ROIC of 18.8% combined with attractive earnings yield — Magic Formula screen highlight.", "EPS grew 31.4% annualised as crude tanker rates and utilisation remained elevated.", "Russian oil rerouting structurally extended average crude voyage distances."]),
    531: ('Tenaris SA', 'Argentine steel pipe manufacturer. High ROIC.', 'Steel tube market leader.', "Tenaris is the world's leading manufacturer of steel tubes for the oil and gas industry, producing OCTG pipes used in drilling and completing wells globally. The company serves every major oil and gas producer with a global manufacturing and distribution network.", 'Steel tubes for oil and gas. High ROIC.', 'Oil country tubular compounder.', "The world's leading steel tube manufacturer for oil and gas with a 16.4% ROIC and EPS growth of 40.1% annualised. Tenaris produces OCTG pipes essential for drilling operations globally — serving every major oil producer with a vertically integrated steel tube business.", ["World leading OCTG steel tubes for oil and gas drilling and completion globally.", "ROIC of 16.4% reflects consistent returns from dominant market position in steel tubes.", "EPS grew 40.1% annualised as oil drilling activity and tube pricing strengthened.", "Global manufacturing network serving every major oil and gas producer worldwide."]),
    532: ('Tourmaline Oil Corp', "Canada's largest gas producer. Magic formula value.", 'Canadian gas value play.', "Tourmaline is Canada's largest natural gas producer with a low-cost production base in the Western Canadian Sedimentary Basin. The company screens on the Magic Formula — consistent ROIC from low-cost gas production at an attractive earnings yield.", 'Canadian gas. Magic formula value.', 'Gas producer value play.', "Canada's largest natural gas producer with a 12.3% ROIC screening on the Magic Formula. Tourmaline low-cost Montney and Deep Basin production generates consistent free cash flow — quality gas producer at an attractive earnings yield with generous dividend policy.", ["Canada's largest natural gas producer — low-cost Western Canadian Sedimentary Basin.", "ROIC of 12.3% combined with attractive earnings yield — Magic Formula screen highlight.", "Consistent free cash flow funds base and special dividends to shareholders.", "Low-cost production base provides resilience through natural gas price cycles."]),
    533: ('Trican Well Service Ltd', 'Canadian pressure pumping. Magic formula value.', 'Pressure pumping value play.', "Trican Well Service is a Canadian pressure pumping company providing hydraulic fracturing and cementing services. The company screens on the Magic Formula — consistent ROIC from essential oilfield services at an attractive earnings yield.", 'Pressure pumping. Magic formula value.', 'Fracturing service value.', "A Canadian pressure pumping company with a 15.6% ROIC screening on the Magic Formula. Trican provides hydraulic fracturing services essential for Western Canadian tight oil production — quality oilfield services at an attractive earnings yield.", ["Hydraulic fracturing and cementing for Western Canadian tight oil and gas producers.", "ROIC of 15.6% combined with attractive earnings yield — Magic Formula screen highlight.", "EPS grew 21.7% annualised as Canadian tight oil drilling activity expanded.", "Essential pressure pumping services with consistent demand from multi-well pad programmes."]),
    534: ('TTW Pcl', 'Thai water treatment utility. Steady yield.', 'Thai water utility.', "TTW is a Thai water treatment company producing and distributing tap water across the Nakhon Pathom and Samut Sakhon provinces west of Bangkok. The company operates under long-term government concessions — a regulated utility with predictable, inflation-linked revenues.", 'Thai water utility. Steady income.', 'Regulated water utility.', "A Thai water treatment utility with an 18.4% ROIC under long-term government concessions in Bangkok's western provinces. TTW produces and distributes treated water under a regulated concession — predictable, inflation-linked revenues from essential water infrastructure.", ["Water treatment and distribution under long-term government concessions in Thailand.", "ROIC of 18.4% reflects strong regulated returns from essential water infrastructure.", "EPS grew 2.1% annualised with stable regulated water volumes and pricing.", "Long-term concession provides predictable, inflation-linked revenue visibility."]),
    535: ('UIE Plc', 'Copenhagen palm oil holding. Magic formula value.', 'Palm oil holding value.', "UIE is a Copenhagen-listed investment holding company with controlling stakes in United Plantations — a high-quality Malaysian palm oil producer. The company screens on the Magic Formula — plantation ROIC combined with an attractive earnings yield.", 'Palm oil holding. Magic formula value.', 'Plantation value play.', "A Copenhagen-listed palm oil holding company with a 9.3% ROIC screening on the Magic Formula. UIE primary asset is United Plantations — one of Malaysia's highest-quality certified palm oil producers available at an attractive earnings yield.", ["Investment holding with controlling stake in United Plantations — premium Malaysian palm oil.", "ROIC of 9.3% combined with attractive earnings yield — Magic Formula screen highlight.", "Revenue grew 20.8% annualised as palm oil prices and plantation volumes expanded.", "United Plantations certification and quality commands premium from food industry buyers."]),
    536: ('United States Lime & Minerals Inc', 'US lime and limestone producer. High ROIC.', 'US lime industry leader.', "United States Lime and Minerals is the largest US lime producer, mining limestone and producing quicklime and hydrated lime for steel, construction, environmental, and chemical applications. The company benefits from growing demand for lime in environmental applications and steel production.", 'US lime producer. High ROIC compounder.', 'Lime industry compounder.', "The largest US lime producer with a 32.4% ROIC and EPS growth of 36.2% annualised. US Lime and Minerals produces quicklime and hydrated lime for steel, construction, and environmental applications — structural demand from water treatment and emissions control.", ["Quicklime and hydrated lime for steel, construction, environmental and chemical markets.", "ROIC of 32.4% — exceptional returns from a dominant US lime production position.", "EPS grew 36.2% annualised as lime demand and pricing strengthened structurally.", "Revenue grew 17.3% annualised driven by environmental and industrial lime demand growth."]),
    537: ('Utah Medical Products Inc', 'US medical devices. Exceptional ROIC.', 'Specialty medical devices.', "Utah Medical Products manufactures specialty disposable medical devices for obstetrics, gynaecology, and neonatal care. The company products are used in labour and delivery units and neonatal intensive care settings — niche medical devices with recurring demand from hospitals.", 'Specialty medical devices. Exceptional ROIC.', 'Niche medical device compounder.', "A US specialty medical device manufacturer with a 36.7% ROIC producing disposable devices for obstetrics and neonatal care. Utah Medical Products serves labour and delivery and NICU settings globally with niche devices that have high barriers to entry from clinical certification requirements.", ["Specialty disposable devices for obstetrics, gynaecology and neonatal intensive care.", "ROIC of 36.7% — exceptional returns from a niche, highly defensible medical device business.", "Recurring demand from hospital labour and delivery and NICU units globally.", "High barriers to entry from clinical certification and regulatory approval requirements."]),
    538: ('VBG Group', 'Swedish commercial vehicle components. Quality compounder.', 'Commercial vehicle systems.', "VBG Group is a Swedish manufacturer of towing systems, fifth wheel couplings, and truck body systems for commercial vehicles. The company holds leading market positions in European trailer coupling systems — safety-critical components with strict certification requirements.", 'Vehicle coupling systems. Quality compounder.', 'Commercial vehicle compounder.', "A Swedish commercial vehicle component manufacturer with a 10.2% ROIC and EPS growth of 13.2% annualised. VBG Group produces towing systems and coupling components for European trucks and trailers — safety-critical components with strict certification creating high barriers to entry.", ["Towing systems, fifth wheel couplings and truck body systems for commercial vehicles.", "ROIC of 10.2% reflects consistent returns from safety-certified commercial vehicle components.", "Leading market positions in European trailer coupling systems — high barriers to entry.", "EPS grew 13.2% annualised with consistent demand from European commercial vehicle production."]),
    539: ('Viscofan SA', 'Spanish food casings. Magic formula value.', 'Food casings value play.', "Viscofan is the global leader in food casings for processed meat products. The company screens on the Magic Formula — consistent ROIC from a dominant food ingredient niche at an attractive earnings yield.", 'Food casings leader. Magic formula value.', 'Food casing value compounder.', "The global food casings leader with a 15.1% ROIC screening on the Magic Formula. Viscofan produces collagen, cellulose, and plastic casings for processed meat globally — dominant niche at an attractive earnings yield.", ["Global leader in collagen, cellulose and plastic food casings for processed meat.", "ROIC of 15.1% combined with attractive earnings yield — Magic Formula screen highlight.", "Dominant market position with high switching costs from long meat processor relationships.", "Dividend yield of 5.5% backed by consistent free cash flow from a stable food business."]),
    540: ('Watts Water Technologies Inc', 'US water management products. High ROIC.', 'Water technology leader.', "Watts Water Technologies is a US manufacturer of water products — flow control, water quality, and HVAC products for commercial, industrial, and residential applications. The company benefits from growing investment in smart water infrastructure and building sustainability requirements.", 'Water technology. High ROIC compounder.', 'Water infrastructure compounder.', "A US water technology manufacturer with a 17.3% ROIC and EPS growth of 24.7% annualised. Watts Water produces flow control and water quality products for buildings and infrastructure — benefiting from smart building and water sustainability investment.", ["Flow control, water quality and HVAC products for commercial and industrial buildings.", "ROIC of 17.3% reflects consistent returns from essential water infrastructure products.", "EPS grew 24.7% annualised as building sustainability and smart water investment expanded.", "Revenue grew 8.3% annualised with consistent demand from construction and retrofit markets."]),
    541: ('Winpak Ltd', 'Canadian specialty packaging. Quality compounder.', 'Specialty food packaging.', "Winpak is a Canadian manufacturer of specialty packaging materials and machines for perishable food, beverages, and healthcare products. The company produces high-barrier films, lidding, and modified atmosphere packaging — extending product shelf life for food manufacturers.", 'Specialty packaging. Quality compounder.', 'Food packaging compounder.', "A Canadian specialty packaging company with a 14.3% ROIC and consistent earnings from high-barrier food packaging. Winpak produces modified atmosphere and high-barrier packaging extending shelf life for perishable foods — a defensive, recurring business with consistent food industry demand.", ["High-barrier films and modified atmosphere packaging for perishable food and beverage.", "ROIC of 14.3% reflects consistent returns from specialty food packaging materials.", "EPS grew 8.8% annualised with consistent demand from food manufacturer packaging requirements.", "Defensive food packaging business with recurring demand through economic cycles."]),
    542: ('Wuxi AppTec Co Ltd', 'Chinese pharma contract research. High ROIC.', 'China pharma outsourcing leader.', "Wuxi AppTec is a Chinese pharmaceutical contract research and manufacturing organisation — providing drug discovery, testing, and manufacturing services to global pharmaceutical companies. The company is one of the largest global CRO and CDMO businesses.", 'China pharma outsourcing. High ROIC.', 'Pharma outsourcing compounder.', "A Chinese pharmaceutical CRO and CDMO with a 22.8% ROIC and EPS growth of 44.6% annualised. Wuxi AppTec provides drug discovery, testing, and manufacturing services to global pharma companies — an asset-light outsourcing model with structural growth from rising pharma R&D spending.", ["Pharmaceutical CRO and CDMO services — drug discovery, testing and manufacturing.", "ROIC of 22.8% reflects strong returns from asset-light pharma outsourcing model.", "EPS grew 44.6% annualised as global pharma outsourcing to China accelerated.", "Revenue grew 15.8% annualised with consistent global pharma R&D outsourcing demand."]),
    543: ('Yum Brands Inc', 'US global fast food franchisor. High ROIC.', 'Global fast food franchisor.', "Yum Brands is a US franchisor of KFC, Pizza Hut, and Taco Bell globally — operating through a nearly fully franchised model with minimal capital requirements. The company earns royalties on system sales from its 55,000+ restaurant network across 155 countries.", 'KFC, Pizza Hut, Taco Bell. Asset-light royalties.', 'Global franchise compounder.', "The franchisor of KFC, Pizza Hut, and Taco Bell with a 33.4% ROIC and EPS growth of 13.3% annualised. Yum Brands earns royalties from 55,000+ restaurants across 155 countries — a nearly fully franchised model with minimal capital requirements and high-margin royalty income.", ["Franchisor of KFC, Pizza Hut and Taco Bell — 55,000+ restaurants in 155 countries.", "ROIC of 33.4% reflects exceptional returns from an asset-light franchise royalty model.", "EPS grew 13.3% annualised with consistent global system sales growth.", "Revenue grew 8.8% annualised as international franchise expansion accelerated."]),
    544: ('ZTO Express Inc', 'Chinese parcel delivery. Magic formula value.', 'China logistics value play.', "ZTO Express is one of China's largest parcel delivery networks serving Chinese e-commerce platforms. The company screens on the Magic Formula — a high ROIC from China's leading e-commerce delivery network at an attractive earnings yield.", 'China e-commerce delivery. Magic formula value.', 'China logistics value.', "A Chinese parcel delivery network with a 17.7% ROIC screening on the Magic Formula. ZTO Express handles billions of parcels annually for Alibaba and JD.com — quality e-commerce logistics business at an attractive earnings yield.", ["One of China's largest parcel delivery networks serving major e-commerce platforms.", "ROIC of 17.7% combined with attractive earnings yield — Magic Formula screen highlight.", "EPS grew 15.3% annualised as Chinese e-commerce parcel volumes expanded.", "Revenue grew 13.2% annualised with structural demand from China e-commerce growth."]),
}

with open(CARDS_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

updated = 0
for card_id, (company, tag, tagBold, tagFull, pick, pickBold, pickFull, bullets) in descriptions.items():
    pattern = re.compile(
        rf"(id: {card_id}, type: 'QUEEN'.*?tag: ')[^']*('.*?tagBold: ')[^']*('.*?tagFull: \")[^\"]*(\",.*?pick: ')[^']*('.*?pickBold: ')[^']*('.*?pickFull: \")[^\"]*(\",)",
        re.DOTALL
    )
    replacement = rf"\g<1>{tag}\g<2>{tagBold}\g<3>{tagFull}\g<4>{pick}\g<5>{pickBold}\g<6>{pickFull}\g<7>"
    new_content = pattern.sub(replacement, content)
    if new_content != content:
        content = new_content
        updated += 1
        print(f"✅ {card_id}: {company}")
    else:
        print(f"❌ {card_id}: pattern not matched")
    bullets_str = ', '.join([f'"{b}"' for b in bullets])
    bullets_pattern = re.compile(rf"(id: {card_id},.*?bullets: \[)[^\]]*\]", re.DOTALL)
    content = bullets_pattern.sub(rf"\g<1>{bullets_str}]", content)

with open(CARDS_PATH, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n✅ Updated {updated}/18 QUEEN cards")
print(f"Remaining generic: {content.count('operates in')}")
