import re

CARDS_PATH = '/Users/radekmajewski/Downloads/valujack/public/cards.js'

descriptions = {
    358: ('Kunlun Energy Co Ltd', 'Chinese natural gas distributor. Steady yield.', 'China gas distribution.', "Kunlun Energy is a Hong Kong-listed natural gas distribution company operating pipelines and LNG receiving terminals across China. The company benefits from China's structural shift from coal to natural gas as the government pursues cleaner energy targets.", 'China gas transition. Steady income.', 'Energy transition compounder.', "A Chinese natural gas distributor with a 4.6% dividend yield and ROIC of 13.6%. Kunlun Energy operates in a structurally growing market as China accelerates its coal-to-gas transition. EPS grew 10.2% annualised with predictable regulated returns from pipeline and distribution assets.", ["Natural gas pipelines and LNG terminals across China — essential energy infrastructure.", "Structural tailwind from China's coal-to-gas transition and clean energy policy targets.", "ROIC of 13.6% reflects steady regulated returns from long-life pipeline assets.", "Dividend yield of 4.6% backed by predictable cash flows from regulated distribution."]),
    359: ('Lennar Corp', 'US homebuilder. Structural housing demand.', 'US homebuilder.', "Lennar is one of the largest US homebuilders, constructing homes across 26 states for first-time, move-up, and active adult buyers. The company benefits from a multi-year structural housing shortage in the US and has diversified into multifamily and financial services.", 'US housing shortage. Quality builder.', 'US homebuilder compounder.', "One of the largest US homebuilders with a 12.2% ROIC benefiting from structural US housing undersupply. Lennar's scale across 26 states and diversification into multifamily and financial services provides earnings resilience through the housing cycle. The 2.2% dividend yield is growing alongside strong land bank execution.", ["One of the largest US homebuilders — operations across 26 states for all buyer segments.", "Structural US housing shortage provides multi-year demand tailwind for new construction.", "ROIC of 12.2% reflects disciplined land management and consistent operational scale.", "Dividend yield of 2.2% growing alongside strong free cash flow from homebuilding operations."]),
    360: ('Luka Koper DD', 'Slovenian port operator. Consistent compounder.', 'Adriatic port monopoly.', "Luka Koper is Slovenia's only commercial seaport, handling container, bulk, and vehicle cargo at the northern tip of the Adriatic Sea. As the most direct sea gateway to Central Europe, the port handles cargo for Austria, Hungary, Slovakia, and the Czech Republic.", 'Adriatic gateway monopoly. Steady yield.', 'Strategic port infrastructure.', "Slovenia's monopoly seaport and the most direct Adriatic gateway to Central Europe with a 2.3% dividend yield. Luka Koper handles container, vehicle, and bulk cargo for landlocked Central European countries — a captive customer base with no viable alternative port.", ["Slovenia's only commercial seaport — monopoly Adriatic gateway to Central Europe.", "Handles cargo for Austria, Hungary, Slovakia and Czech Republic — captive regional demand.", "ROIC of 10.0% reflects consistent infrastructure returns from a long-life port concession.", "Dividend yield of 2.3% backed by stable, long-term cargo handling revenues."]),
    361: ('Maschinenfabrik Berthold Hermle', 'German precision machining. High yield.', 'Precision machining excellence.', "Hermle is a German manufacturer of five-axis CNC milling machines — arguably the world's most precise machining centres. The company's machines are used in aerospace, medical implant, and automotive tooling applications where dimensional tolerances are measured in microns.", 'German precision engineering. High yield.', 'Precision engineering compounder.', "A German precision CNC machine tool manufacturer with a 32.1% ROIC and a 6.8% dividend yield. Hermle's five-axis machining centres are regarded as among the finest in the world — used in aerospace and medical applications where precision is non-negotiable. The high yield reflects exceptional cash generation from a niche premium product.", ["World-class five-axis CNC milling machines for aerospace, medical and automotive tooling.", "ROIC of 32.1% reflects premium pricing and switching costs in precision machine tools.", "EPS grew 3.6% annualised — steady compounding from a mature, cash-generative business.", "Dividend yield of 6.8% — exceptional income from a highly profitable precision engineering niche."]),
    362: ('Miquel y Costas & Miquel SA', 'Spanish specialty paper. Consistent compounder.', 'Specialty paper manufacturer.', "Miquel y Costas is a Spanish specialty paper manufacturer producing cigarette paper, plug wrap, and specialty papers for industrial applications. The company holds a strong global market position in tobacco-related specialty papers and has diversified into technical papers.", 'Specialty paper niche. Consistent income.', 'Niche paper compounder.', "A Spanish specialty paper manufacturer with a 12.7% ROIC and a 3.5% dividend yield. Miquel y Costas produces cigarette and specialty papers for global tobacco companies — a niche with high barriers to entry and long-term supply contracts.", ["Cigarette paper and specialty paper manufacturer for global tobacco and industrial customers.", "High barriers to entry in tobacco specialty papers — long customer qualification processes.", "ROIC of 12.7% reflects consistent returns from a niche, defensible paper business.", "Dividend yield of 3.5% backed by stable long-term supply contracts with tobacco companies."]),
    363: ('Naturenergie Holding AG', 'Swiss renewable energy. Growing dividend.', 'Swiss renewable energy.', "Naturenergie is a Swiss renewable energy company operating hydropower plants, wind farms, and solar installations across Switzerland and Germany. The company has a long history of clean energy generation and is growing its renewable portfolio to meet rising demand for green electricity.", 'Swiss renewables. Growing income.', 'Clean energy compounder.', "A Swiss renewable energy company with a 10.2% ROIC and EPS growth of 34.2% annualised. Naturenergie's hydropower assets provide stable, long-life baseload generation while wind and solar additions drive growth. The 2.5% dividend yield is growing alongside expanding renewable capacity.", ["Hydropower, wind and solar energy generation across Switzerland and Germany.", "Long-life hydropower assets provide stable baseload generation with minimal operating costs.", "EPS grew 34.2% annualised as renewable capacity expansion and higher power prices boosted earnings.", "Dividend yield of 2.5% growing alongside consistent clean energy capacity additions."]),
    364: ('NetEase Inc', 'Chinese gaming and education giant. Growing yield.', 'China gaming leader.', "NetEase is one of China's largest online gaming companies, operating popular titles including Fantasy Westward Journey and Naraka: Bladepoint. The company has also built substantial music streaming and online education businesses alongside its core gaming franchise.", 'China gaming. High quality compounder.', 'China digital entertainment.', "A Chinese online gaming company with an 18.9% ROIC and EPS growth of 25.6% annualised. NetEase's portfolio of long-running game franchises generates highly recurring revenue from dedicated player bases. The 2.6% dividend yield is growing alongside strong free cash flow expansion.", ["Major Chinese online gaming company — Fantasy Westward Journey, Naraka: Bladepoint and others.", "ROIC of 18.9% reflects strong intellectual property economics in online gaming.", "EPS grew 25.6% annualised over five years — consistent compounding from gaming and adjacent businesses.", "Dividend yield of 2.6% growing alongside strong free cash flow from the gaming franchise."]),
    365: ('Neurones', 'French IT services. High ROIC.', 'French IT compounder.', "Neurones is a French IT services group providing infrastructure management, application development, and digital consulting to large French corporations. The company has grown steadily through a combination of organic growth and disciplined acquisitions of specialist IT firms.", 'French IT services. Quality compounder.', 'French IT compounder.', "A French IT services company with a 32.2% ROIC and EPS growth of 10.5% annualised. Neurones serves large French corporates across infrastructure, applications, and consulting — building long-term client relationships in a fragmented market where scale and specialist expertise create defensible positions.", ["IT infrastructure, application development and digital consulting for large French corporations.", "ROIC of 32.2% — exceptional for an IT services business, reflecting specialised expertise.", "EPS grew 10.5% annualised with consistent margin improvement from scale and acquisitions.", "Dividend yield of 3.4% with a long track record of consistent dividend payments."]),
    366: ('Olvi', 'Finnish beverage compounder. Nordic yield.', 'Nordic beverage leader.', "Olvi is a Finnish brewery and beverage company operating across Finland, Estonia, Latvia, Lithuania, and Belarus. The company produces beer, cider, soft drinks, and energy drinks under its own brands and under licence — a diversified beverage portfolio across the Baltic region.", 'Nordic beverages. Consistent compounder.', 'Baltic beverage compounder.', "A Finnish beverage company with a 15.7% ROIC and a 4.1% dividend yield operating across the Nordic and Baltic markets. Olvi's diversified brand portfolio across beer, cider, and soft drinks provides resilient earnings through economic cycles in structurally stable markets.", ["Beer, cider and soft drinks across Finland, Estonia, Latvia, Lithuania and Belarus.", "ROIC of 15.7% reflects consistent returns from a diversified beverage portfolio.", "EPS grew 9.6% annualised with steady demand from loyal Baltic regional consumer base.", "Dividend yield of 4.1% backed by consistent free cash flow from a defensive beverage business."]),
    367: ('Orell Fussli AG', 'Swiss security printing. Consistent yield.', 'Swiss security printing.', "Orell Fussli is a Swiss company with operations in security documents, bookretailing, and industrial technology. The security documents division produces passports, banknotes, and identity documents for Swiss and international governments — a highly regulated, high-barrier business.", 'Swiss security printing. Reliable income.', 'Security document compounder.', "A Swiss security document printer producing passports, banknotes, and identity documents for governments worldwide with a 2.7% dividend yield. Orell Fussli's security printing business has extremely high barriers to entry — government certification, security clearances, and specialised equipment create a near-impenetrable moat.", ["Passport, banknote and identity document printing for Swiss and international governments.", "Extremely high barriers to entry — government certification and security clearances required.", "ROIC of 16.6% reflects consistent returns from a regulated, high-security printing business.", "Dividend yield of 2.7% backed by long-term government printing contracts."]),
    368: ('Orient Overseas Ltd', 'Hong Kong container shipping. Exceptional yield.', 'Major container line.', "Orient Overseas Container Line is one of the world's top-ten container shipping companies, operating a global fleet of container vessels under the OOCL brand. The company was acquired by COSCO in 2018 and benefits from integration with China's largest state-owned shipping group.", 'Container shipping. Exceptional yield.', 'Container shipping income.', "A major Hong Kong container shipping company with an 88.0% ROIC and an 11.2% dividend yield. OOCL operates one of the world's most efficient container fleets and has benefited significantly from elevated freight rates. The exceptional yield reflects extraordinary cash generation during the post-COVID shipping boom.", ["Top-ten global container shipping company operating under the OOCL brand worldwide.", "ROIC of 88.0% — extraordinary capital efficiency from elevated freight rates and fleet efficiency.", "EPS grew 23.2% annualised as container demand and freight rates remained structurally elevated.", "Dividend yield of 11.2% — exceptional income reflecting massive free cash flow generation."]),
    369: ('Pacific Basin Shipping Ltd', 'Hong Kong dry bulk shipper. Consistent yield.', 'Dry bulk shipping specialist.', "Pacific Basin Shipping is a Hong Kong dry bulk shipping company operating one of the world's largest fleets of Handysize and Supramax vessels. The company focuses on minor bulk cargoes — agricultural products, fertilisers, forest products — serving a diversified global customer base.", 'Dry bulk shipping. Consistent yield.', 'Dry bulk income.', "A Hong Kong dry bulk shipping company with a 20.5% ROIC and a 2.2% dividend yield. Pacific Basin's Handysize and Supramax fleet serves the global minor bulk trade — agricultural products, fertilisers, and forest products — with a diversified customer base across all major trade lanes.", ["Handysize and Supramax dry bulk fleet serving global minor bulk commodity trade.", "ROIC of 20.5% reflects efficient fleet management and disciplined capital allocation.", "EPS grew 17.7% annualised with consistent demand from global agricultural and industrial trade.", "Dividend yield of 2.2% with additional special dividends paid in high-earnings years."]),
    371: ('Raffles Medical Group Ltd', 'Singaporean private healthcare. Steady yield.', 'Singapore private hospital.', "Raffles Medical Group is Singapore's largest private healthcare provider, operating Raffles Hospital and a network of clinics across Singapore, China, and Vietnam. The group provides integrated healthcare services from primary care through specialist and hospital care.", 'Singapore healthcare. Defensive income.', 'Asian private healthcare.', "Singapore's largest private healthcare group with a 10.7% ROIC and a 2.5% dividend yield. Raffles Medical's integrated healthcare network across Singapore, China, and Vietnam benefits from rising Asian healthcare expenditure and growing medical tourism to Singapore.", ["Singapore's largest private healthcare provider — hospital and clinic network across Asia.", "Integrated healthcare from primary care to specialist and hospital services.", "ROIC of 10.7% reflects consistent returns from a growing private healthcare network.", "Dividend yield of 2.5% backed by stable healthcare demand from Singapore's affluent population."]),
    372: ('Rightmove PLC', 'UK property portal monopoly. Exceptional ROIC.', 'UK property portal monopoly.', "Rightmove is the UK's dominant online property portal, holding approximately 85% market share of all UK property listings. Estate agents have no viable alternative to Rightmove — the network effects of having the most listings attract the most buyers, and vice versa, creating an unassailable competitive position.", 'UK property monopoly. Exceptional returns.', 'Digital property monopoly.', "The UK's dominant property portal with a 511% ROIC — one of the highest in European equity markets. Rightmove's network effects are self-reinforcing: more listings attract more buyers, which attracts more agents. The 2.2% dividend yield is modest relative to the exceptional cash generation — the business returns capital primarily through buybacks.", ["UK property portal with approximately 85% market share — near-total monopoly on UK listings.", "ROIC of 511% — extraordinary returns from a pure network effect digital platform.", "EPS grew 17.4% annualised with consistent pricing power over estate agents.", "Dividend yield of 2.2% supplemented by significant share buyback programme."]),
    373: ('Rotork PLC', 'UK flow control actuators. Quality compounder.', 'Flow control specialist.', "Rotork is a UK manufacturer of industrial valve actuators — the devices that automatically open and close valves in oil, gas, water, and power infrastructure. The company has a dominant global market position in electric actuators and generates significant aftermarket revenue from its large installed base.", 'Valve actuators. Aftermarket compounder.', 'Industrial flow control.', "A UK industrial actuator manufacturer with a 20.0% ROIC and a 2.3% dividend yield. Rotork's valve actuators are embedded in critical infrastructure worldwide — oil platforms, water treatment plants, and power stations — generating high-margin aftermarket revenue from its installed base of over a million actuators.", ["Electric valve actuators for oil, gas, water and power infrastructure — safety-critical applications.", "Large installed base of over one million actuators generates high-margin recurring aftermarket revenue.", "ROIC of 20.0% reflects strong intellectual property and aftermarket economics.", "Dividend yield of 2.3% with consistent growth backed by recurring aftermarket cash flows."]),
    374: ('Russel Metals Inc', 'Canadian steel distributor. High yield.', 'Canadian metals distribution.', "Russel Metals is Canada's largest steel products distributor, servicing the oil and gas, construction, and manufacturing sectors. The company operates service centres and energy field stores across Canada, providing processed steel and metals to industrial customers.", 'Canadian steel distribution. High yield.', 'Canadian industrial income.', "Canada's largest steel distributor with a 17.2% ROIC and a 3.5% dividend yield. Russel Metals services the oil and gas, construction, and manufacturing sectors with processed steel products — benefiting from Canadian infrastructure investment and energy sector activity.", ["Canada's largest steel products distributor — service centres and energy stores across Canada.", "ROIC of 17.2% reflects efficient working capital management in steel distribution.", "EPS grew 50.5% annualised as Canadian industrial activity and steel prices recovered strongly.", "Dividend yield of 3.5% backed by consistent cash generation from distribution operations."]),
    375: ('Seiren Co Ltd', 'Japanese functional fabric innovator. Consistent yield.', 'Advanced textile technology.', "Seiren is a Japanese specialty textile company producing functional fabrics for automotive interiors, sportswear, and industrial applications. The company has pioneered digital fabric printing technology and produces high-performance materials for Toyota, Honda, and other major manufacturers.", 'Japanese textile innovation. Steady income.', 'Advanced materials compounder.', "A Japanese specialty textile company with an 11.7% ROIC producing functional fabrics for automotive interiors and sportswear. Seiren's digital printing technology and high-performance materials are specified by major Japanese automakers — creating long-term supply relationships.", ["Functional fabrics for automotive interiors, sportswear and industrial applications.", "Digital fabric printing pioneer — proprietary technology for Toyota, Honda and other automakers.", "ROIC of 11.7% reflects consistent returns from specialised textile technology.", "Dividend yield of 2.6% backed by steady demand from long-term automotive supply relationships."]),
    376: ('Shoe Carnival Inc', 'US family footwear retailer. Dividend grower.', 'US family footwear.', "Shoe Carnival is a US specialty footwear retailer operating over 400 stores across the US and Puerto Rico, targeting value-conscious families. The company focuses on branded athletic and casual footwear at competitive price points, with a growing e-commerce presence.", 'US footwear retail. Consistent compounder.', 'US footwear compounder.', "A US specialty footwear retailer with a 13.5% ROIC and EPS growth of 27.4% annualised. Shoe Carnival's value positioning in branded athletic and casual footwear targets a resilient consumer segment — families seeking quality brands at competitive prices.", ["Specialty footwear retailer across 400+ US stores targeting value-conscious family buyers.", "ROIC of 13.5% reflects efficient inventory management and consistent retail execution.", "EPS grew 27.4% annualised as store expansion and e-commerce growth drove earnings higher.", "Dividend yield of 3.2% with consistent dividend growth from strong free cash flow."]),
    377: ('Socfinasia SA Holding', 'Asian plantation company. Exceptional yield.', 'Asian rubber and palm oil.', "Socfinasia is a Luxembourg-listed holding company with rubber and oil palm plantations across Cambodia, Vietnam, and Indonesia. The company is part of the Socfin group and generates income from agricultural commodities with long-life plantation assets.", 'Asian plantations. Exceptional yield.', 'Agricultural commodity income.', "A Luxembourg-listed Asian plantation company with a 30.5% ROIC and an 18.8% dividend yield from rubber and oil palm operations across Southeast Asia. Socfinasia's long-life plantation assets generate substantial commodity income with minimal ongoing capital requirements.", ["Rubber and oil palm plantations in Cambodia, Vietnam and Indonesia — long-life agricultural assets.", "ROIC of 30.5% reflects high cash generation from mature plantation assets.", "EPS grew 31.6% annualised as commodity prices and plantation productivity improved.", "Dividend yield of 18.8% — exceptional income reflecting large cash distributions from plantation income."]),
}

with open(CARDS_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

updated = 0
for card_id, (company, tag, tagBold, tagFull, pick, pickBold, pickFull, bullets) in descriptions.items():
    pattern = re.compile(
        rf"(id: {card_id}, type: 'KING'.*?tag: ')[^']*('.*?tagBold: ')[^']*('.*?tagFull: \")[^\"]*(\",.*?pick: ')[^']*('.*?pickBold: ')[^']*('.*?pickFull: \")[^\"]*(\",)",
        re.DOTALL
    )
    replacement = rf"\g<1>{tag}\g<2>{tagBold}\g<3>{tagFull}\g<4>{pick}\g<5>{pickBold}\g<6>{pickFull}\g<7>"
    new_content = pattern.sub(replacement, content)
    if new_content != content:
        content = new_content
        updated += 1
        print(f"✅ {card_id}: {company}")
    else:
        print(f"❌ {card_id}: pattern not matched")
    bullets_str = ', '.join([f'"{b}"' for b in bullets])
    bullets_pattern = re.compile(rf"(id: {card_id},.*?bullets: \[)[^\]]*\]", re.DOTALL)
    content = bullets_pattern.sub(rf"\g<1>{bullets_str}]", content)

with open(CARDS_PATH, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n✅ Updated {updated}/20 KING cards")
print(f"Remaining generic: {content.count('operates in')}")
