import re

CARDS_PATH = '/Users/radekmajewski/Downloads/valujack/public/cards.js'

descriptions = {
    378: ('Strategic Education Inc', 'US online higher education. Consistent yield.', 'Online education provider.', "Strategic Education operates Strayer University and Capella University, two of the largest online universities in the US. The company serves working adults seeking flexible degree programmes in business, technology, and healthcare — a structurally growing market as workers upskill throughout their careers.", 'Online education. Defensive compounder.', 'Adult education compounder.', "A US online university operator with a 2.9% dividend yield serving working adults through Strayer and Capella universities. Strategic Education benefits from structural demand for flexible, career-focused higher education as workers increasingly pursue online degrees while employed.", ["Strayer University and Capella University — two of the largest US online universities.", "Serves working adults seeking flexible degree programmes in business, technology and healthcare.", "Structural demand for online education as workforce upskilling becomes a career-long necessity.", "Dividend yield of 2.9% backed by consistent tuition revenue from a large enrolled student base."]),
    379: ('Systemair', 'Swedish ventilation systems. Consistent compounder.', 'Ventilation technology leader.', "Systemair is a Swedish ventilation equipment manufacturer operating across 50 countries. The company produces fans, air handling units, and ventilation systems for residential, commercial, and industrial buildings — benefiting from growing regulatory requirements for indoor air quality and energy efficiency.", 'Ventilation systems. Consistent compounder.', 'Swedish industrial compounder.', "A Swedish ventilation equipment manufacturer with a 12.2% ROIC and EPS growth of 11.3% annualised operating across 50 countries. Systemair benefits from tightening building energy efficiency regulations across Europe — ventilation systems with heat recovery are increasingly mandated in new construction.", ["Ventilation fans, air handling units and systems for residential, commercial and industrial buildings.", "Operations across 50 countries with growing demand from building energy efficiency regulations.", "ROIC of 12.2% reflects consistent returns from a global ventilation equipment business.", "Dividend yield of 1.7% with consistent growth as earnings compound steadily."]),
    380: ('The Marzetti Co', 'US specialty food. Consistent dividend.', 'US specialty sauces and dressings.', "Lancaster Colony, through its Marzetti brand, produces specialty salad dressings, dips, and frozen breads sold in US retail and food service. The Marzetti brand has strong retail shelf presence and benefits from growing consumer demand for premium refrigerated dressings.", 'Specialty food. Consistent income.', 'US food compounder.', "A US specialty food company producing Marzetti dressings, dips, and specialty foods for retail and food service with a 2.8% dividend yield and ROIC of 15.8%. The Marzetti brand benefits from strong retail shelf presence and consistent consumer demand for premium refrigerated dressings.", ["Marzetti salad dressings, dips and specialty foods for US retail and food service channels.", "Strong retail shelf presence with consistent consumer loyalty to the Marzetti brand.", "ROIC of 15.8% reflects steady returns from branded specialty food with pricing power.", "Dividend yield of 2.8% backed by consistent free cash flow from a defensive food business."]),
    381: ('TORM Plc', 'Product tanker operator. High yield.', 'Product tanker specialist.', "TORM is one of the world's largest product tanker companies, transporting refined petroleum products — gasoline, diesel, jet fuel — across global trade routes. The company operates a modern, fuel-efficient fleet and benefits from structurally strong demand for refined product transportation.", 'Product tankers. High yield income.', 'Tanker income play.', "One of the world's largest product tanker operators with a 6.7% dividend yield and ROIC of 16.7%. TORM transports refined petroleum products globally on a modern, fuel-efficient fleet. EPS grew 19.6% annualised as refined product trade volumes and tanker rates remained elevated.", ["One of the world's largest product tanker fleets — gasoline, diesel and jet fuel transport.", "Modern, fuel-efficient fleet provides cost advantage and lower emissions per tonne-mile.", "ROIC of 16.7% reflects strong tanker market conditions and efficient fleet management.", "Dividend yield of 6.7% backed by substantial free cash flow from elevated tanker rates."]),
    382: ('Tourmaline Oil Corp', 'Canadian natural gas producer. High yield.', 'Canadian gas producer.', "Tourmaline is Canada's largest natural gas producer, operating in the Western Canadian Sedimentary Basin. The company has a low-cost production base, a strong balance sheet, and a policy of returning excess cash to shareholders through base and special dividends.", 'Canadian gas. High yield compounder.', 'Canadian energy income.', "Canada's largest natural gas producer with a 5.5% dividend yield and ROIC of 12.3%. Tourmaline's low-cost production base in the Western Canadian Sedimentary Basin and strong balance sheet support a generous dividend policy including special dividends in high-price environments.", ["Canada's largest natural gas producer — low-cost operations in the Western Canadian Sedimentary Basin.", "Strong balance sheet with minimal debt supports generous base and special dividend policy.", "ROIC of 12.3% reflects efficient capital deployment in low-cost natural gas production.", "Dividend yield of 5.5% with additional special dividends paid in high natural gas price environments."]),
    383: ('UIE Plc', 'Palm oil investment holding. Steady yield.', 'Palm oil investment holding.', "UIE is a Copenhagen-listed investment holding company with controlling stakes in palm oil and other agricultural commodity businesses across Southeast Asia and West Africa. The company's primary asset is United Plantations, a high-quality Malaysian palm oil producer.", 'Palm oil holding. Steady income.', 'Agricultural holding income.', "A Copenhagen-listed agricultural investment holding company with a 3.2% dividend yield and primary exposure to United Plantations — one of Malaysia's highest-quality palm oil producers. UIE provides indirect access to palm oil economics with a diversified holding structure.", ["Investment holding company with controlling stake in United Plantations — premium Malaysian palm oil.", "Palm oil and agricultural commodity exposure across Southeast Asia and West Africa.", "ROIC of 9.3% reflects consistent returns from high-quality plantation asset management.", "Dividend yield of 3.2% backed by steady dividend income from portfolio plantation companies."]),
    384: ('Universal Display Corp', 'US OLED technology licensor. High ROIC.', 'OLED technology monopoly.', "Universal Display Corporation holds the foundational patents for OLED (organic light-emitting diode) display technology used in smartphones, TVs, and wearables. The company licenses its technology to every major display manufacturer — Samsung, LG, BOE — earning royalties on billions of OLED displays shipped annually.", 'OLED patents. Royalty compounder.', 'Display technology licensor.', "The world's dominant OLED technology licensor with a 22.6% ROIC and EPS growth of 12.7% annualised. Universal Display earns royalties on virtually every OLED display manufactured — from iPhone screens to Samsung TVs. The 1.8% dividend yield is modest relative to substantial cash generation.", ["Foundational OLED display technology patents — royalties on every OLED display manufactured.", "Licenses to Samsung, LG, BOE and all major display manufacturers globally.", "ROIC of 22.6% reflects extraordinary intellectual property economics from patent licensing.", "Dividend yield of 1.8% with significant additional cash generation retained for growth."]),
    385: ('Viscofan SA', 'Spanish food casings. Dominant niche.', 'Food casings monopoly.', "Viscofan is a Spanish manufacturer of artificial food casings — the collagen, cellulose, and plastic materials used to encase sausages and processed meats globally. The company holds a dominant global market position in collagen casings and serves every major meat processor worldwide.", 'Food casings. Dominant niche compounder.', 'Global food casings leader.', "A Spanish food casings manufacturer with a 15.1% ROIC and a 5.5% dividend yield. Viscofan produces the collagen, cellulose, and plastic casings used in virtually all processed meat products globally. The company's dominant market position and long customer relationships create a highly defensible business.", ["Global leader in collagen, cellulose and plastic food casings for the processed meat industry.", "Serves every major meat processor worldwide — dominant market position with high switching costs.", "ROIC of 15.1% reflects consistent returns from a niche, defensible food ingredient business.", "Dividend yield of 5.5% backed by consistent free cash flow from a structurally stable food business."]),
}

with open(CARDS_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

updated = 0
for card_id, (company, tag, tagBold, tagFull, pick, pickBold, pickFull, bullets) in descriptions.items():
    pattern = re.compile(
        rf"(id: {card_id}, type: 'KING'.*?tag: ')[^']*('.*?tagBold: ')[^']*('.*?tagFull: \")[^\"]*(\",.*?pick: ')[^']*('.*?pickBold: ')[^']*('.*?pickFull: \")[^\"]*(\",)",
        re.DOTALL
    )
    replacement = rf"\g<1>{tag}\g<2>{tagBold}\g<3>{tagFull}\g<4>{pick}\g<5>{pickBold}\g<6>{pickFull}\g<7>"
    new_content = pattern.sub(replacement, content)
    if new_content != content:
        content = new_content
        updated += 1
        print(f"✅ {card_id}: {company}")
    else:
        print(f"❌ {card_id}: pattern not matched")
    bullets_str = ', '.join([f'"{b}"' for b in bullets])
    bullets_pattern = re.compile(rf"(id: {card_id},.*?bullets: \[)[^\]]*\]", re.DOTALL)
    content = bullets_pattern.sub(rf"\g<1>{bullets_str}]", content)

with open(CARDS_PATH, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n✅ Updated {updated}/8 KING cards")
print(f"Remaining generic: {content.count('operates in')}")
