import re

CARDS_PATH = '/Users/radekmajewski/Downloads/valujack/public/cards.js'

descriptions = {
    446: ('Saputo Inc', 'Canadian dairy products giant. Consistent compounder.', 'Canadian dairy leader.', "Saputo is one of the largest dairy processors in the world, producing cheese, fluid milk, and dairy ingredients across Canada, the US, the UK, Australia, and Argentina. The company has built its position through decades of disciplined acquisitions of regional dairy businesses.", 'Global dairy. Consistent compounder.', 'Dairy products compounder.', "One of the world's largest dairy processors with a 6.5% ROIC operating across Canada, the US, UK, and Australia. Saputo has built a global dairy platform through disciplined acquisitions — producing cheese, milk, and dairy ingredients for retail and foodservice customers worldwide.", ["One of the world's largest dairy processors — cheese, milk and dairy ingredients globally.", "Operations across Canada, USA, UK, Australia and Argentina — highly diversified dairy platform.", "ROIC of 6.5% with improving trajectory as integration of acquisitions drives efficiency gains.", "Consistent demand from retail and foodservice dairy customers across developed markets."]),
    447: ('Savaria Corp', 'Canadian accessibility solutions. Recovery momentum.', 'Accessibility solutions provider.', "Savaria is a Canadian manufacturer of accessibility solutions — stairlifts, vertical platform lifts, wheelchair-accessible vehicles, and patient handling equipment. The company serves an ageing population globally with products that enable independent living and mobility.", 'Ageing population. Recovery momentum.', 'Accessibility compounder.', "A Canadian accessibility solutions company with a 13.0% ROIC serving the structural trend of global population ageing. Savaria produces stairlifts, platform lifts, and mobility vehicles — products with growing structural demand as populations age across developed markets.", ["Stairlifts, platform lifts and wheelchair-accessible vehicles for ageing populations.", "ROIC of 13.0% reflects consistent returns from a structurally growing accessibility market.", "Structural demand growth as global populations age across North America and Europe.", "Recovery momentum following integration of acquisitions that temporarily diluted margins."]),
    448: ('Scanfil', 'Finnish electronics manufacturing services. Consistent compounder.', 'Nordic electronics manufacturer.', "Scanfil is a Finnish electronics manufacturing services company producing complex assemblies for industrial, medtech, and energy technology customers. The company operates factories across Europe and Asia, serving customers who require reliable, quality-certified manufacturing in regulated industries.", 'Nordic electronics manufacturing. Quality compounder.', 'Electronics manufacturing compounder.', "A Finnish electronics manufacturing services company with a 13.7% ROIC and consistent demand from industrial, medtech, and energy technology customers. Scanfil operates certified manufacturing facilities across Europe and Asia — building long-term relationships in regulated end markets.", ["Complex electronics assemblies for industrial, medtech and energy technology customers.", "ROIC of 13.7% reflects consistent returns from quality-certified manufacturing services.", "Operations across Europe and Asia serving regulated industries with high quality requirements.", "EPS growing steadily as medtech and industrial electronics outsourcing expands."]),
    449: ('Seaboard Corp', 'US diversified agribusiness and shipping. Exceptional value.', 'US agribusiness conglomerate.', "Seaboard is a US diversified agribusiness and transportation conglomerate operating pork processing, ocean shipping, commodity trading, and power generation across multiple continents. The company trades at a significant discount to its sum-of-parts value.", 'Diversified agribusiness. Exceptional value.', 'Agribusiness conglomerate value.', "A US diversified agribusiness and ocean shipping conglomerate with a 9.0% ROIC and EPS growth of 16.1% annualised. Seaboard operates pork processing, ocean cargo shipping, and commodity trading — a complex multi-business conglomerate trading at a substantial discount to intrinsic value.", ["Diversified agribusiness — pork processing, ocean shipping and commodity trading.", "ROIC of 9.0% across a highly diversified portfolio of food and transportation businesses.", "EPS grew 16.1% annualised with consistent performance across diversified business segments.", "Trades at a significant discount to sum-of-parts value — classic conglomerate discount."]),
    450: ('Seneca Foods Corp', 'US canned fruits and vegetables. Consistent compounder.', 'US canned food producer.', "Seneca Foods is a US processor and marketer of canned and frozen fruits and vegetables, selling under the Seneca, Libby, and private-label brands. The company is the largest private-label canned vegetable producer in the US — a defensive, recession-resistant food business.", 'Canned vegetables. Defensive compounder.', 'Defensive food compounder.', "A US canned fruit and vegetable producer with a 9.0% ROIC and consistent demand from retail and foodservice customers. Seneca Foods is the largest private-label canned vegetable producer in the US — a recession-resistant business benefiting from consumer trade-down to value food options.", ["Canned and frozen fruits and vegetables under Seneca, Libby and private-label brands.", "Largest private-label canned vegetable producer in the US — scale creates cost advantages.", "ROIC of 9.0% reflects consistent returns from a recession-resistant defensive food business.", "Revenue growing 4.6% annualised with consistent demand from retail and foodservice channels."]),
    451: ('Sipef SA', 'Belgian palm oil plantation group. High growth.', 'Tropical plantation group.', "Sipef is a Belgian tropical agribusiness group operating oil palm, rubber, and tea plantations in Indonesia, Papua New Guinea, and Ivory Coast. The company produces sustainable certified palm oil and plantation commodities for food, personal care, and industrial customers globally.", 'Sustainable palm oil. High growth.', 'Tropical agribusiness compounder.', "A Belgian tropical plantation group with a 12.2% ROIC and EPS growth of 54.7% annualised. Sipef operates oil palm, rubber, and tea plantations across Indonesia, Papua New Guinea, and Ivory Coast — producing sustainable certified commodities with growing demand from food and personal care industries.", ["Oil palm, rubber and tea plantations in Indonesia, Papua New Guinea and Ivory Coast.", "ROIC of 12.2% reflects consistent returns from mature tropical plantation assets.", "EPS grew 54.7% annualised as palm oil prices and plantation productivity improved.", "Revenue grew 29.3% annualised driven by higher commodity prices and plantation expansion."]),
    452: ('SOL SpA', 'Italian industrial gases. Consistent compounder.', 'Italian industrial gases.', "SOL is an Italian industrial and medical gases company, producing and distributing oxygen, nitrogen, argon, and specialty gases across Italy, Central Europe, and the Middle East. The company also provides home healthcare services using medical oxygen and respiratory equipment.", 'Industrial gases. Consistent compounder.', 'Gas distribution compounder.', "An Italian industrial and medical gases company with a 9.9% ROIC and revenue growth of 11.4% annualised. SOL distributes industrial gases and provides home healthcare services across Italy and Central Europe — a defensive, infrastructure-based business with recurring customer relationships.", ["Industrial and medical gases — oxygen, nitrogen, argon and specialty gases.", "Home healthcare services with medical oxygen and respiratory equipment for patients.", "ROIC of 9.9% reflects consistent returns from gas distribution infrastructure.", "Revenue grew 11.4% annualised with steady industrial and healthcare gas demand growth."]),
    453: ('Solstad Offshore', 'Norwegian offshore support vessels. Recovery momentum.', 'Offshore support vessel operator.', "Solstad Offshore is a Norwegian operator of offshore support vessels serving oil and gas exploration and production, as well as offshore wind installation. The company operates anchor handling tugs, platform supply vessels, and construction support vessels globally.", 'Offshore vessels. Recovery momentum.', 'Offshore support recovery.', "A Norwegian offshore support vessel operator with a 21.8% ROIC showing recovery momentum as offshore oil and gas and wind installation demand increases. Solstad fleet serves oil exploration and offshore wind — positioned at the intersection of conventional energy and the energy transition.", ["Offshore support vessels for oil and gas exploration and offshore wind installation.", "ROIC of 21.8% reflects improving utilisation as offshore activity recovers strongly.", "Positioned at intersection of conventional energy and offshore wind energy transition.", "Revenue growing 10.0% annualised as offshore activity and vessel day rates improve."]),
    454: ('StealthGas Inc', 'Marshall Islands small LPG tanker operator. High yield.', 'Small LPG tanker fleet.', "StealthGas operates one of the largest fleets of small LPG carriers globally — pressurised gas tankers transporting propane, butane, and petrochemical gases on short and medium-haul trade routes. The company serves regional LPG distribution markets across Europe, the Middle East, and Asia.", 'Small LPG tankers. High yield income.', 'Regional LPG tanker income.', "A Marshall Islands small LPG tanker operator with a 10.2% ROIC and EPS growth of 40.4% annualised. StealthGas operates pressurised LPG carriers serving regional propane and butane distribution markets — a niche segment with limited vessel supply and consistent demand from LPG heating and petrochemical markets.", ["One of the largest small LPG carrier fleets globally — propane, butane and petrochemical gases.", "ROIC of 10.2% reflects consistent fleet utilisation in regional LPG distribution markets.", "EPS grew 40.4% annualised as small LPG tanker rates and utilisation improved.", "Niche vessel segment with limited new supply supporting sustained rate improvement."]),
    455: ('Teekay Tankers Ltd', 'Canadian mid-size crude tanker operator. High ROIC.', 'Mid-size crude tanker operator.', "Teekay Tankers operates a fleet of Suezmax and Aframax crude oil tankers serving medium-haul crude trade routes globally. The company benefits from strong crude tanker demand as Russian oil rerouting and US crude export growth have structurally lengthened average voyage distances.", 'Crude tankers. High ROIC income.', 'Crude tanker income play.', "A Canadian mid-size crude tanker operator with a 28.0% ROIC and EPS growth of 31.4% annualised. Teekay Tankers Suezmax and Aframax fleet benefits from structurally longer crude voyage distances as Russian oil sanctions reroute trade and US crude exports grow.", ["Suezmax and Aframax crude tanker fleet serving medium-haul global crude trade routes.", "ROIC of 28.0% reflects strong crude tanker market conditions and fleet efficiency.", "EPS grew 31.4% annualised as Russian oil rerouting lengthened average voyage distances.", "US crude export growth adding sustained incremental tonne-mile demand."]),
    456: ('Thermon Group Holdings Inc', 'US industrial heat tracing. High growth.', 'Industrial heat tracing specialist.', "Thermon manufactures electric heat tracing systems — the cables and controls that prevent industrial pipes from freezing in cold environments. The company serves LNG terminals, refineries, chemical plants, and power facilities where pipe freeze protection is safety-critical.", 'Heat tracing systems. High growth.', 'Industrial heat tracing compounder.', "A US industrial heat tracing company with an 8.9% ROIC and EPS growth of 126.5% annualised from a low base. Thermon electric heat tracing systems prevent pipe freezing at LNG terminals, refineries, and chemical plants — safety-critical infrastructure with growing demand from LNG facility construction.", ["Electric heat tracing for LNG terminals, refineries, chemical plants and power facilities.", "ROIC of 8.9% with improving trajectory as LNG and industrial project demand accelerates.", "EPS grew 126.5% annualised as LNG terminal construction drove heat tracing demand higher.", "Safety-critical pipe freeze protection — essential for cold-climate industrial operations."]),
    457: ('Topaz Energy Corp', 'Canadian energy royalty and infrastructure. High growth.', 'Canadian energy royalty.', "Topaz Energy is a Canadian royalty and infrastructure company with royalty interests and infrastructure assets across the Western Canadian Sedimentary Basin. The company earns royalties on oil and gas production from Tourmaline and other producers without bearing exploration or production risk.", 'Canadian energy royalties. High growth.', 'Energy royalty compounder.', "A Canadian energy royalty company with a 5.8% ROIC and EPS growth of 94.7% annualised. Topaz earns royalties on oil and gas production from Tourmaline and other Western Canadian producers — a pure royalty model that benefits from production growth without bearing operating risk.", ["Royalty interests and infrastructure assets across Western Canadian Sedimentary Basin.", "ROIC of 5.8% from a pure royalty model with minimal capital requirements.", "EPS grew 94.7% annualised as royalty production volumes and commodity prices improved.", "Revenue growing 8.3% annualised as underlying production from royalty lands expands."]),
    458: ('Toromont Industries Ltd', 'Canadian Caterpillar dealer. Quality compounder.', 'Canadian equipment dealer.', "Toromont Industries is the authorised Caterpillar equipment dealer for Ontario, Manitoba, and the Atlantic provinces — selling, renting, and servicing heavy construction and mining equipment. The company also operates CIMCO, a refrigeration systems business serving arenas and food processing.", 'Caterpillar dealer. Quality compounder.', 'Canadian equipment compounder.', "A Canadian Caterpillar equipment dealer with a 16.4% ROIC and EPS growth of 14.5% annualised. Toromont sells, rents, and services Caterpillar equipment across Ontario and Atlantic Canada — a franchised dealership with high-margin aftermarket parts and service revenue.", ["Authorised Caterpillar dealer for Ontario, Manitoba and Atlantic Canada.", "ROIC of 16.4% reflects high-margin parts and service revenue from large equipment fleet.", "EPS grew 14.5% annualised with consistent aftermarket demand from installed equipment base.", "CIMCO refrigeration systems division provides diversification into food and arena cooling."]),
    459: ('Total Energy Services Inc', 'Canadian oilfield services. High growth.', 'Canadian energy services compounder.', "Total Energy Services is a Canadian oilfield services company providing contract drilling, well servicing, compression, and production testing to oil and gas producers across Western Canada and the US. The company has grown organically and through acquisitions into a diversified energy services provider.", 'Canadian oilfield services. High growth.', 'Energy services compounder.', "A Canadian diversified oilfield services company with an 11.0% ROIC and EPS growth of 37.6% annualised. Total Energy provides contract drilling, compression, and well servicing across Western Canada and the US — a diversified services model reducing dependence on any single activity.", ["Contract drilling, well servicing, compression and production testing in Western Canada and US.", "ROIC of 11.0% reflects consistent returns across diversified oilfield service activities.", "EPS grew 37.6% annualised as Canadian drilling activity and service pricing strengthened.", "Revenue grew 17.4% annualised with organic growth and disciplined acquisition expansion."]),
    460: ('Trican Well Service Ltd', 'Canadian pressure pumping services. High ROIC.', 'Canadian pressure pumping specialist.', "Trican Well Service is a Canadian pressure pumping company providing hydraulic fracturing and cementing services to oil and gas producers in Western Canada. The company is one of Canada's largest pressure pumpers — essential for unlocking tight oil and gas from shale and deep formations.", 'Pressure pumping. High ROIC momentum.', 'Canadian fracturing compounder.', "A Canadian pressure pumping company with a 12.9% ROIC and EPS growth of 21.7% annualised. Trican provides hydraulic fracturing and cementing services essential for Western Canadian tight oil and gas production — a recurring services business with consistent demand from multi-well pad drilling programmes.", ["Hydraulic fracturing and cementing for Western Canadian tight oil and gas producers.", "ROIC of 12.9% reflects consistent returns from essential pressure pumping services.", "EPS grew 21.7% annualised as Canadian tight oil drilling activity expanded.", "Revenue grew 11.8% annualised with multi-well pad drilling driving sustained service demand."]),
    462: ('Valeura Energy Inc', 'Canadian oil producer in Thailand. Growth momentum.', 'Thailand oil producer.', "Valeura Energy is a Canadian oil production company operating offshore concessions in the Gulf of Thailand. The company acquired producing assets from KrisEnergy and has grown production significantly — generating strong free cash flow from its Gulf of Thailand oil fields.", 'Thailand offshore oil. Growth momentum.', 'Emerging market oil producer.', "A Canadian oil producer operating in the Gulf of Thailand with a 5.4% ROIC and EPS growth of 23.8% annualised. Valeura acquired producing Gulf of Thailand concessions and has grown production and cash flow significantly from its offshore oil fields.", ["Offshore oil production from concessions in the Gulf of Thailand.", "ROIC of 5.4% with improving trajectory as production growth drives cash flow higher.", "EPS grew 23.8% annualised as production from Gulf of Thailand fields expanded.", "Strong free cash flow generation from low-cost Gulf of Thailand offshore production."]),
    463: ('Village Super Market Inc', 'US ShopRite grocery operator. Consistent compounder.', 'US ShopRite grocery operator.', "Village Super Market operates ShopRite supermarkets across New Jersey, Maryland, and Florida under a cooperative franchise model. The company serves dense suburban communities with full-service grocery stores — a defensive, recession-resistant food retail business.", 'Grocery retail. Consistent compounder.', 'Defensive grocery compounder.', "A US ShopRite cooperative supermarket operator with an 8.4% ROIC and EPS growth of 22.7% annualised. Village Super Market serves dense New Jersey and Maryland suburban communities with full-service grocery stores — a recession-resistant food retail business with consistent consumer demand.", ["ShopRite supermarkets across New Jersey, Maryland and Florida — dense suburban markets.", "ROIC of 8.4% reflects consistent returns from a defensive grocery retail operation.", "EPS grew 22.7% annualised with consistent consumer demand from established suburban locations.", "Recession-resistant food retail with consistent demand through economic cycles."]),
    464: ('Western Digital Corp', 'US hard drive and flash storage giant. High ROIC recovery.', 'Data storage technology leader.', "Western Digital is one of the world's largest data storage companies, producing hard disk drives and NAND flash memory for cloud, enterprise, and consumer markets. The company is benefiting from surging data centre storage demand as AI infrastructure buildout drives unprecedented storage requirements.", 'Data storage. AI infrastructure tailwind.', 'Storage technology recovery.', "A US data storage company with a 59.5% ROIC recovering strongly as AI infrastructure investment drives unprecedented cloud storage demand. Western Digital produces hard disk drives and NAND flash for the world's largest hyperscale data centres — a direct beneficiary of the AI data storage buildout.", ["Hard disk drives and NAND flash memory for cloud, enterprise and consumer storage.", "ROIC of 59.5% reflects strong recovery as data centre storage demand surged.", "EPS grew 33.6% annualised as AI infrastructure buildout drove unprecedented storage demand.", "Revenue grew 28.1% annualised as hyperscale cloud storage investment accelerated."]),
    465: ('Westinghouse Air Brake', 'US rail technology and services. Quality compounder.', 'Rail technology leader.', "Wabtec Corporation is a US manufacturer of railway equipment, components, and digital solutions for freight and transit rail worldwide. The company produces locomotive technology, braking systems, and digital train management software — serving the global rail industry with mission-critical equipment.", 'Rail technology. Quality compounder.', 'Railway technology compounder.', "A US railway technology company with a 7.2% ROIC and EPS growth of 25.7% annualised. Wabtec produces locomotive technology, braking systems, and digital train management solutions for global freight and transit rail — a business with strong aftermarket revenue from its large installed equipment base.", ["Locomotive technology, braking systems and digital train management for global rail.", "ROIC of 7.2% with improving trajectory as aftermarket services revenue grows.", "EPS grew 25.7% annualised as rail technology upgrades and services demand expanded.", "Large installed equipment base generates high-margin recurring parts and service revenue."]),
}

with open(CARDS_PATH, 'r', encoding='utf-8') as f:
    content = f.read()

updated = 0
for card_id, (company, tag, tagBold, tagFull, pick, pickBold, pickFull, bullets) in descriptions.items():
    pattern = re.compile(
        rf"(id: {card_id}, type: 'JACK'.*?tag: ')[^']*('.*?tagBold: ')[^']*('.*?tagFull: \")[^\"]*(\",.*?pick: ')[^']*('.*?pickBold: ')[^']*('.*?pickFull: \")[^\"]*(\",)",
        re.DOTALL
    )
    replacement = rf"\g<1>{tag}\g<2>{tagBold}\g<3>{tagFull}\g<4>{pick}\g<5>{pickBold}\g<6>{pickFull}\g<7>"
    new_content = pattern.sub(replacement, content)
    if new_content != content:
        content = new_content
        updated += 1
        print(f"✅ {card_id}: {company}")
    else:
        print(f"❌ {card_id}: pattern not matched")
    bullets_str = ', '.join([f'"{b}"' for b in bullets])
    bullets_pattern = re.compile(rf"(id: {card_id},.*?bullets: \[)[^\]]*\]", re.DOTALL)
    content = bullets_pattern.sub(rf"\g<1>{bullets_str}]", content)

with open(CARDS_PATH, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n✅ Updated {updated}/20 JACK cards")
print(f"Remaining generic: {content.count('operates in')}")
