
import re
CARDS_PATH = '/Users/radekmajewski/Downloads/valujack/public/cards.js'
descriptions = {
    620: ('Flotek Industries Inc', 'US oilfield chemistry. High ROIC growth.', 'Oilfield chemistry growth.', "Flotek Industries provides specialty chemistry systems for oil and gas well stimulation and production. The company has improved its financial performance significantly from its specialty chemistry portfolio for US shale producers.", 'Oilfield chemistry. High ROIC growth.', 'Specialty chemistry compounder.', "A US oilfield specialty chemistry company with a 20.0% ROIC and EPS growth of 15.7% annualised. Flotek provides well stimulation chemistry for US shale producers — improving financial performance from a focused specialty chemistry portfolio.", ["Specialty chemistry for oil and gas well stimulation and production enhancement.", "ROIC of 20.0% reflects improving returns from focused specialty chemistry operations.", "EPS grew 15.7% annualised as oilfield chemistry demand and margins improved.", "Revenue grew 26.9% annualised as US shale drilling activity and chemistry adoption expanded."]),
    621: ('Freshpet Inc', 'US fresh refrigerated pet food. High growth.', 'Fresh pet food pioneer.', "Freshpet pioneers fresh refrigerated pet food — a premium alternative to dry kibble for dogs and cats. The company has built a national refrigerated distribution network across US retail stores and is growing rapidly as pet owners trade up to premium fresh food.", 'Fresh pet food. High growth momentum.', 'Pet food growth compounder.', "A US fresh refrigerated pet food company with a 9.8% ROIC and EPS growth of 106.6% annualised. Freshpet is pioneering the fresh pet food category — a structurally growing market as pet owners increasingly trade up to premium fresh food.", ["Fresh refrigerated dog and cat food — premium alternative to dry kibble.", "ROIC of 9.8% with improving trajectory as distribution scale drives operating leverage.", "EPS grew 106.6% annualised as fresh pet food category adoption accelerated.", "Revenue grew 13.0% annualised with consistent new household and retail door expansion."]),
    622: ('Glenveagh Properties PLC', 'Irish homebuilder. Exceptional growth momentum.', 'Irish housing growth play.', "Glenveagh Properties is an Irish homebuilder benefiting from one of Europe's most severe housing shortages. The company is scaling production rapidly in Dublin and Leinster — generating exceptional earnings growth as housing completions and selling prices expand.", 'Irish housing. Exceptional growth.', 'Irish housing growth compounder.', "An Irish homebuilder with a 12.9% ROIC and EPS growth of 73.7% annualised scaling production in Europe's most undersupplied housing market. Glenveagh rapid volume growth in Dublin and Leinster is driving exceptional earnings expansion.", ["Homebuilder scaling production across Dublin and Leinster in Ireland.", "ROIC of 12.9% improving as housing production scales and fixed costs are absorbed.", "EPS grew 73.7% annualised as housing completions and selling prices expanded strongly.", "Revenue grew 79.9% annualised with rapid production scale-up across Irish housing markets."]),
    623: ('Gorman-Rupp Co', 'US self-priming pump manufacturer. Growth momentum.', 'Pump manufacturer growth.', "Gorman-Rupp is a leading manufacturer of self-priming pumps for water, wastewater, construction, and military applications. The company is growing earnings strongly from infrastructure spending and its stock shows technical momentum consistent with CANSLIM growth criteria.", 'Pump manufacturer. Growth momentum.', 'Industrial pump growth compounder.', "A US pump manufacturer with a 7.3% ROIC and EPS growth of 15.8% annualised. Gorman-Rupp self-priming pumps serve water utilities, construction, and military — growing earnings from infrastructure spending and pump replacement demand.", ["Self-priming pumps for water, wastewater, construction and military applications.", "ROIC of 7.3% with improving trajectory as infrastructure spending drives pump demand.", "EPS grew 15.8% annualised as water infrastructure and construction pump demand expanded.", "Over 80 consecutive years of dividend payments — exceptional dividend consistency."]),
    624: ('Guidewire Software Inc', 'US insurance SaaS platform. High ROIC.', 'Insurance SaaS platform.', "Guidewire provides cloud-based core system software for property and casualty insurance companies. The company is the dominant platform for P&C insurance core systems globally, with strong switching costs from deep operational integration.", 'Insurance SaaS. High ROIC growth.', 'Insurance tech compounder.', "A US insurance technology company with a 14.4% ROIC and EPS growth of 37.1% annualised. Guidewire is the dominant cloud platform for P&C insurance core systems — deep integration creates high switching costs and consistent recurring subscription revenue.", ["Cloud-based policy, billing and claims software for property and casualty insurers.", "ROIC of 14.4% reflects strong returns from dominant insurance SaaS platform economics.", "EPS grew 37.1% annualised as cloud migration and new insurer wins accelerated.", "Revenue grew 23.7% annualised with consistent SaaS transition and new customer additions."]),
    625: ('Indivior Pharmaceuticals Inc', 'UK opioid addiction treatment. Exceptional ROIC.', 'Opioid addiction treatment.', "Indivior focuses on opioid addiction treatment with Sublocade — a monthly injectable buprenorphine for opioid use disorder. The drug addresses the US opioid crisis with a superior formulation that improves treatment adherence over daily oral alternatives.", 'Opioid addiction drug. Exceptional ROIC.', 'Addiction treatment compounder.', "A UK opioid addiction treatment company with a 225.8% ROIC from Sublocade. Indivior treats a massive US opioid addiction patient population — exceptional capital efficiency from a commercially successful addiction medicine with growing monthly prescription volumes.", ["Sublocade monthly injectable buprenorphine for opioid use disorder treatment.", "ROIC of 225.8% — extraordinary returns from opioid addiction drug pricing and volume.", "EPS grew 29.8% annualised as Sublocade prescriptions grew consistently.", "Massive US opioid addiction patient population provides large and growing market."]),
    626: ('Infracom', 'Swedish internet infrastructure. High ROIC.', 'Swedish internet infrastructure.', "Infracom is a Swedish provider of internet and broadband infrastructure services — fibre networks, managed connectivity, and cloud services for Swedish businesses and municipalities. The company benefits from growing demand for high-speed connectivity.", 'Swedish connectivity. High ROIC compounder.', 'Broadband infrastructure compounder.', "A Swedish internet infrastructure company with a 21.0% ROIC and EPS growth of 49.9% annualised. Infracom provides fibre connectivity and managed network services to Swedish businesses — recurring subscription revenue from essential digital infrastructure.", ["Fibre networks, managed connectivity and cloud services for Swedish businesses.", "ROIC of 21.0% reflects strong returns from essential digital connectivity infrastructure.", "EPS grew 49.9% annualised as broadband demand and managed service adoption expanded.", "Recurring subscription revenue from essential internet infrastructure services."]),
    627: ('InfuSystems Holdings Inc', 'US infusion therapy services. Growth recovery.', 'Infusion therapy services.', "InfuSystems provides ambulatory infusion pump management for cancer patients across the US. The company manages infusion pumps for home chemotherapy and other ambulatory treatments — a growing market as healthcare shifts to home-based care.", 'Infusion therapy. Growth recovery.', 'Healthcare services recovery.', "A US infusion therapy services company with an 8.6% ROIC providing ambulatory pump management for cancer patients. InfuSystems serves the growing home-based chemotherapy market — improving financial metrics as ambulatory infusion therapy adoption expands.", ["Ambulatory infusion pump management and oncology drug services for cancer patients.", "ROIC of 8.6% with improving trajectory as home-based care adoption expands.", "Revenue grew 6.4% annualised as home chemotherapy and ambulatory care demand increased.", "Growing market as healthcare systems push treatment from hospitals to home settings."]),
    628: ('Integrated Wind', 'Norwegian offshore wind developer. Exceptional growth.', 'Offshore wind developer.', "Integrated Wind is a Norwegian offshore wind project developer working on floating and fixed offshore wind projects in Northern Europe. The company is generating rapid revenue growth as offshore wind project activity accelerates.", 'Offshore wind development. Exceptional growth.', 'Offshore wind growth play.', "A Norwegian offshore wind developer with exceptional revenue growth of 90.9% annualised as offshore wind project development accelerates. Integrated Wind develops floating and fixed offshore wind projects — a direct beneficiary of Northern European offshore wind expansion targets.", ["Offshore wind project development — floating and fixed installations in Northern Europe.", "Revenue grew 90.9% annualised as offshore wind project pipeline expanded rapidly.", "EPS grew 430.3% annualised from a low base as development fees and project revenues grew.", "Direct beneficiary of Northern European offshore wind capacity expansion targets."]),
    629: ('Kendrion NV', 'Dutch electromagnetic components. Growth recovery.', 'Electromagnetic recovery play.', "Kendrion manufactures electromagnetic solenoids, brakes, and clutches for automotive and industrial applications. The company is recovering from supply chain disruptions with improving financial metrics as automotive production normalises.", 'Electromagnetic components. Growth recovery.', 'Electromagnetic recovery compounder.', "A Dutch electromagnetic component manufacturer with a 9.6% ROIC showing growth recovery. Kendrion solenoids and electromagnetic brakes serve automotive and industrial automation — improving earnings as automotive supply chain disruptions resolve.", ["Solenoids, brakes and clutches for automotive and industrial automation applications.", "ROIC of 9.6% recovering as automotive production normalises and industrial demand grows.", "EPS grew 24.6% annualised as the business recovers from supply chain disruptions.", "Industrial automation providing new revenue streams beyond automotive applications."]),
    630: ('Koninklijke Vopak NV', 'Dutch tank terminal infrastructure. High growth.', 'Global tank terminal operator.', "Vopak operates tank terminals for liquid bulk storage at ports globally — oil, chemicals, LNG, and biofuels. The company is expanding into LNG and hydrogen infrastructure as the energy transition creates new storage requirements.", 'Tank terminals. High growth momentum.', 'Terminal infrastructure compounder.', "A Dutch global tank terminal operator with a 9.7% ROIC and EPS growth of 17.6% annualised. Vopak operates liquid bulk storage at major global ports — expanding into LNG and hydrogen storage as energy transition creates structural new terminal demand.", ["Liquid bulk tank terminals for oil, chemicals, LNG and biofuels at global ports.", "ROIC of 9.7% from long-life terminal infrastructure with high barriers to entry.", "EPS grew 17.6% annualised as terminal utilisation and LNG storage demand improved.", "Energy transition expanding addressable market with LNG and hydrogen storage demand."]),
    632: ('Life360 Inc', 'US family location sharing app. High ROIC.', 'Family safety app leader.', "Life360 is a US company operating a family location sharing and safety platform with 60+ million active users globally. The company has transitioned to a subscription model generating high recurring revenue from premium family safety features.", 'Family safety app. High ROIC growth.', 'Safety app compounder.', "A US family location sharing platform with a 40.9% ROIC and EPS growth of 51.2% annualised. Life360 has 60+ million global users and is successfully converting free users to paid subscribers — exceptional capital efficiency from a scalable consumer subscription platform.", ["Family location sharing and safety platform with 60+ million global active users.", "ROIC of 40.9% — exceptional returns from a scalable consumer subscription model.", "EPS grew 51.2% annualised as free-to-paid conversion and ARPU expanded.", "Revenue grew 31.8% annualised with consistent subscriber growth and premium tier adoption."]),
    633: ('LiveRamp Holdings Inc', 'US data connectivity platform. High ROIC.', 'Data connectivity platform.', "LiveRamp provides a data connectivity platform that helps companies safely share and use first-party data for advertising and analytics. The company operates a data collaboration network connecting advertisers with publishers in a privacy-safe environment.", 'Data connectivity. High ROIC growth.', 'Data platform compounder.', "A US data connectivity platform with an 11.2% ROIC and EPS growth of 22.7% annualised. LiveRamp enables privacy-safe data collaboration between advertisers and publishers — a growing market as third-party cookie deprecation drives demand for first-party data solutions.", ["Privacy-safe data connectivity platform for advertisers and publishers.", "ROIC of 11.2% reflects improving returns from the data collaboration network.", "EPS grew 22.7% annualised as data connectivity demand expanded with cookie deprecation.", "Revenue grew 9.2% annualised with consistent enterprise data platform adoption."]),
    635: ('Navigator Holdings Ltd', 'Marshall Islands LPG tankers. High growth.', 'LPG tanker growth play.', "Navigator Holdings operates handysize LPG and petrochemical tankers serving global LPG and ethylene trade routes. The company benefits from growing LPG export volumes from the US Gulf Coast driving structural tonne-mile demand.", 'LPG tankers. Strong growth momentum.', 'LPG tanker growth compounder.', "A Marshall Islands LPG tanker operator with EPS growth of 172.8% annualised from a low base. Navigator Holdings fleet serves global LPG and ethylene trade — benefiting from surging US LPG export volumes and growing petrochemical shipping demand.", ["Handysize LPG and petrochemical tanker fleet serving global gas trade routes.", "EPS grew 172.8% annualised as LPG trade volumes and tanker rates recovered strongly.", "Surging US Gulf Coast LPG export volumes driving additional tonne-mile demand.", "Revenue growing 3.6% annualised with improving fleet utilisation and rate environment."]),
    636: ('Omer-Decugis & Cie', 'French tropical fruit importer. High ROIC.', 'Tropical fruit distribution.', "Omer-Decugis is a French importer and distributor of tropical fruits — mangoes, pineapples, avocados, and citrus — serving French and European food retail and foodservice markets. The company benefits from growing European consumer demand for tropical and exotic fruits.", 'Tropical fruit distribution. High ROIC.', 'French fruit compounder.', "A French tropical fruit importer with a 16.4% ROIC and EPS growth of 30.9% annualised. Omer-Decugis distributes mangoes, pineapples, and exotic fruits to European retailers — benefiting from structural growth in European tropical fruit consumption.", ["Tropical fruit importing and distribution — mangoes, pineapples, avocados and citrus.", "ROIC of 16.4% reflects consistent returns from a specialty tropical fruit distribution business.", "EPS grew 30.9% annualised as European tropical fruit consumption expanded.", "Revenue grew 15.3% annualised with growing European demand for exotic and tropical produce."]),
}
with open(CARDS_PATH, "r", encoding="utf-8") as f:
    content = f.read()
updated = 0
for card_id, (company, tag, tagBold, tagFull, pick, pickBold, pickFull, bullets) in descriptions.items():
    pattern = re.compile(rf"(id: {card_id}, type: .JOKER..*?tag: ')[^']*('..*?tagBold: ')[^']*('..*?tagFull: \")[^\"]*(\",.*?pick: ')[^']*('..*?pickBold: ')[^']*('..*?pickFull: \")[^\"]*(\",)", re.DOTALL)
    replacement = rf"\g<1>{tag}\g<2>{tagBold}\g<3>{tagFull}\g<4>{pick}\g<5>{pickBold}\g<6>{pickFull}\g<7>"
    new_content = pattern.sub(replacement, content)
    if new_content != content:
        content = new_content
        updated += 1
        print(f"OK {card_id}: {company}")
    else:
        print(f"MISS {card_id}: {company}")
    bullets_str = ", ".join([f'"{b}"' for b in bullets])
    bp = re.compile(rf"(id: {card_id},.*?bullets: \[)[^\]]*\]", re.DOTALL)
    content = bp.sub(rf"\g<1>{bullets_str}]", content)
with open(CARDS_PATH, "w", encoding="utf-8") as f:
    f.write(content)
print(f"Updated: {updated}")
print(f"Remaining: {content.count('operates in')}")
