
import re
CARDS_PATH = '/Users/radekmajewski/Downloads/valujack/public/cards.js'
descriptions = {
    601: ('ACADIA Pharmaceuticals Inc', 'US CNS drug. Exceptional ROIC.', 'CNS pharmaceutical specialist.', "ACADIA Pharmaceuticals focuses on central nervous system disorders. Nuplazid is the first FDA-approved treatment for hallucinations associated with Parkinson disease psychosis — a rare condition with high unmet need and captive patient population.", 'Parkinson psychosis drug. Exceptional ROIC.', 'CNS rare disease compounder.', "A US CNS pharmaceutical company with an 83.7% ROIC and EPS growth of 26.9% annualised. ACADIA Nuplazid is the only FDA-approved treatment for Parkinson disease psychosis — exceptional capital efficiency from a rare disease drug with no treatment alternatives.", ["Nuplazid — only FDA-approved treatment for Parkinson disease psychosis.", "ROIC of 83.7% — exceptional returns from rare CNS disease drug pricing power.", "EPS grew 26.9% annualised as Nuplazid prescriptions grew consistently.", "Captive patient population with no treatment alternatives supports sustainable high pricing."]),
    602: ('Akita Drilling Ltd', 'Canadian contract drilling. Growth recovery.', 'Canadian drilling recovery.', "Akita Drilling is a Canadian contract drilling company providing land drilling services to oil and gas producers in Western Canada and internationally. The company is benefiting from rising Canadian energy investment and improved drilling activity.", 'Canadian drilling. Growth recovery.', 'Contract drilling recovery.', "A Canadian contract drilling company with a 6.2% ROIC recovering alongside rising Western Canadian energy investment. Akita provides land drilling services to oil and gas producers — improving utilisation and revenue as Canadian drilling activity expands.", ["Land drilling services for oil and gas producers in Western Canada and internationally.", "ROIC of 6.2% with improving trajectory as Canadian drilling activity recovers.", "EPS grew 16.5% annualised as Canadian energy investment and drilling demand expanded.", "Revenue grew 3.9% annualised with improving rig utilisation and day rates."]),
    603: ('Almirall SA', 'Spanish dermatology pharma. Revenue growth.', 'Dermatology pharmaceutical.', "Almirall is a Spanish pharmaceutical company focused on dermatology — skin disease treatments including biologics for psoriasis and atopic dermatitis. The company is transitioning to a pure dermatology specialist with growing biologic revenue.", 'Dermatology pharma. Strong revenue growth.', 'Dermatology specialist.', "A Spanish dermatology pharmaceutical company with revenue growth of 12.4% annualised transitioning to a pure dermatology specialist. Almirall biologic treatments for psoriasis and atopic dermatitis address large, growing patient populations with high unmet need.", ["Dermatology biologics and treatments for psoriasis and atopic dermatitis.", "Revenue grew 12.4% annualised as biologic dermatology prescriptions expanded.", "Transition to pure dermatology specialist strategy focusing portfolio and improving margins.", "Large and growing patient populations with psoriasis and atopic dermatitis globally."]),
    604: ('Amer Sports Inc', 'Premium sporting brands portfolio. High growth.', 'Sporting goods brand portfolio.', "Amer Sports owns premium brands including Arc teryx, Salomon, Wilson, and Peak Performance targeting outdoor, winter sports, and racquet sports markets. The company benefits from structural growth in outdoor and active lifestyle consumer spending.", 'Premium sporting brands. High growth.', 'Outdoor brands compounder.', "A Finnish sporting goods company with a 5.9% ROIC and EPS growth of 33.1% annualised owning premium brands including Arc teryx, Salomon, and Wilson. Amer Sports premium brand portfolio targets the structurally growing outdoor and active lifestyle consumer market.", ["Premium sporting brands — Arc teryx, Salomon, Wilson and Peak Performance.", "ROIC of 5.9% with improving trajectory as premium brand revenue scales.", "EPS grew 33.1% annualised as outdoor and active lifestyle spending expanded.", "Revenue grew 26.7% annualised with consistent premium brand growth across all segments."]),
    605: ('American Public Education Inc', 'US military online education. Growth recovery.', 'Military education recovery.', "American Public Education operates American Military University, the largest online education provider to the US military. The company is recovering as military education demand stabilises and its commercial higher education segment improves.", 'Military education. Growth recovery.', 'Online education recovery.', "A US military and public service online education company with an 11.6% ROIC showing growth recovery. American Public Education serves US military personnel and veterans — improving financial trajectory as enrolment and retention metrics recover.", ["American Military University — largest online education provider to the US military.", "ROIC of 11.6% with improving trajectory as enrolment and retention recover.", "Revenue growing as military tuition assistance demand stabilises.", "EPS improving as restructuring benefits and operational efficiency gains take effect."]),
    606: ('American Superconductor Corp', 'US power electronics and wind tech. High ROIC.', 'Power electronics growth play.', "American Superconductor provides power electronics and software for wind turbines, naval ships, and power grids. The company benefits from structural growth in renewable energy and grid modernisation investment.", 'Power electronics. High growth momentum.', 'Grid technology growth play.', "A US power electronics company with a 28.6% ROIC and EPS growth of 39.5% annualised. American Superconductor provides grid stability technology and wind power electronics — a direct beneficiary of global renewable energy investment and grid modernisation spending.", ["Power electronics and software for wind turbines, naval ships and power grids.", "ROIC of 28.6% reflects strong returns from proprietary grid and wind technology.", "EPS grew 39.5% annualised as renewable energy and grid investment accelerated.", "Revenue grew 41.0% annualised driven by structural grid modernisation and wind power demand."]),
    608: ('Aurinia Pharmaceuticals Inc', 'Canadian lupus nephritis drug. Exceptional ROIC.', 'Lupus nephritis treatment.', "Aurinia Pharmaceuticals produces Voclosporin — the first oral calcineurin inhibitor approved for lupus nephritis. The drug addresses a serious autoimmune kidney disease with limited treatment options and high pricing power.", 'Lupus nephritis drug. Exceptional ROIC.', 'Rare autoimmune compounder.', "A Canadian pharmaceutical company with a 110.5% ROIC from Voclosporin — the first oral treatment approved for lupus nephritis. Aurinia rare disease drug serves patients with limited treatment alternatives — exceptional capital efficiency from a commercially established orphan drug.", ["Voclosporin — first oral calcineurin inhibitor approved for lupus nephritis.", "ROIC of 110.5% — exceptional returns from rare autoimmune disease drug pricing.", "EPS grew 34.9% annualised as Voclosporin prescriptions expanded from launch.", "Limited treatment alternatives for lupus nephritis support sustainable high pricing."]),
    609: ('BK Technologies Corp', 'US public safety radios. High ROIC growth.', 'Public safety comms growth.', "BK Technologies manufactures mission-critical radios for police, fire, and EMS agencies. The company is growing strongly as public safety agencies upgrade aging communication equipment to meet new interoperability standards.", 'Public safety radios. High ROIC growth.', 'Safety communications compounder.', "A US public safety radio manufacturer with a 46.1% ROIC and EPS growth of 105.8% annualised. BK Technologies serves police, fire, and EMS agencies with government-certified radios — exceptional growth from public safety communication upgrade cycles.", ["Mission-critical radios for police, fire and EMS agencies — government-certified.", "ROIC of 46.1% reflects strong pricing power in safety communication equipment.", "EPS grew 105.8% annualised as public safety communication upgrade demand surged.", "Government certification and procurement cycles create recurring replacement demand."]),
    610: ('Bowman Consulting Group Ltd', 'US engineering and consulting. High growth.', 'Engineering consulting growth.', "Bowman Consulting is a US national engineering and technical services firm providing site development, infrastructure, and environmental consulting. The company is growing through acquisitions and organic market share gains across US infrastructure markets.", 'Engineering consulting. High growth momentum.', 'Infrastructure consulting compounder.', "A US engineering consulting company with EPS growth of 47.8% annualised. Bowman provides site development and infrastructure engineering — growing through acquisitions and US infrastructure investment tailwinds.", ["Site development, infrastructure and environmental consulting across the US.", "EPS grew 47.8% annualised as acquisitions and organic growth expanded the business.", "Revenue grew 14.9% annualised driven by US infrastructure investment and land development.", "National platform with consistent acquisition strategy building geographic coverage."]),
    611: ('Calavo Growers Inc', 'US avocado distributor. Growth recovery.', 'Avocado distribution leader.', "Calavo Growers is the largest US avocado distributor and fresh food company. The company is benefiting from structurally growing avocado consumption and its dominant supply chain position in the US fresh produce market.", 'Avocado distribution. Growth recovery.', 'Fresh food distribution compounder.', "A US avocado distributor with an 8.9% ROIC and EPS growth of 27.2% annualised. Calavo Growers dominates US avocado distribution — structural growth in avocado consumption and fresh food demand provides consistent volume growth.", ["Largest US avocado distributor and fresh food company.", "ROIC of 8.9% with improving trajectory as avocado margins and volumes recover.", "EPS grew 27.2% annualised as avocado consumption growth and margins improved.", "Structural growth in US avocado demand provides consistent volume expansion."]),
    612: ('Cameco Corp', 'Canadian uranium producer. High growth.', 'Uranium production leader.', "Cameco is one of the largest uranium producers globally, mining uranium from operations in Canada and Kazakhstan. The company benefits from structural growth in nuclear energy demand as governments pursue low-carbon electricity generation.", 'Uranium producer. High growth momentum.', 'Nuclear fuel compounder.', "A Canadian uranium producer with a 7.4% ROIC and EPS growth of 65.4% annualised. Cameco produces uranium from world-class Canadian and Kazakh mines — a direct beneficiary of the nuclear energy renaissance as countries pursue low-carbon electricity.", ["Major uranium producer from Canadian and Kazakh mining operations.", "ROIC of 7.4% with improving trajectory as uranium prices recover toward incentive levels.", "EPS grew 65.4% annualised as uranium demand and pricing strengthened significantly.", "Revenue grew 11.0% annualised as nuclear energy renaissance drives structural uranium demand."]),
    613: ('Cematrix Corp', 'Canadian cellular concrete technology. High growth.', 'Cellular concrete innovation.', "Cematrix produces cellular concrete — a lightweight, insulating concrete used for pipeline abandonment, void filling, and geotechnical applications. The company benefits from growing demand for pipeline abandonment as energy infrastructure ages.", 'Cellular concrete. High growth play.', 'Specialty concrete compounder.', "A Canadian cellular concrete company with a 12.7% ROIC and revenue growth of 27.5% annualised. Cematrix produces lightweight cellular concrete for pipeline abandonment and void filling — a growing market as North American energy infrastructure requires decommissioning.", ["Cellular concrete for pipeline abandonment, void filling and geotechnical applications.", "ROIC of 12.7% reflects consistent returns from specialty concrete technology.", "EPS grew 16.8% annualised as pipeline abandonment demand expanded.", "Revenue grew 27.5% annualised driven by growing North American infrastructure decommissioning."]),
    614: ('CNX Resources Corp', 'US Appalachian natural gas. High revenue growth.', 'Appalachian gas growth play.', "CNX Resources is a US natural gas producer and midstream company in the Appalachian Basin. The company has vertically integrated gas production with midstream infrastructure — generating strong free cash flow from low-cost Appalachian gas production.", 'Appalachian gas. High revenue growth.', 'Integrated gas compounder.', "A US Appalachian natural gas producer with a 7.9% ROIC and revenue growth of 48.9% annualised. CNX Resources vertically integrated operations generate consistent free cash flow — benefiting from structural US gas demand growth from LNG exports.", ["Natural gas production and midstream infrastructure in the Appalachian Basin.", "ROIC of 7.9% from vertically integrated gas production and midstream operations.", "EPS grew 30.9% annualised as gas prices and production volumes improved.", "Revenue grew 48.9% annualised as US LNG export demand drove gas price improvement."]),
    615: ('Coherent Corp', 'US photonics and laser technology. AI data centre play.', 'Photonics technology leader.', "Coherent is a US photonics, laser, and networking technology company serving data centres, communications, and industrial markets. The company is a major supplier of optical transceivers and laser components for AI data centre interconnects.", 'Photonics technology. AI infrastructure play.', 'AI data centre compounder.', "A US photonics and laser technology company with revenue growth of 18.6% annualised. Coherent produces optical transceivers for AI data centre interconnects — a direct beneficiary of the massive AI infrastructure investment driving unprecedented demand for high-speed optical networking.", ["Photonics, lasers and optical transceivers for AI data centres, telecom and industrial.", "Revenue grew 18.6% annualised as AI data centre optical networking demand surged.", "Direct beneficiary of AI infrastructure buildout driving optical transceiver demand.", "Leading position in high-speed optical components for next-generation data centre connectivity."]),
    619: ('eGain Corp', 'US AI customer service software. Exceptional ROIC.', 'AI customer service platform.', "eGain provides AI-powered customer service and knowledge management software to enterprises. The company platform helps businesses manage customer interactions across digital channels — a growing market as enterprises automate customer service operations.", 'AI customer service. Exceptional ROIC.', 'AI SaaS compounder.', "A US AI customer service software company with a 330.3% ROIC and EPS growth of 42.4% annualised. eGain provides AI-powered knowledge management platforms to enterprises — exceptional capital efficiency from a scalable SaaS model with high recurring revenue.", ["AI-powered customer service and knowledge management software for enterprises.", "ROIC of 330.3% — extraordinary returns from an asset-light AI SaaS platform.", "EPS grew 42.4% annualised as AI customer service adoption expanded significantly.", "Scalable SaaS model with high recurring revenue and improving operating leverage."]),
}
with open(CARDS_PATH, "r", encoding="utf-8") as f:
    content = f.read()
updated = 0
for card_id, (company, tag, tagBold, tagFull, pick, pickBold, pickFull, bullets) in descriptions.items():
    import re
    pattern = re.compile(rf"(id: {card_id}, type: .JOKER..*?tag: )[^;]{{1,2000}}?(tagFull: \")[^\"]*(\",.*?pick: )[^;]{{1,2000}}?(pickFull: \")[^\"]*(\",)", re.DOTALL)
    pattern2 = re.compile(rf"(id: {card_id}, type: .JOKER..*?tag: ')[^']*('.*?tagBold: ')[^']*('.*?tagFull: \")[^\"]*(\",.*?pick: ')[^']*('.*?pickBold: ')[^']*('.*?pickFull: \")[^\"]*(\",)", re.DOTALL)
    replacement = rf"\g<1>{tag}\g<2>{tagBold}\g<3>{tagFull}\g<4>{pick}\g<5>{pickBold}\g<6>{pickFull}\g<7>"
    new_content = pattern2.sub(replacement, content)
    if new_content != content:
        content = new_content
        updated += 1
        print(f"OK {card_id}: {company}")
    else:
        print(f"MISS {card_id}: {company}")
    bullets_str = ", ".join([f'"{b}"' for b in bullets])
    bp = re.compile(rf"(id: {card_id},.*?bullets: \[)[^\]]*\]", re.DOTALL)
    content = bp.sub(rf"\g<1>{bullets_str}]", content)
with open(CARDS_PATH, "w", encoding="utf-8") as f:
    f.write(content)
print(f"Updated: {updated}, Remaining: {content.count(chr(111)+chr(112)+chr(101)+chr(114)+chr(97)+chr(116)+chr(101)+chr(115)+chr(32)+chr(105)+chr(110))}")
